import React,{useState} from 'react';
import { Platform,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,useWindowDimensions,View } from 'react-native';
import { armory } from './data';
import { IconArt } from './IconArt';
import { progressionRules } from './progressionRules';
import { ProgressionSnapshot } from './progression';
import { useProgressionSnapshot } from './useProgression';
import { useVitalTheme } from './ThemeProvider';
import DataStatePanel from './DataStatePanel';

type Filter='Earned'|'All';
export default function ArmoryV2(){
  const {theme}=useVitalTheme();const {snapshot,loading,error,refresh}=useProgressionSnapshot();const t=theme.tokens;const {width}=useWindowDimensions();const wide=width>=760;const [filter,setFilter]=useState<Filter>('Earned');
  const stateFor=(name:string)=>getState(name,snapshot);const earned=armory.filter(item=>stateFor(item.name)==='unlocked');const visible=filter==='Earned'?earned:armory;
  return <SafeAreaView style={[styles.safe,{backgroundColor:t.background}]}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={[styles.page,wide&&styles.pageWide]}><View style={styles.shell}>
    <View><Text style={[styles.eyebrow,{color:t.accent}]}>REWARDS</Text><Text style={[styles.title,{color:t.text}]}>What your work has earned.</Text><Text style={[styles.lede,{color:t.muted}]}>Rewards are outcomes of real progression. Nothing here advances separately from your training ledger.</Text></View>
    {loading?<DataStatePanel kind="loading" title="Loading your rewards" copy="Checking your progression milestones and earned collection." icon="trophy"/>:error?<DataStatePanel kind="error" title="Rewards couldn’t load" copy={error} actionLabel="Try again" onAction={()=>void refresh()} icon="trophy"/>:<>
    <View style={[styles.summary,{borderColor:t.border,backgroundColor:t.surface}]}><View style={styles.summaryIcon}><IconArt name="trophy" size={44}/></View><View style={{flex:1}}><Text style={[styles.eyebrow,{color:t.accent}]}>COLLECTION</Text><Text style={[styles.summaryTitle,{color:t.text}]}>{earned.length} of {armory.length} unlocked</Text><Text style={[styles.summaryCopy,{color:t.muted}]}>{snapshot.totalXP.toLocaleString()} lifetime XP · rewards unlock automatically as milestones are reached.</Text></View></View>
    <View style={[styles.tabs,{borderColor:t.border,backgroundColor:t.surface}]}>{(['Earned','All'] as Filter[]).map(item=>{const active=item===filter;return <Pressable key={item} onPress={()=>setFilter(item)} style={[styles.tab,active&&{backgroundColor:t.surfaceElevated,borderColor:t.accentSoft}]}><Text style={[styles.tabText,{color:active?t.accent:t.muted}]}>{item.toUpperCase()} {item==='Earned'?`· ${earned.length}`:`· ${armory.length}`}</Text></Pressable>})}</View>
    {visible.length?<View style={[styles.grid,wide&&styles.gridWide]}>{visible.map((item,index)=>{const state=stateFor(item.name);const requirement=requirementFor(item.name,snapshot);return <View key={item.name} style={[styles.card,{borderColor:state==='unlocked'?t.accentSoft:t.border,backgroundColor:t.surface},state==='locked'&&{opacity:.58}]}><View style={styles.cardTop}><IconArt name={index%2===0?'trophy':'armory'} size={42}/><Text style={[styles.state,{color:state==='unlocked'?t.accent:t.muted}]}>{state==='unlocked'?'EARNED':state==='progress'?'IN PROGRESS':'LOCKED'}</Text></View><Text style={[styles.kind,{color:t.muted}]}>{item.kind.toUpperCase()}</Text><Text style={[styles.name,{color:t.text}]}>{item.name}</Text><Text style={[styles.copy,{color:t.muted}]}>{state==='unlocked'?'Unlocked through real-world progression.':requirement}</Text></View>})}</View>:<DataStatePanel kind="empty" title="Your collection starts with training" copy="Complete sessions, build streaks, accumulate volume and XP, and rewards will appear here automatically." icon="trophy"/>}
    </>}
  </View></ScrollView></SafeAreaView>;
}
function getState(name:string,s:ProgressionSnapshot){if(name==='Iron Initiate')return s.unlocks.ironInitiate?'unlocked':'locked';if(name==='The Relentless')return s.unlocks.relentless?'unlocked':s.streakDays>0?'progress':'locked';if(name==='The Restored')return s.unlocks.restored?'unlocked':s.recoveryCount>0?'progress':'locked';if(name==='Forged Helm')return s.unlocks.forgedHelm?'unlocked':s.workoutCount>0?'progress':'locked';if(name==='Titan Plate')return s.unlocks.titanPlate?'unlocked':s.totalVolume>0?'progress':'locked';if(name==='Roadrunner Greaves')return s.unlocks.roadrunnerGreaves?'unlocked':s.lifetimeMiles>0?'progress':'locked';if(name==='Ember Aura')return s.unlocks.emberAura?'unlocked':s.totalXP>0?'progress':'locked';return'locked'}
function requirementFor(name:string,s:ProgressionSnapshot){const u=progressionRules.unlocks;if(name==='Iron Initiate')return`${Math.min(s.workoutCount,u.ironInitiate.target)} / ${u.ironInitiate.target} workout`;if(name==='The Relentless')return`${Math.min(s.streakDays,u.relentless.target)} / ${u.relentless.target} day streak`;if(name==='The Restored')return`${Math.min(s.recoveryCount,u.restored.target)} / ${u.restored.target} recovery sessions`;if(name==='Forged Helm')return`${Math.min(s.workoutCount,u.forgedHelm.target)} / ${u.forgedHelm.target} workouts`;if(name==='Titan Plate')return`${Math.min(Math.round(s.totalVolume),u.titanPlate.target).toLocaleString()} / ${u.titanPlate.target.toLocaleString()} lb`;if(name==='Roadrunner Greaves')return`${Math.min(s.lifetimeMiles,u.roadrunnerGreaves.target).toFixed(1)} / ${u.roadrunnerGreaves.target.toFixed(1)} miles`;if(name==='Ember Aura')return`${Math.min(s.totalXP,u.emberAura.target).toLocaleString()} / ${u.emberAura.target.toLocaleString()} XP`;return'Requirement hidden'}
const styles=StyleSheet.create({safe:{flex:1},page:{padding:16,paddingBottom:124},pageWide:{padding:28},shell:{width:'100%',maxWidth:1080,alignSelf:'center',gap:16},eyebrow:{fontSize:8,fontWeight:'900',letterSpacing:1.3},title:{fontFamily:Platform.select({ios:'Georgia',default:'serif'}),fontSize:36,fontWeight:'900',marginTop:5},lede:{fontSize:11,lineHeight:17,marginTop:6,maxWidth:650},summary:{borderWidth:1,borderRadius:18,padding:16,flexDirection:'row',alignItems:'center',gap:12},summaryIcon:{width:58,height:58,alignItems:'center',justifyContent:'center'},summaryTitle:{fontSize:22,fontWeight:'900',marginTop:4},summaryCopy:{fontSize:9.5,lineHeight:14,marginTop:4},tabs:{flexDirection:'row',borderWidth:1,borderRadius:14,padding:4,gap:4},tab:{flex:1,minHeight:42,borderWidth:1,borderColor:'transparent',borderRadius:10,alignItems:'center',justifyContent:'center'},tabText:{fontSize:8,fontWeight:'900',letterSpacing:.8},grid:{gap:10},gridWide:{flexDirection:'row',flexWrap:'wrap'},card:{flex:1,minWidth:220,borderWidth:1,borderRadius:16,padding:15,minHeight:190},cardTop:{flexDirection:'row',alignItems:'flex-start',justifyContent:'space-between'},state:{fontSize:7,fontWeight:'900',letterSpacing:.8},kind:{fontSize:7,fontWeight:'900',letterSpacing:1,marginTop:16},name:{fontSize:18,fontWeight:'900',marginTop:4},copy:{fontSize:9,lineHeight:14,marginTop:7}});
