import React,{useState} from 'react';
import { Platform,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,useWindowDimensions,View } from 'react-native';
import { armory } from './data';
import { IconArt } from './IconArt';
import { progressionRules } from './progressionRules';
import { ProgressionSnapshot } from './progression';
import { useProgressionSnapshot } from './useProgression';
import { useVitalTheme } from './ThemeProvider';
import DataStatePanel from './DataStatePanel';
import { Entrance } from './Interaction';

type Filter='Earned'|'All';
export default function ArmoryV2(){
  const {theme}=useVitalTheme();const {snapshot,loading,error,refresh}=useProgressionSnapshot();const t=theme.tokens;const {width}=useWindowDimensions();const wide=width>=760;const [filter,setFilter]=useState<Filter>('Earned');
  const stateFor=(name:string)=>getState(name,snapshot);const earned=armory.filter(item=>stateFor(item.name)==='unlocked');const visible=filter==='Earned'?earned:armory;const ratio=armory.length?earned.length/armory.length:0;
  return <SafeAreaView style={[styles.safe,{backgroundColor:t.background}]}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={[styles.page,wide&&styles.pageWide]}><View style={styles.shell}>
    <Entrance><View><Text style={[styles.eyebrow,{color:t.accent}]}>REWARDS</Text><Text style={[styles.title,{color:t.text}]}>What your work has earned.</Text><Text style={[styles.lede,{color:t.muted}]}>Milestones become visible artifacts of progression. Nothing here advances separately from your training ledger.</Text></View></Entrance>
    {loading?<DataStatePanel kind="loading" title="Loading your rewards" copy="Checking your progression milestones and earned collection." icon="trophy"/>:error?<DataStatePanel kind="error" title="Rewards couldn’t load" copy={error} actionLabel="Try again" onAction={()=>void refresh()} icon="trophy"/>:<>
    <Entrance delay={45}><View style={[styles.collectionRail,{borderColor:t.border}]}><View style={[styles.collectionIcon,{borderColor:t.border,backgroundColor:t.heroSurface}]}><IconArt name="trophy" size={40}/></View><View style={styles.collectionCore}><Text style={[styles.eyebrow,{color:t.accent}]}>COLLECTION STATUS</Text><View style={styles.collectionTop}><Text style={[styles.collectionTitle,{color:t.text}]}>{earned.length} of {armory.length} earned</Text><Text style={[styles.collectionPct,{color:t.accent}]}>{Math.round(ratio*100)}%</Text></View><View style={[styles.track,{backgroundColor:t.surfaceElevated}]}><View style={[styles.fill,{width:`${ratio*100}%`,backgroundColor:t.accent}]}/></View><Text style={[styles.collectionCopy,{color:t.muted}]}>{snapshot.totalXP.toLocaleString()} lifetime XP · rewards unlock automatically when progression milestones are reached.</Text></View></View></Entrance>

    <Entrance delay={85}><View style={[styles.tabs,{borderColor:t.border}]}>{(['Earned','All'] as Filter[]).map(item=>{const active=item===filter;return <Pressable key={item} onPress={()=>setFilter(item)} style={[styles.tab,active&&{backgroundColor:t.heroSurface,borderColor:t.accentSoft}]}><Text style={[styles.tabText,{color:active?t.accent:t.muted}]}>{item.toUpperCase()} {item==='Earned'?`· ${earned.length}`:`· ${armory.length}`}</Text></Pressable>})}</View></Entrance>

    {visible.length?<View style={[styles.grid,wide&&styles.gridWide]}>{visible.map((item,index)=>{const state=stateFor(item.name);const requirement=requirementFor(item.name,snapshot);const unlocked=state==='unlocked';return <Entrance key={item.name} delay={120+index*25} style={wide?styles.rewardEntranceWide:undefined}><View style={[styles.rewardCard,{borderColor:unlocked?t.accentSoft:t.border,backgroundColor:unlocked?t.surface:'transparent'},state==='locked'&&{opacity:.52}]}><View style={styles.rewardTop}><View style={[styles.iconFrame,{borderColor:unlocked?t.accentSoft:t.border,backgroundColor:t.heroSurface}]}><IconArt name={index%2===0?'trophy':'armory'} size={38}/></View><Text style={[styles.state,{color:unlocked?t.accent:t.muted}]}>{unlocked?'EARNED':state==='progress'?'IN PROGRESS':'LOCKED'}</Text></View><Text style={[styles.kind,{color:t.muted}]}>{item.kind.toUpperCase()}</Text><Text style={[styles.name,{color:t.text}]}>{item.name}</Text><View style={[styles.requirement,{borderTopColor:t.border}]}><Text style={[styles.reqLabel,{color:t.muted}]}>{unlocked?'UNLOCKED':'REQUIREMENT'}</Text><Text style={[styles.copy,{color:unlocked?t.text:t.muted}]}>{unlocked?'Earned through verified real-world progression.':requirement}</Text></View></View></Entrance>})}</View>:<DataStatePanel kind="empty" title="Your collection starts with training" copy="Complete sessions, build streaks, accumulate volume and XP, and rewards will appear here automatically." icon="trophy"/>}
    </>}
  </View></ScrollView></SafeAreaView>;
}
function getState(name:string,s:ProgressionSnapshot){if(name==='Iron Initiate')return s.unlocks.ironInitiate?'unlocked':'locked';if(name==='The Relentless')return s.unlocks.relentless?'unlocked':s.streakDays>0?'progress':'locked';if(name==='The Restored')return s.unlocks.restored?'unlocked':s.recoveryCount>0?'progress':'locked';if(name==='Forged Helm')return s.unlocks.forgedHelm?'unlocked':s.workoutCount>0?'progress':'locked';if(name==='Titan Plate')return s.unlocks.titanPlate?'unlocked':s.totalVolume>0?'progress':'locked';if(name==='Roadrunner Greaves')return s.unlocks.roadrunnerGreaves?'unlocked':s.lifetimeMiles>0?'progress':'locked';if(name==='Ember Aura')return s.unlocks.emberAura?'unlocked':s.totalXP>0?'progress':'locked';return'locked'}
function requirementFor(name:string,s:ProgressionSnapshot){const u=progressionRules.unlocks;if(name==='Iron Initiate')return`${Math.min(s.workoutCount,u.ironInitiate.target)} / ${u.ironInitiate.target} workout`;if(name==='The Relentless')return`${Math.min(s.streakDays,u.relentless.target)} / ${u.relentless.target} day streak`;if(name==='The Restored')return`${Math.min(s.recoveryCount,u.restored.target)} / ${u.restored.target} recovery sessions`;if(name==='Forged Helm')return`${Math.min(s.workoutCount,u.forgedHelm.target)} / ${u.forgedHelm.target} workouts`;if(name==='Titan Plate')return`${Math.min(Math.round(s.totalVolume),u.titanPlate.target).toLocaleString()} / ${u.titanPlate.target.toLocaleString()} lb`;if(name==='Roadrunner Greaves')return`${Math.min(s.lifetimeMiles,u.roadrunnerGreaves.target).toFixed(1)} / ${u.roadrunnerGreaves.target.toFixed(1)} miles`;if(name==='Ember Aura')return`${Math.min(s.totalXP,u.emberAura.target).toLocaleString()} / ${u.emberAura.target.toLocaleString()} XP`;return'Requirement hidden'}
const styles=StyleSheet.create({safe:{flex:1},page:{padding:16,paddingBottom:124},pageWide:{padding:28},shell:{width:'100%',maxWidth:1080,alignSelf:'center',gap:16},eyebrow:{fontSize:7,fontWeight:'900',letterSpacing:1.45},title:{fontFamily:Platform.select({ios:'Georgia',default:'serif'}),fontSize:39,lineHeight:44,fontWeight:'900',marginTop:5,letterSpacing:-.8},lede:{fontSize:10.5,lineHeight:17,marginTop:7,maxWidth:650},collectionRail:{borderTopWidth:1,borderBottomWidth:1,paddingVertical:15,flexDirection:'row',alignItems:'center',gap:14},collectionIcon:{width:62,height:62,borderWidth:1,borderRadius:18,alignItems:'center',justifyContent:'center'},collectionCore:{flex:1,minWidth:220},collectionTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'baseline',gap:10},collectionTitle:{fontSize:21,fontWeight:'900',marginTop:3},collectionPct:{fontSize:17,fontWeight:'900'},collectionCopy:{fontSize:8.5,lineHeight:13,marginTop:7},track:{height:7,borderRadius:99,overflow:'hidden',marginTop:9},fill:{height:'100%',borderRadius:99},tabs:{flexDirection:'row',borderWidth:1,borderRadius:14,padding:4,gap:4},tab:{flex:1,minHeight:42,borderWidth:1,borderColor:'transparent',borderRadius:10,alignItems:'center',justifyContent:'center'},tabText:{fontSize:7.5,fontWeight:'900',letterSpacing:.9},grid:{gap:10},gridWide:{flexDirection:'row',flexWrap:'wrap'},rewardEntranceWide:{flexGrow:1,flexBasis:300},rewardCard:{flex:1,borderWidth:1,borderRadius:20,padding:16,minHeight:210},rewardTop:{flexDirection:'row',alignItems:'flex-start',justifyContent:'space-between'},iconFrame:{width:54,height:54,borderWidth:1,borderRadius:16,alignItems:'center',justifyContent:'center'},state:{fontSize:6.5,fontWeight:'900',letterSpacing:.9},kind:{fontSize:6.5,fontWeight:'900',letterSpacing:1.05,marginTop:16},name:{fontSize:20,fontWeight:'900',marginTop:4},requirement:{borderTopWidth:1,marginTop:18,paddingTop:11},reqLabel:{fontSize:6,fontWeight:'900',letterSpacing:.8},copy:{fontSize:9,lineHeight:14,marginTop:4}});
