import React,{useState}from'react';
import{Pressable,StyleSheet,Text,TextInput,View}from'react-native';
import{useSQLiteContext}from'expo-sqlite';
import{saveBetaFeedback}from'./db';
import{makeFeedbackId,shouldSampleSessionFeedback}from'./betaFeedback';
import{useVitalTheme}from'./ThemeProvider';

type Props={sessionId:string;context?:Record<string,unknown>;alwaysShow?:boolean};
export default function BetaSessionFeedback({sessionId,context={},alwaysShow=false}:Props){
  const db=useSQLiteContext();const{theme}=useVitalTheme();const t=theme.tokens;
  const [fair,setFair]=useState<boolean|null>(null);const[clear,setClear]=useState<boolean|null>(null);const[notes,setNotes]=useState('');const[saved,setSaved]=useState(false);const[saving,setSaving]=useState(false);
  if(!alwaysShow&&!shouldSampleSessionFeedback(sessionId))return null;
  if(saved)return <View style={[styles.card,{borderColor:t.border,backgroundColor:t.heroSurface}]}><Text style={[styles.kicker,{color:t.accent}]}>BETA 1 FEEDBACK</Text><Text style={[styles.title,{color:t.text}]}>Feedback recorded.</Text><Text style={[styles.copy,{color:t.muted}]}>This response is tied to the session's XP trust record so we can tune fairness from real use.</Text></View>;
  async function submit(){if(fair==null||clear==null)return;setSaving(true);await saveBetaFeedback(db,{id:makeFeedbackId('session-feedback'),sessionId,kind:'session',fairCredit:fair,explanationClear:clear,notes:notes.trim(),context});setSaved(true);setSaving(false);}
  return <View style={[styles.card,{borderColor:t.accentSoft,backgroundColor:t.heroSurface}]}><Text style={[styles.kicker,{color:t.accent}]}>BETA 1 CHECK-IN</Text><Text style={[styles.title,{color:t.text}]}>Did VitalQuest judge this fairly?</Text><Question label="Did this workout get fair XP credit?" value={fair} onChange={setFair}/><Question label="Did the XP explanation make sense?" value={clear} onChange={setClear}/><TextInput value={notes} onChangeText={setNotes} placeholder="Anything unusual? Optional" placeholderTextColor={t.muted} multiline style={[styles.input,{color:t.text,borderColor:t.border,backgroundColor:t.surface}]}/><Pressable disabled={fair==null||clear==null||saving} onPress={submit} style={[styles.submit,{backgroundColor:t.accent,opacity:fair==null||clear==null||saving?0.45:1}]}><Text style={[styles.submitText,{color:t.background}]}>{saving?'SAVING...':'SUBMIT BETA FEEDBACK'}</Text></Pressable></View>;
  function Question({label,value,onChange}:{label:string;value:boolean|null;onChange:(v:boolean)=>void}){return <View style={styles.question}><Text style={[styles.label,{color:t.text}]}>{label}</Text><View style={styles.row}><Choice active={value===true} label="YES" onPress={()=>onChange(true)}/><Choice active={value===false} label="NO" onPress={()=>onChange(false)}/></View></View>}
  function Choice({active,label,onPress}:{active:boolean;label:string;onPress:()=>void}){return <Pressable onPress={onPress} style={[styles.choice,{borderColor:active?t.accent:t.border,backgroundColor:active?t.surfaceElevated:t.surface}]}><Text style={[styles.choiceText,{color:active?t.accent:t.muted}]}>{label}</Text></Pressable>}
}
const styles=StyleSheet.create({card:{width:'100%',borderWidth:1,borderRadius:16,padding:15,marginTop:12},kicker:{fontSize:9.5,fontWeight:'900',letterSpacing:1.1},title:{fontSize:17,fontWeight:'900',marginTop:4},copy:{fontSize:9,lineHeight:14,marginTop:5},question:{marginTop:14},label:{fontSize:10,fontWeight:'800',marginBottom:7},row:{flexDirection:'row',gap:8},choice:{flex:1,minHeight:42,borderWidth:1,borderRadius:9,alignItems:'center',justifyContent:'center'},choiceText:{fontSize:8.5,fontWeight:'900',letterSpacing:.7},input:{minHeight:74,borderWidth:1,borderRadius:10,padding:10,fontVariant:['tabular-nums'],fontSize:10,lineHeight:15,textAlignVertical:'top',marginTop:14},submit:{minHeight:48,borderRadius:10,alignItems:'center',justifyContent:'center',marginTop:10},submitText:{fontSize:8.5,fontWeight:'900',letterSpacing:.8}});
