import{router}from'expo-router';
import{useSQLiteContext}from'expo-sqlite';
import React,{useState}from'react';
import{Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View}from'react-native';
import{makeFeedbackId}from'./betaFeedback';
import{saveBetaFeedback}from'./db';
import{useVitalTheme}from'./ThemeProvider';

const categories=['XP / TRUST','WORKOUT','BUG','UI / UX','QUEST / PROGRESSION','OTHER'] as const;
export default function BetaFeedbackV2(){
 const db=useSQLiteContext();const{theme}=useVitalTheme();const t=theme.tokens;const[category,setCategory]=useState<(typeof categories)[number]>('BUG');const[notes,setNotes]=useState('');const[saved,setSaved]=useState(false);const[saving,setSaving]=useState(false);
 async function submit(){if(!notes.trim())return;setSaving(true);await saveBetaFeedback(db,{id:makeFeedbackId('issue'),kind:'issue',notes:notes.trim(),context:{category,source:'beta_issue_reporter'}});setSaved(true);setSaving(false);}
 return <SafeAreaView style={[styles.safe,{backgroundColor:t.background}]}><ScrollView contentContainerStyle={styles.page}><View style={styles.shell}><View style={styles.top}><Pressable onPress={()=>router.back()}><Text style={[styles.back,{color:t.muted}]}>‹ BACK</Text></Pressable><Text style={[styles.meta,{color:t.accent}]}>WEB BETA 1</Text></View><View style={[styles.hero,{borderColor:t.accentSoft,backgroundColor:t.heroSurface}]}><Text style={[styles.kicker,{color:t.accent}]}>BETA FEEDBACK</Text><Text style={[styles.title,{color:t.text}]}>Something feel off?</Text><Text style={[styles.copy,{color:t.muted}]}>Tell us while the context is fresh. Reports are stored locally with the beta ledger and queued for future sync.</Text></View>{saved?<View style={[styles.card,{borderColor:t.border,backgroundColor:t.surface}]}><Text style={[styles.titleSmall,{color:t.text}]}>Report recorded.</Text><Text style={[styles.copy,{color:t.muted}]}>Thanks. This will help us separate XP-calibration problems from ordinary product bugs.</Text><Pressable onPress={()=>router.back()} style={[styles.primary,{backgroundColor:t.accent}]}><Text style={[styles.primaryText,{color:t.background}]}>RETURN TO VITALQUEST</Text></Pressable></View>:<><View style={[styles.card,{borderColor:t.border,backgroundColor:t.surface}]}><Text style={[styles.kicker,{color:t.accent}]}>CATEGORY</Text><View style={styles.chips}>{categories.map(item=><Pressable key={item} onPress={()=>setCategory(item)} style={[styles.chip,{borderColor:category===item?t.accent:t.border,backgroundColor:category===item?t.surfaceElevated:t.heroSurface}]}><Text style={[styles.chipText,{color:category===item?t.accent:t.muted}]}>{item}</Text></Pressable>)}</View></View><View style={[styles.card,{borderColor:t.border,backgroundColor:t.surface}]}><Text style={[styles.kicker,{color:t.accent}]}>WHAT HAPPENED?</Text><TextInput value={notes} onChangeText={setNotes} placeholder="What did you expect, and what happened instead?" placeholderTextColor={t.muted} multiline style={[styles.input,{color:t.text,borderColor:t.border,backgroundColor:t.heroSurface}]}/><Pressable disabled={!notes.trim()||saving} onPress={submit} style={[styles.primary,{backgroundColor:t.accent,opacity:!notes.trim()||saving?.45:1}]}><Text style={[styles.primaryText,{color:t.background}]}>{saving?'SAVING...':'SUBMIT BETA REPORT'}</Text></Pressable></View></>}</View></ScrollView></SafeAreaView>
}
const styles=StyleSheet.create({safe:{flex:1},page:{padding:16,paddingBottom:100},shell:{width:'100%',maxWidth:760,alignSelf:'center',gap:14},top:{minHeight:44,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},back:{fontSize:9,fontWeight:'900',letterSpacing:.8},meta:{fontSize:8,fontWeight:'900',letterSpacing:1.2},hero:{borderWidth:1,borderRadius:18,padding:20},kicker:{fontSize:7.5,fontWeight:'900',letterSpacing:1.2},title:{fontSize:30,fontWeight:'900',marginTop:5},titleSmall:{fontSize:18,fontWeight:'900'},copy:{fontSize:10,lineHeight:16,marginTop:6},card:{borderWidth:1,borderRadius:15,padding:14},chips:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:11},chip:{borderWidth:1,borderRadius:999,paddingHorizontal:11,paddingVertical:9},chipText:{fontSize:7.5,fontWeight:'900',letterSpacing:.6},input:{minHeight:150,borderWidth:1,borderRadius:11,padding:12,fontSize:11,lineHeight:17,textAlignVertical:'top',marginTop:10},primary:{minHeight:52,borderRadius:10,alignItems:'center',justifyContent:'center',marginTop:12},primaryText:{fontSize:9,fontWeight:'900',letterSpacing:.9}});
