import { router } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import React,{useMemo,useState} from 'react';
import { Alert,Platform,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { saveCustomWorkout } from './db';
import { useTrainingSetup } from './useTrainingSetup';
import { CustomWorkoutExercise,EXERCISE_CATALOG,equipmentSupports } from './trainingPreferences';
import { useVitalTheme } from './ThemeProvider';
import { GeneratedWorkoutPlan } from './workoutGenerator';

const makeId=()=>`custom-${Date.now()}-${Math.random().toString(16).slice(2)}`;
export default function CustomWorkoutBuilderV2(){
  const db=useSQLiteContext();const {theme}=useVitalTheme();const t=theme.tokens;const {equipment}=useTrainingSetup();
  const [name,setName]=useState('Custom Trial');const [selected,setSelected]=useState<Record<string,CustomWorkoutExercise>>({});
  const available=useMemo(()=>EXERCISE_CATALOG.filter(item=>equipmentSupports(item.equipment,equipment)),[equipment]);
  const toggle=(id:string)=>{const item=available.find(x=>x.id===id);if(!item)return;setSelected(current=>{const next={...current};if(next[id])delete next[id];else next[id]={id:item.id,name:item.name,muscle:item.muscle,prescribedSets:item.defaultSets,targetReps:item.defaultReps};return next})};
  const adjust=(id:string,field:'prescribedSets'|'targetReps',delta:number)=>setSelected(current=>({...current,[id]:{...current[id],[field]:Math.max(1,current[id][field]+delta)}}));
  const exercises=Object.values(selected);const totalSets=exercises.reduce((sum,e)=>sum+e.prescribedSets,0);const estimatedMinutes=Math.max(20,Math.round(totalSets*2.6));const projectedXP=100+totalSets*6+Math.min(60,Math.floor(estimatedMinutes*1.25));
  async function saveAndStart(start:boolean){if(!exercises.length){Alert.alert('Add at least one exercise','Choose movements before saving this loadout.');return;}const id=makeId();const workout={id,name:name.trim()||'Custom Trial',createdAt:new Date().toISOString(),exercises};await saveCustomWorkout(db,workout);if(start){const plan:GeneratedWorkoutPlan={id,name:workout.name,focus:'full',targetXP:projectedXP,projectedXP,estimatedMinutes,rationale:'Custom loadout built from your selected movements and equipment profile.',coachingNote:'Actual XP is awarded from the work you complete.',qualityScore:100,qualityLabel:'ELITE FIT',deload:false,exercises:exercises.map(e=>({id:e.id,name:e.name,muscle:e.muscle,sets:e.prescribedSets,reps:e.targetReps,suggestedWeight:null,prescriptionRationale:'Custom loadout. Choose a comfortable working load; saved ledger history will calibrate future prescriptions.'}))};router.replace({pathname:'/generated-workout',params:{plan:encodeURIComponent(JSON.stringify(plan))}})}else router.back();}
  return <SafeAreaView style={[styles.safe,{backgroundColor:t.background}]}><ScrollView contentContainerStyle={styles.page}><View style={styles.shell}>
    <Pressable onPress={()=>router.back()}><Text style={[styles.back,{color:t.muted}]}>‹ TRAIN</Text></Pressable><View><Text style={[styles.eyebrow,{color:t.accent}]}>CUSTOM LOADOUT</Text><Text style={[styles.title,{color:t.text}]}>Build your own trial.</Text><Text style={[styles.copy,{color:t.muted}]}>Only exercises supported by your equipment profile appear here. Saved loadouts can be reused later.</Text></View>
    <View style={[styles.nameCard,{borderColor:t.border,backgroundColor:t.surface}]}><Text style={[styles.label,{color:t.muted}]}>LOADOUT NAME</Text><TextInput value={name} onChangeText={setName} placeholder="Custom Trial" placeholderTextColor={t.muted} style={[styles.nameInput,{borderColor:t.border,color:t.text}]}/><View style={styles.stats}><Stat value={String(exercises.length)} label="EXERCISES"/><Stat value={String(totalSets)} label="SETS"/><Stat value={`~${estimatedMinutes}`} label="MIN"/><Stat value={`~${projectedXP}`} label="XP"/></View></View>
    <View style={styles.grid}>{available.map(item=>{const active=selected[item.id];return <View key={item.id} style={[styles.card,{borderColor:active?t.accent:t.border,backgroundColor:active?t.surfaceElevated:t.surface}]}><Pressable onPress={()=>toggle(item.id)}><View style={styles.row}><View style={{flex:1}}><Text style={[styles.cardTitle,{color:t.text}]}>{item.name}</Text><Text style={[styles.cardCopy,{color:t.muted}]}>{item.muscle}</Text></View><View style={[styles.check,{borderColor:active?t.accent:t.border,backgroundColor:active?t.accent:'transparent'}]}><Text style={{color:active?t.background:t.muted,fontWeight:'900'}}>{active?'✓':'+'}</Text></View></View></Pressable>{active?<View style={[styles.controls,{borderTopColor:t.border}]}><Stepper label="SETS" value={active.prescribedSets} onMinus={()=>adjust(item.id,'prescribedSets',-1)} onPlus={()=>adjust(item.id,'prescribedSets',1)}/><Stepper label="REPS" value={active.targetReps} onMinus={()=>adjust(item.id,'targetReps',-1)} onPlus={()=>adjust(item.id,'targetReps',1)}/></View>:null}</View>})}</View>
    {!available.length?<View style={[styles.empty,{borderColor:t.border}]}><Text style={[styles.cardTitle,{color:t.text}]}>No compatible movements yet.</Text><Text style={[styles.copy,{color:t.muted}]}>Update your equipment profile to unlock exercises.</Text><Pressable onPress={()=>router.push('/equipment')}><Text style={[styles.link,{color:t.accent}]}>EDIT EQUIPMENT PROFILE</Text></Pressable></View>:null}
    <View style={styles.actions}><Pressable onPress={()=>saveAndStart(false)} style={[styles.secondary,{borderColor:t.border}]}><Text style={[styles.buttonText,{color:t.text}]}>SAVE LOADOUT</Text></Pressable><Pressable onPress={()=>saveAndStart(true)} style={[styles.primary,{backgroundColor:t.accent}]}><Text style={[styles.buttonText,{color:t.background}]}>SAVE + START</Text></Pressable></View>
  </View></ScrollView></SafeAreaView>
}
function Stat({value,label}:{value:string;label:string}){const {theme}=useVitalTheme();const t=theme.tokens;return <View style={[styles.stat,{borderColor:t.border,backgroundColor:t.heroSurface}]}><Text style={[styles.statValue,{color:t.text}]}>{value}</Text><Text style={[styles.statLabel,{color:t.muted}]}>{label}</Text></View>}
function Stepper({label,value,onMinus,onPlus}:{label:string;value:number;onMinus:()=>void;onPlus:()=>void}){const {theme}=useVitalTheme();const t=theme.tokens;return <View style={styles.stepper}><Text style={[styles.label,{color:t.muted}]}>{label}</Text><View style={styles.stepRow}><Pressable onPress={onMinus} style={[styles.stepButton,{borderColor:t.border}]}><Text style={{color:t.text,fontWeight:'900'}}>−</Text></Pressable><Text style={[styles.stepValue,{color:t.text}]}>{value}</Text><Pressable onPress={onPlus} style={[styles.stepButton,{borderColor:t.border}]}><Text style={{color:t.text,fontWeight:'900'}}>+</Text></Pressable></View></View>}
const styles=StyleSheet.create({safe:{flex:1},page:{padding:16,paddingBottom:100},shell:{width:'100%',maxWidth:950,alignSelf:'center',gap:15},back:{fontSize:8,fontWeight:'900',letterSpacing:.8},eyebrow:{fontSize:8,fontWeight:'900',letterSpacing:1.3},title:{fontFamily:Platform.select({ios:'Georgia',default:'serif'}),fontSize:34,fontWeight:'900',marginTop:5},copy:{fontSize:10,lineHeight:16,marginTop:5},nameCard:{borderWidth:1,borderRadius:16,padding:14},label:{fontSize:7,fontWeight:'900',letterSpacing:.8},nameInput:{borderWidth:1,borderRadius:9,minHeight:46,paddingHorizontal:12,fontSize:14,fontWeight:'800',marginTop:8},stats:{flexDirection:'row',gap:7,marginTop:12,flexWrap:'wrap'},stat:{flex:1,minWidth:90,borderWidth:1,borderRadius:9,padding:9,alignItems:'center'},statValue:{fontSize:15,fontWeight:'900'},statLabel:{fontSize:6.5,fontWeight:'900',marginTop:2},grid:{gap:9},card:{borderWidth:1,borderRadius:15,padding:13},row:{flexDirection:'row',alignItems:'center',gap:12},cardTitle:{fontSize:14,fontWeight:'900'},cardCopy:{fontSize:8.5,marginTop:3},check:{width:34,height:34,borderRadius:17,borderWidth:1,alignItems:'center',justifyContent:'center'},controls:{borderTopWidth:1,marginTop:12,paddingTop:11,flexDirection:'row',gap:20},stepper:{flex:1},stepRow:{flexDirection:'row',alignItems:'center',gap:10,marginTop:6},stepButton:{width:32,height:32,borderRadius:16,borderWidth:1,alignItems:'center',justifyContent:'center'},stepValue:{fontSize:15,fontWeight:'900',minWidth:24,textAlign:'center'},empty:{borderWidth:1,borderRadius:15,padding:20},link:{fontSize:8,fontWeight:'900',letterSpacing:.8,marginTop:10},actions:{flexDirection:'row',gap:8},secondary:{flex:1,minHeight:52,borderWidth:1,borderRadius:9,alignItems:'center',justifyContent:'center'},primary:{flex:1,minHeight:52,borderRadius:9,alignItems:'center',justifyContent:'center'},buttonText:{fontSize:9,fontWeight:'900',letterSpacing:.9}});
