import React from 'react';
import { ImageBackground, Platform, SafeAreaView, ScrollView, StyleSheet, Text, useWindowDimensions, View } from 'react-native';
import { useVitalTheme } from './ThemeProvider';
import { IconArt } from './IconArt';
import { ThemeId } from './theme';

const art:Record<ThemeId,string>={mythicForge:'/vitalquest-app/art/premium/mythic-hero.jpg',celestialPulse:'/vitalquest-app/art/today-celestial-premium.webp',titanCore:'/vitalquest-app/art/today-titan-premium.webp'};

export default function HeroV2(){
  const {theme,themeId}=useVitalTheme();const t=theme.tokens;const {width}=useWindowDimensions();const wide=width>=760;
  const attributes=[['Strength',153,.76,t.strength,'strength'],['Stamina',128,.64,t.stamina,'stamina'],['Agility',104,.52,t.agility,'agility'],['Power',137,.68,t.power,'xp'],['Discipline',171,.86,t.discipline,'streak']] as const;
  return <SafeAreaView style={[styles.safe,{backgroundColor:t.background}]}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={[styles.page,wide&&styles.pageWide]}><View style={styles.shell}>
    <View><Text style={[styles.eyebrow,{color:t.accent}]}>HERO PROFILE</Text><Text style={[styles.title,{color:t.text}]}>The Relentless</Text><Text style={[styles.lede,{color:t.muted}]}>Your training history, translated into identity.</Text></View>
    <View style={[styles.heroCard,{borderColor:t.border,backgroundColor:t.surface}]}><ImageBackground source={{uri:art[themeId as ThemeId]}} resizeMode="cover" style={[styles.heroArt,wide&&styles.heroArtWide]}><View style={styles.shade}/><View style={styles.heroCopy}><Text style={[styles.eyebrow,{color:t.accent}]}>VANGUARD · LEVEL 12</Text><Text style={[styles.heroName,{color:t.text}]}>Champion</Text><Text style={[styles.heroSub,{color:t.text}]}>12 day streak · 43 lifetime sessions</Text></View></ImageBackground><View style={styles.heroHud}><View style={styles.levelRow}><View style={[styles.levelOrb,{borderColor:t.accent,backgroundColor:t.heroSurface}]}><Text style={[styles.levelLabel,{color:t.muted}]}>LVL</Text><Text style={[styles.levelValue,{color:t.text}]}>12</Text></View><View style={{flex:1}}><Text style={[styles.className,{color:t.text}]}>Arclight Vanguard</Text><Text style={[styles.xpCopy,{color:t.muted}]}>1,180 / 1,800 XP · 620 XP to Level 13</Text><View style={[styles.track,{backgroundColor:t.surfaceElevated}]}><View style={[styles.fill,{width:'66%',backgroundColor:t.accent}]}/></View></View></View><View style={[styles.titlePlate,{borderColor:t.accentSoft,backgroundColor:t.heroSurface}]}><Text style={[styles.eyebrow,{color:t.accent}]}>ACTIVE TITLE</Text><Text style={[styles.activeTitle,{color:t.text}]}>Iron Vow</Text><Text style={[styles.activeCopy,{color:t.muted}]}>Show up. No excuses.</Text></View></View></View>
    <View style={[styles.summaryGrid,wide&&styles.summaryWide]}><Summary icon="strength" value="43" label="WORKOUTS"/><Summary icon="streak" value="12" label="DAY STREAK"/><Summary icon="trophy" value="8" label="BADGES"/><Summary icon="armory" value="3" label="TITLES"/></View>
    <View style={styles.sectionHead}><View><Text style={[styles.eyebrow,{color:t.accent}]}>ATTRIBUTES</Text><Text style={[styles.sectionTitle,{color:t.text}]}>Current build</Text></View><Text style={[styles.overall,{color:t.muted}]}>OVERALL 139</Text></View>
    <View style={[styles.attrCard,{borderColor:t.border,backgroundColor:t.surface}]}>{attributes.map(([name,value,ratio,color,icon],i)=><View key={name} style={[styles.attrRow,i<attributes.length-1&&{borderBottomWidth:1,borderBottomColor:t.border}]}><IconArt name={icon as any} size={34}/><View style={{flex:1}}><View style={styles.attrTop}><Text style={[styles.attrName,{color:t.text}]}>{name}</Text><Text style={[styles.attrValue,{color}]}>{value}</Text></View><View style={[styles.track,{backgroundColor:t.surfaceElevated}]}><View style={[styles.fill,{width:`${ratio*100}%`,backgroundColor:color}]}/></View></View></View>)}</View>
    <View style={[styles.featGrid,wide&&styles.featWide]}><Feat value="482K" label="LBS LIFTED" detail="Titan path · 48%" icon="strength"/><Feat value="74.2" label="MILES RUN" detail="Road path · 37%" icon="agility"/><Feat value="12" label="DAY STREAK" detail="Best: 18 days" icon="streak"/></View>
    <View style={[styles.badgeStrip,{borderColor:t.border,backgroundColor:t.heroSurface}]}><IconArt name="trophy" size={50}/><View style={{flex:1}}><Text style={[styles.eyebrow,{color:t.accent}]}>RECENT ACHIEVEMENT</Text><Text style={[styles.badgeTitle,{color:t.text}]}>Consistent</Text><Text style={[styles.badgeCopy,{color:t.muted}]}>Earned for maintaining a 7-day training streak.</Text></View></View>
  </View></ScrollView></SafeAreaView>
}

function Summary({icon,value,label}:{icon:'strength'|'streak'|'trophy'|'armory';value:string;label:string}){const {theme}=useVitalTheme();const t=theme.tokens;return <View style={[styles.summary,{borderColor:t.border,backgroundColor:t.surface}]}><IconArt name={icon} size={34}/><Text style={[styles.summaryValue,{color:t.text}]}>{value}</Text><Text style={[styles.summaryLabel,{color:t.muted}]}>{label}</Text></View>}
function Feat({value,label,detail,icon}:{value:string;label:string;detail:string;icon:'strength'|'agility'|'streak'}){const {theme}=useVitalTheme();const t=theme.tokens;return <View style={[styles.feat,{borderColor:t.border,backgroundColor:t.surface}]}><IconArt name={icon} size={38}/><Text style={[styles.featValue,{color:t.text}]}>{value}</Text><Text style={[styles.featLabel,{color:t.muted}]}>{label}</Text><Text style={[styles.featDetail,{color:t.accent}]}>{detail}</Text></View>}

const styles=StyleSheet.create({safe:{flex:1},page:{padding:14,paddingBottom:120},pageWide:{padding:24},shell:{width:'100%',maxWidth:1120,alignSelf:'center',gap:16},eyebrow:{fontSize:8,fontWeight:'900',letterSpacing:1.5},title:{fontFamily:Platform.select({ios:'Georgia',default:'serif'}),fontSize:36,fontWeight:'900',marginTop:5},lede:{fontSize:11,lineHeight:17,marginTop:5},heroCard:{overflow:'hidden',borderWidth:1,borderRadius:20},heroArt:{height:320,justifyContent:'flex-end'},heroArtWide:{height:420},shade:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(0,0,0,.32)'},heroCopy:{padding:20,maxWidth:620},heroName:{fontFamily:Platform.select({ios:'Georgia',default:'serif'}),fontSize:34,fontWeight:'900',marginTop:5,textShadowColor:'rgba(0,0,0,.8)',textShadowOffset:{width:0,height:2},textShadowRadius:8},heroSub:{fontSize:11,fontWeight:'700',marginTop:6,textShadowColor:'rgba(0,0,0,.8)',textShadowOffset:{width:0,height:1},textShadowRadius:6},heroHud:{padding:16},levelRow:{flexDirection:'row',alignItems:'center',gap:12},levelOrb:{width:66,height:66,borderRadius:33,borderWidth:2,alignItems:'center',justifyContent:'center'},levelLabel:{fontSize:7,fontWeight:'900',letterSpacing:1},levelValue:{fontSize:28,fontWeight:'900'},className:{fontSize:18,fontWeight:'900'},xpCopy:{fontSize:8.5,marginTop:4,marginBottom:7},track:{height:7,borderRadius:99,overflow:'hidden'},fill:{height:'100%',borderRadius:99},titlePlate:{borderWidth:1,borderRadius:14,padding:12,marginTop:14},activeTitle:{fontSize:17,fontWeight:'900',marginTop:3},activeCopy:{fontSize:9,marginTop:3},summaryGrid:{gap:8},summaryWide:{flexDirection:'row'},summary:{flex:1,borderWidth:1,borderRadius:14,padding:12,alignItems:'center'},summaryValue:{fontSize:22,fontWeight:'900',marginTop:2},summaryLabel:{fontSize:7,fontWeight:'900',letterSpacing:.8,marginTop:2},sectionHead:{flexDirection:'row',alignItems:'flex-end',justifyContent:'space-between'},sectionTitle:{fontFamily:Platform.select({ios:'Georgia',default:'serif'}),fontSize:23,fontWeight:'800',marginTop:4},overall:{fontSize:7,fontWeight:'900',letterSpacing:.8},attrCard:{borderWidth:1,borderRadius:17,paddingHorizontal:14},attrRow:{flexDirection:'row',alignItems:'center',gap:11,paddingVertical:13},attrTop:{flexDirection:'row',justifyContent:'space-between',marginBottom:7},attrName:{fontSize:12,fontWeight:'900'},attrValue:{fontSize:12,fontWeight:'900'},featGrid:{gap:9},featWide:{flexDirection:'row'},feat:{flex:1,borderWidth:1,borderRadius:15,padding:14},featValue:{fontSize:24,fontWeight:'900',marginTop:4},featLabel:{fontSize:7,fontWeight:'900',letterSpacing:.8,marginTop:3},featDetail:{fontSize:8,fontWeight:'800',marginTop:8},badgeStrip:{borderWidth:1,borderRadius:16,padding:15,flexDirection:'row',alignItems:'center',gap:12},badgeTitle:{fontSize:17,fontWeight:'900',marginTop:3},badgeCopy:{fontSize:9.5,lineHeight:15,marginTop:3}});
