import { router,useLocalSearchParams } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import React,{useMemo,useState} from 'react';
import { ImageBackground,Platform,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,useWindowDimensions,View } from 'react-native';
import { ActionPressable,Entrance } from './Interaction';
import { HERO_ARCHETYPES,type HeroArchetype } from './heroEvolution';
import { ARC_GOALS,type TrainingArcGoal } from './trainingBlock';
import { DEFAULT_EQUIPMENT,EQUIPMENT_OPTIONS,type EquipmentId } from './trainingPreferences';
import { firstSessionForGoal,saveOnboardingProfile,type TrainingExperience } from './onboarding';
import { materialForArchetype,paletteForArchetype } from './designSystem';
import { useVitalTheme } from './ThemeProvider';
import BrandLoadingScreen from './BrandLoadingScreen';
import { IconArt,type VQIconName } from './IconArt';
import { heroArtFor,worldArtFor } from './vitalquestArt';
import { BRAND_LAUNCH_IMAGE } from './brandLaunchAsset';

type Step=0|1|2|3|4|5|6;
const EXPERIENCE:Array<{id:TrainingExperience;label:string;copy:string}>=[
  {id:'BEGINNER',label:'Building the base',copy:'New or returning after a long break.'},
  {id:'INTERMEDIATE',label:'Consistent trainer',copy:'Training regularly with established movement experience.'},
  {id:'ADVANCED',label:'Experienced',copy:'Comfortable managing load, volume and progression.'},
];
const EQUIPMENT_ICON:Record<EquipmentId,VQIconName>={barbell:'strength',dumbbells:'strength',bench:'strength',rack:'strength',cables:'strength',machines:'strength',pullup:'agility',cardio:'stamina',bodyweight:'streak'};
const EQUIPMENT_SHORT:Record<EquipmentId,string>={barbell:'Barbell',dumbbells:'Dumbbells',bench:'Bench',rack:'Rack',cables:'Cables',machines:'Machines',pullup:'Pull-Up Bar',cardio:'Cardio',bodyweight:'Bodyweight'};

export default function OnboardingV2(){
  const db=useSQLiteContext();const {theme}=useVitalTheme();const t=theme.tokens;const {width}=useWindowDimensions();const wide=width>=820;const compact=width<430;const {reset}=useLocalSearchParams<{reset?:string}>();
  const [step,setStep]=useState<Step>(reset?1:0);const [goal,setGoal]=useState<TrainingArcGoal>('HYBRID');const [archetype,setArchetype]=useState<HeroArchetype>('athlete');const [experience,setExperience]=useState<TrainingExperience>('INTERMEDIATE');const [weeklyDays,setWeeklyDays]=useState<3|4|5>(4);const [equipment,setEquipment]=useState<EquipmentId[]>(DEFAULT_EQUIPMENT);const [saving,setSaving]=useState(false);
  const palette=paletteForArchetype(archetype);const material=materialForArchetype(archetype);const goalInfo=ARC_GOALS.find(x=>x.id===goal)!;const session=useMemo(()=>firstSessionForGoal(goal,equipment),[goal,equipment]);
  const toggleEquipment=(id:EquipmentId)=>setEquipment(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id]);
  async function calibrate(){setSaving(true);const safeEquipment=equipment.length?equipment:['bodyweight'];await saveOnboardingProfile(db,{goal,archetype,experience,weeklyDays,equipment:safeEquipment});setEquipment(safeEquipment);setStep(6);setSaving(false)}
  if(saving)return <BrandLoadingScreen variant="calibrating" message="BUILDING YOUR FIRST ARC"/>;
  if(step===0)return <WelcomeScreen onStart={()=>setStep(1)} compact={compact}/>;
  const progress=step/6;
  return <SafeAreaView style={[styles.safe,{backgroundColor:'#05070A'}]}><View style={styles.world}><ImageBackground source={{uri:worldArtFor(archetype)}} resizeMode="cover" style={StyleSheet.absoluteFillObject} imageStyle={styles.bgImage}/><View style={styles.scrim}/><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.page}><View style={[styles.shell,wide&&styles.shellWide]}>
    <View style={styles.top}><View><Text style={[styles.wordmark,{color:t.text}]}>VITAL<Text style={{color:palette.highlight}}>QUEST</Text></Text><Text style={[styles.micro,{color:t.muted}]}>{reset?'RECALIBRATE BASELINE':'FIRST RUN CALIBRATION'}</Text></View><Text style={[styles.stepLabel,{color:palette.highlight}]}>0{step} / 06</Text></View>
    <View style={[styles.progress,{backgroundColor:'rgba(255,255,255,.10)'}]}><View style={[styles.progressFill,{width:`${progress*100}%`,backgroundColor:palette.primary}]}/></View>

    {step===1?<Entrance><View style={styles.stage}><Text style={[styles.eyebrow,{color:palette.highlight}]}>DEFINE THE ARC</Text><Text style={[styles.title,compact&&styles.titleCompact,{color:t.text}]}>What should your training change first?</Text><Text style={[styles.lede,{color:t.muted}]}>Choose the outcome that should lead your first four-week Arc. VitalQuest will adapt the plan as your real training data comes in.</Text><View style={[styles.goalGrid,wide&&styles.goalGridWide]}>{ARC_GOALS.map(item=>{const active=item.id===goal;return <Pressable key={item.id} onPress={()=>setGoal(item.id)} style={[styles.goalCard,{borderColor:active?material.edgeStrong:t.border,backgroundColor:active?material.elevatedSurface:'rgba(5,9,13,.76)'}]}><Text style={[styles.choiceState,{color:active?palette.highlight:t.muted}]}>{active?'SELECTED':'CHOOSE'}</Text><Text style={[styles.goalTitle,{color:t.text}]}>{item.label}</Text><Text style={[styles.choiceCopy,{color:t.muted}]}>{item.description}</Text></Pressable>})}</View></View></Entrance>:null}

    {step===2?<Entrance><View style={styles.stage}><Text style={[styles.eyebrow,{color:palette.highlight}]}>CHOOSE YOUR WORLD</Text><Text style={[styles.title,compact&&styles.titleCompact,{color:t.text}]}>Different paths. A stronger you.</Text><Text style={[styles.lede,{color:t.muted}]}>Your world changes the atmosphere, materials and evolution language — never your underlying training data.</Text><View style={[styles.worldGrid,wide&&styles.worldGridWide]}>{(Object.keys(HERO_ARCHETYPES) as HeroArchetype[]).map(id=>{const config=HERO_ARCHETYPES[id];const p=paletteForArchetype(id);const m=materialForArchetype(id);const active=id===archetype;return <Pressable key={id} onPress={()=>setArchetype(id)} style={[styles.worldCard,{borderColor:active?m.edgeStrong:'rgba(255,255,255,.16)'}]}><ImageBackground source={{uri:worldArtFor(id)}} resizeMode="cover" style={styles.worldArt} imageStyle={styles.worldArtImage}><View style={styles.worldShade}/><View style={styles.worldCopy}><Text style={[styles.choiceState,{color:active?p.highlight:'#D6D9DE'}]}>{active?'YOUR WORLD':'SELECT PATH'}</Text><Text style={styles.worldTitle}>{config.name.toUpperCase()}</Text><Text numberOfLines={2} style={styles.worldDescription}>{m.descriptor}</Text><Text style={[styles.worldArrow,{color:p.highlight}]}>›</Text></View></ImageBackground></Pressable>})}</View></View></Entrance>:null}

    {step===3?<Entrance><View style={styles.stage}><Text style={[styles.eyebrow,{color:palette.highlight}]}>YOUR ARCHETYPE</Text><Text style={[styles.title,compact&&styles.titleCompact,{color:t.text}]}>Meet the hero your work will build.</Text><Text style={[styles.lede,{color:t.muted}]}>This visual evolves with your progression. Your training — not taps — determines what changes.</Text><View style={[styles.archetypeHero,{borderColor:material.edgeStrong}]}><ImageBackground source={{uri:heroArtFor(archetype)}} resizeMode="cover" style={[styles.heroArt,wide&&styles.heroArtWide]} imageStyle={styles.heroArtImage}><View style={styles.heroShade}/><View style={styles.heroCopy}><Text style={[styles.heroKicker,{color:palette.highlight}]}>{material.motif}</Text><Text style={styles.heroName}>{HERO_ARCHETYPES[archetype].name.toUpperCase()}</Text><Text style={styles.heroVow}>{archetype==='mystic'?'Focus. Balance. Ascension.':archetype==='athlete'?'Discipline. Progress. Potential.':'Resilience. Strength. Legacy.'}</Text></View></ImageBackground></View><ActionPressable onPress={()=>setStep(4)} style={[styles.heroButton,{backgroundColor:palette.primary}]}><Text style={styles.primaryText}>SELECT THIS PATH</Text></ActionPressable></View></Entrance>:null}

    {step===4?<Entrance><View style={styles.stage}><Text style={[styles.eyebrow,{color:palette.highlight}]}>BUILD YOUR BASELINE</Text><Text style={[styles.title,compact&&styles.titleCompact,{color:t.text}]}>Set up training you can actually sustain.</Text><Text style={[styles.lede,{color:t.muted}]}>Tell VitalQuest where you are starting and what you can use. You can change all of this later.</Text><Section title="TRAINING EXPERIENCE"><View style={[styles.segment,wide&&styles.segmentWide]}>{EXPERIENCE.map(item=><Pressable key={item.id} onPress={()=>setExperience(item.id)} style={[styles.segmentItem,{borderColor:experience===item.id?material.edgeStrong:t.border,backgroundColor:experience===item.id?material.elevatedSurface:'rgba(5,9,13,.76)'}]}><Text style={[styles.segmentTitle,{color:experience===item.id?palette.highlight:t.text}]}>{item.label}</Text><Text style={[styles.segmentCopy,{color:t.muted}]}>{item.copy}</Text></Pressable>)}</View></Section><Section title="REALISTIC TRAINING DAYS"><View style={styles.days}>{([3,4,5] as const).map(day=><Pressable key={day} onPress={()=>setWeeklyDays(day)} style={[styles.day,{borderColor:weeklyDays===day?material.edgeStrong:t.border,backgroundColor:weeklyDays===day?material.elevatedSurface:'rgba(5,9,13,.76)'}]}><Text style={[styles.dayValue,{color:t.text}]}>{day}</Text><Text style={[styles.micro,{color:weeklyDays===day?palette.highlight:t.muted}]}>DAYS / WEEK</Text></Pressable>)}</View></Section><Section title="SELECT YOUR EQUIPMENT"><Text style={[styles.sectionHelp,{color:t.muted}]}>Choose everything you have access to.</Text><View style={[styles.equipmentGrid,wide&&styles.equipmentGridWide]}>{EQUIPMENT_OPTIONS.map(item=>{const active=equipment.includes(item.id);return <Pressable key={item.id} onPress={()=>toggleEquipment(item.id)} style={[styles.equipmentTile,{borderColor:active?material.edgeStrong:t.border,backgroundColor:active?material.elevatedSurface:'rgba(7,13,19,.86)'}]}><View style={[styles.equipmentIcon,{borderColor:active?material.edgeStrong:'rgba(255,255,255,.12)',backgroundColor:material.railSurface}]}><IconArt name={EQUIPMENT_ICON[item.id]} size={30} tint={active?palette.highlight:t.text}/></View><Text numberOfLines={2} style={[styles.equipmentLabel,{color:active?palette.highlight:t.text}]}>{EQUIPMENT_SHORT[item.id]}</Text></Pressable>})}</View></Section></View></Entrance>:null}

    {step===5?<Entrance><View style={styles.stage}><Text style={[styles.eyebrow,{color:palette.highlight}]}>ARC PREVIEW</Text><Text style={[styles.title,compact&&styles.titleCompact,{color:t.text}]}>Your first four weeks have a direction.</Text><Text style={[styles.lede,{color:t.muted}]}>VitalQuest starts conservatively, watches the evidence you create, then adapts load and recommendations as your history becomes trustworthy.</Text><View style={[styles.arcCard,{borderColor:material.edgeStrong,backgroundColor:material.commandSurface}]}><ImageBackground source={{uri:worldArtFor(archetype)}} resizeMode="cover" style={styles.arcBackdrop} imageStyle={styles.arcBackdropImage}><View style={styles.arcShade}/><View style={styles.arcContent}><Text style={[styles.eyebrow,{color:palette.highlight}]}>WEEK 1 · FOUNDATION</Text><Text style={styles.arcTitle}>{goalInfo.label}</Text><Text style={styles.arcCopy}>{goalInfo.description}</Text><View style={styles.arcStats}><Mini value={`${weeklyDays}×`} label="WEEKLY AVAILABILITY"/><Mini value={experience.replace('_',' ')} label="BASELINE"/><Mini value={`${equipment.length}`} label="EQUIPMENT CATEGORIES"/></View><View style={[styles.firstSession,{borderColor:material.edge,backgroundColor:'rgba(4,8,12,.82)'}]}><IconArt name={session.templateId==='run'?'agility':session.templateId==='recovery'?'streak':'strength'} size={38} tint={palette.highlight}/><View style={{flex:1}}><Text style={[styles.micro,{color:palette.highlight}]}>FIRST RECOMMENDED SESSION</Text><Text style={styles.firstTitle}>{session.name}</Text><Text style={styles.firstCopy}>{session.reason}</Text></View></View></View></ImageBackground></View></View></Entrance>:null}

    {step===6?<Entrance><View style={[styles.ready,{borderColor:material.edgeStrong,backgroundColor:'rgba(5,9,13,.80)'}]}><ImageBackground source={{uri:heroArtFor(archetype)}} resizeMode="cover" style={styles.readyArt} imageStyle={styles.readyArtImage}><View style={styles.readyShade}/><View style={styles.readyCopyWrap}><Text style={[styles.eyebrow,{color:palette.highlight}]}>CALIBRATION COMPLETE</Text><Text style={styles.readyTitle}>Your Arc is live.</Text><Text style={styles.readyCopy}>Every trusted workout gives VitalQuest better evidence for what to recommend next.</Text><View style={[styles.reveal,{borderColor:material.edge,backgroundColor:'rgba(3,7,10,.82)'}]}><Text style={[styles.micro,{color:palette.highlight}]}>START HERE</Text><Text style={styles.revealTitle}>{session.name}</Text><Text style={styles.revealCopy}>{session.reason}</Text></View><ActionPressable onPress={()=>router.replace({pathname:'/workout',params:{templateId:session.templateId}})} style={[styles.primary,{backgroundColor:palette.primary}]}><Text style={styles.primaryText}>START FIRST SESSION</Text></ActionPressable><ActionPressable onPress={()=>router.replace('/(tabs)')} style={[styles.secondary,{borderColor:material.edge}]}><Text style={styles.secondaryText}>OPEN TODAY INSTEAD</Text></ActionPressable></View></ImageBackground></View></Entrance>:null}

    {step>0&&step<6&&step!==3?<View style={styles.footer}><ActionPressable onPress={()=>setStep(Math.max(reset?1:0,step-1) as Step)} style={styles.backButton}><Text style={[styles.backText,{color:t.muted}]}>‹ BACK</Text></ActionPressable>{step<5?<ActionPressable onPress={()=>setStep((step+1) as Step)} style={[styles.primary,styles.next,{backgroundColor:palette.primary}]}><Text style={styles.primaryText}>CONTINUE</Text></ActionPressable>:<ActionPressable onPress={calibrate} style={[styles.primary,styles.next,{backgroundColor:palette.primary}]}><Text style={styles.primaryText}>{reset?'RECALIBRATE ARC':'BUILD MY ARC'}</Text></ActionPressable>}</View>:null}
  </View></ScrollView></View></SafeAreaView>
}

function WelcomeScreen({onStart,compact}:{onStart:()=>void;compact:boolean}){
  return <SafeAreaView style={styles.welcomeSafe}><ImageBackground source={{uri:BRAND_LAUNCH_IMAGE}} resizeMode="cover" style={styles.welcomeArt} imageStyle={styles.welcomeImage}><View style={styles.welcomeShade}/><View style={styles.welcomeChrome}><Text style={styles.welcomeBrand}>VITALQUEST</Text><View style={styles.welcomeSpacer}/><View style={styles.welcomeCopy}><Text style={[styles.welcomeTitle,compact&&styles.welcomeTitleCompact]}>Welcome to{`\n`}VitalQuest</Text><Text style={styles.welcomeSub}>Train with purpose.{`\n`}Build a stronger you.</Text><ActionPressable onPress={onStart} style={styles.welcomeButton}><Text style={styles.welcomeButtonText}>GET STARTED</Text></ActionPressable></View></View></ImageBackground></SafeAreaView>
}
function Section({title,children}:{title:string;children:React.ReactNode}){const {theme}=useVitalTheme();return <View style={styles.section}><Text style={[styles.sectionLabel,{color:theme.tokens.muted}]}>{title}</Text>{children}</View>}
function Mini({value,label}:{value:string;label:string}){return <View style={styles.mini}><Text style={styles.miniValue}>{value}</Text><Text style={styles.miniLabel}>{label}</Text></View>}

const styles=StyleSheet.create({
  safe:{flex:1},world:{flex:1,backgroundColor:'#05070A'},bgImage:{opacity:.72},scrim:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(2,6,10,.48)'},page:{padding:18,paddingBottom:46,minHeight:'100%'},shell:{width:'100%',maxWidth:1120,alignSelf:'center',gap:18},shellWide:{paddingHorizontal:18},
  top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},wordmark:{fontSize:24,fontWeight:'900',letterSpacing:-1},micro:{fontSize:7,fontWeight:'900',letterSpacing:.9},stepLabel:{fontSize:8,fontWeight:'900',letterSpacing:1.2},progress:{height:3,borderRadius:99,overflow:'hidden'},progressFill:{height:'100%',borderRadius:99},stage:{gap:13,paddingTop:14},eyebrow:{fontSize:7.5,fontWeight:'900',letterSpacing:1.5},title:{fontFamily:Platform.select({ios:'Georgia',default:'serif'}),fontSize:40,lineHeight:45,fontWeight:'900',maxWidth:760,color:'#F7F4EC'},titleCompact:{fontSize:33,lineHeight:38},lede:{fontSize:10.5,lineHeight:17,maxWidth:700},choiceState:{fontSize:6.5,fontWeight:'900',letterSpacing:1.1},choiceCopy:{fontSize:9.5,lineHeight:15,marginTop:5},
  goalGrid:{gap:10,marginTop:6},goalGridWide:{flexDirection:'row',flexWrap:'wrap'},goalCard:{borderWidth:1,borderRadius:18,padding:16,minHeight:130,flexGrow:1,flexBasis:300},goalTitle:{fontSize:19,fontWeight:'900',marginTop:13},
  worldGrid:{gap:12,marginTop:8},worldGridWide:{flexDirection:'row'},worldCard:{borderWidth:1,borderRadius:18,overflow:'hidden',flex:1,minHeight:210},worldArt:{minHeight:220,justifyContent:'flex-end'},worldArtImage:{borderRadius:17},worldShade:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(2,5,8,.30)'},worldCopy:{padding:16,paddingTop:54,backgroundColor:'rgba(2,5,8,.40)'},worldTitle:{fontFamily:Platform.select({ios:'Georgia',default:'serif'}),fontSize:25,fontWeight:'900',color:'#FFF',marginTop:5},worldDescription:{fontSize:8.5,lineHeight:13,color:'#D0D4D8',marginTop:4,maxWidth:300},worldArrow:{position:'absolute',right:16,bottom:17,fontSize:28,fontWeight:'700'},
  archetypeHero:{borderWidth:1,borderRadius:24,overflow:'hidden',marginTop:6},heroArt:{height:500,justifyContent:'flex-end'},heroArtWide:{height:560},heroArtImage:{borderRadius:23},heroShade:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(3,6,8,.14)'},heroCopy:{padding:22,paddingTop:100,backgroundColor:'rgba(2,5,8,.32)'},heroKicker:{fontSize:7,fontWeight:'900',letterSpacing:1.5},heroName:{fontFamily:Platform.select({ios:'Georgia',default:'serif'}),fontSize:34,fontWeight:'900',color:'#FFF',marginTop:6},heroVow:{fontSize:11,color:'#F3EEE4',marginTop:5},heroButton:{minHeight:56,borderRadius:11,alignItems:'center',justifyContent:'center'},
  section:{gap:8,marginTop:8},sectionLabel:{fontSize:7,fontWeight:'900',letterSpacing:1.2},sectionHelp:{fontSize:8.5,marginTop:-2},segment:{gap:8},segmentWide:{flexDirection:'row'},segmentItem:{borderWidth:1,borderRadius:14,padding:13,flex:1},segmentTitle:{fontSize:13,fontWeight:'900'},segmentCopy:{fontSize:8.5,lineHeight:13,marginTop:3},days:{flexDirection:'row',gap:8},day:{flex:1,borderWidth:1,borderRadius:14,padding:12,alignItems:'center'},dayValue:{fontSize:24,fontWeight:'900'},equipmentGrid:{flexDirection:'row',flexWrap:'wrap',gap:9},equipmentGridWide:{maxWidth:720},equipmentTile:{width:'31.5%',minHeight:104,borderWidth:1,borderRadius:14,padding:9,alignItems:'center',justifyContent:'center'},equipmentIcon:{width:48,height:48,borderRadius:13,borderWidth:1,alignItems:'center',justifyContent:'center'},equipmentLabel:{fontSize:8,fontWeight:'900',textAlign:'center',marginTop:7,lineHeight:11},
  arcCard:{borderWidth:1,borderRadius:24,overflow:'hidden',marginTop:6},arcBackdrop:{minHeight:390,justifyContent:'flex-end'},arcBackdropImage:{borderRadius:23},arcShade:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(2,5,8,.42)'},arcContent:{padding:20,paddingTop:80},arcTitle:{fontFamily:Platform.select({ios:'Georgia',default:'serif'}),fontSize:29,fontWeight:'900',color:'#FFF',marginTop:5},arcCopy:{fontSize:10,lineHeight:16,color:'#D6D9DE',marginTop:5,maxWidth:650},arcStats:{flexDirection:'row',gap:8,marginTop:16,flexWrap:'wrap'},mini:{minWidth:125,flex:1,borderWidth:1,borderColor:'rgba(255,255,255,.14)',borderRadius:12,padding:11,backgroundColor:'rgba(3,7,10,.58)'},miniValue:{fontSize:16,fontWeight:'900',color:'#FFF'},miniLabel:{fontSize:6.5,fontWeight:'900',letterSpacing:.7,color:'#B5BBC2',marginTop:3},firstSession:{borderWidth:1,borderRadius:14,padding:13,flexDirection:'row',alignItems:'center',gap:12,marginTop:14},firstTitle:{fontSize:16,fontWeight:'900',color:'#FFF',marginTop:3},firstCopy:{fontSize:8.5,lineHeight:13,color:'#B9C0C7',marginTop:3},
  ready:{borderWidth:1,borderRadius:25,overflow:'hidden'},readyArt:{minHeight:620,justifyContent:'flex-end'},readyArtImage:{borderRadius:24},readyShade:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(2,5,8,.28)'},readyCopyWrap:{padding:22,paddingTop:120,backgroundColor:'rgba(2,5,8,.42)'},readyTitle:{fontFamily:Platform.select({ios:'Georgia',default:'serif'}),fontSize:40,fontWeight:'900',color:'#FFF',marginTop:6},readyCopy:{fontSize:10,lineHeight:16,color:'#D3D7DC',marginTop:6,maxWidth:620},reveal:{borderWidth:1,borderRadius:14,padding:14,marginTop:17},revealTitle:{fontSize:18,fontWeight:'900',color:'#FFF',marginTop:4},revealCopy:{fontSize:9,lineHeight:14,color:'#BCC2C9',marginTop:4},
  footer:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:14,marginTop:5},backButton:{minHeight:48,justifyContent:'center',paddingHorizontal:4},backText:{fontSize:8,fontWeight:'900',letterSpacing:.8},primary:{minHeight:54,borderRadius:10,alignItems:'center',justifyContent:'center',paddingHorizontal:18},next:{minWidth:190},primaryText:{fontSize:8,fontWeight:'900',letterSpacing:1,color:'#F7F8FA'},secondary:{minHeight:52,borderRadius:10,borderWidth:1,alignItems:'center',justifyContent:'center',marginTop:9},secondaryText:{fontSize:8,fontWeight:'900',letterSpacing:.9,color:'#FFF'},
  welcomeSafe:{flex:1,backgroundColor:'#04101A'},welcomeArt:{flex:1,minHeight:'100%'},welcomeImage:{opacity:1},welcomeShade:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(2,7,12,.16)'},welcomeChrome:{flex:1,padding:24,alignItems:'center'},welcomeBrand:{fontFamily:Platform.select({ios:'Georgia',default:'serif'}),fontSize:18,letterSpacing:4,color:'#F5F1E8',marginTop:6},welcomeSpacer:{flex:1},welcomeCopy:{width:'100%',maxWidth:520,alignItems:'center',paddingBottom:28},welcomeTitle:{fontFamily:Platform.select({ios:'Georgia',default:'serif'}),fontSize:48,lineHeight:51,fontWeight:'900',textAlign:'center',color:'#FFF'},welcomeTitleCompact:{fontSize:40,lineHeight:43},welcomeSub:{fontSize:13,lineHeight:20,textAlign:'center',color:'#F0EEE8',marginTop:14},welcomeButton:{width:'100%',minHeight:58,borderRadius:12,backgroundColor:'#E9B85E',alignItems:'center',justifyContent:'center',marginTop:22,borderWidth:1,borderColor:'#F6D28C'},welcomeButtonText:{fontSize:9,fontWeight:'900',letterSpacing:1,color:'#171008'},
});