import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { useVitalTheme } from './ThemeProvider';
import type { ProgressionRecap } from './progressionRecap';

export default function ProgressionRecapCard({recap}:{recap:ProgressionRecap}){
  const {theme}=useVitalTheme();const t=theme.tokens;
  return <View style={[styles.card,{borderColor:t.border,backgroundColor:t.surface}]}>
    <View style={styles.head}><View><Text style={[styles.eyebrow,{color:t.accent}]}>PROGRESSION UPDATE</Text><Text style={[styles.title,{color:t.text}]}>{recap.leveledUp?`Level ${recap.levelAfter} reached`:`Level ${recap.levelAfter} progress`}</Text></View><View style={[styles.levelBadge,{borderColor:recap.leveledUp?t.accent:t.border,backgroundColor:t.heroSurface}]}><Text style={[styles.levelSmall,{color:t.muted}]}>LEVEL</Text><Text style={[styles.levelBig,{color:t.text}]}>{recap.levelAfter}</Text></View></View>
    {recap.leveledUp?<Text style={[styles.levelUp,{color:t.accent}]}>LEVEL UP · +{recap.levelsGained}</Text>:null}
    <View style={styles.row}><Text style={[styles.meta,{color:t.muted}]}>{recap.levelCurrentXP.toLocaleString()} / {recap.levelNeededXP.toLocaleString()} XP</Text><Text style={[styles.metaStrong,{color:t.text}]}>{recap.xpToNext.toLocaleString()} XP TO NEXT</Text></View>
    <View style={[styles.track,{backgroundColor:t.surfaceElevated}]}><View style={[styles.fill,{width:`${Math.max(0,Math.min(100,recap.levelRatio*100))}%`,backgroundColor:t.accent}]}/></View>
    {recap.attributes.length?<View style={styles.section}><Text style={[styles.sectionLabel,{color:t.muted}]}>ATTRIBUTES GAINED</Text><View style={styles.chips}>{recap.attributes.map(item=><View key={item.label} style={[styles.chip,{borderColor:t.border,backgroundColor:t.heroSurface}]}><Text style={[styles.chipLabel,{color:t.text}]}>{item.label.toUpperCase()}</Text><Text style={[styles.chipValue,{color:t.accent}]}>+{item.amount}</Text></View>)}</View></View>:null}
    <View style={styles.section}><Text style={[styles.sectionLabel,{color:t.muted}]}>QUEST PROGRESS</Text>{recap.progressSignals.map(signal=><Text key={signal} style={[styles.signal,{color:t.text}]}>{signal}</Text>)}</View>
    {recap.unlocksEarned.length?<View style={[styles.unlockBox,{borderColor:t.accentSoft,backgroundColor:t.heroSurface}]}><Text style={[styles.sectionLabel,{color:t.accent}]}>NEW REWARD UNLOCKED</Text>{recap.unlocksEarned.map(item=><Text key={item} style={[styles.unlockText,{color:t.text}]}>{item}</Text>)}</View>:null}
    <View style={[styles.next,{borderColor:t.accentSoft,backgroundColor:t.heroSurface}]}><Text style={[styles.sectionLabel,{color:t.accent}]}>NEXT MILESTONE</Text><Text style={[styles.nextText,{color:t.text}]}>{recap.nextMilestone}</Text></View>
  </View>
}

const styles=StyleSheet.create({card:{width:'100%',borderWidth:1,borderRadius:18,padding:16,gap:12},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12},eyebrow:{fontSize:7,fontWeight:'900',letterSpacing:1.2},title:{fontSize:21,fontWeight:'900',marginTop:4},levelBadge:{width:64,height:64,borderRadius:32,borderWidth:1,alignItems:'center',justifyContent:'center'},levelSmall:{fontSize:6,fontWeight:'900',letterSpacing:.8},levelBig:{fontSize:23,fontWeight:'900'},levelUp:{fontSize:9,fontWeight:'900',letterSpacing:1.1},row:{flexDirection:'row',justifyContent:'space-between',gap:12},meta:{fontSize:8,fontWeight:'800'},metaStrong:{fontSize:8,fontWeight:'900'},track:{height:8,borderRadius:99,overflow:'hidden'},fill:{height:'100%',borderRadius:99},section:{gap:7},sectionLabel:{fontSize:6.5,fontWeight:'900',letterSpacing:1},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{borderWidth:1,borderRadius:10,paddingHorizontal:10,paddingVertical:8,minWidth:100},chipLabel:{fontSize:7,fontWeight:'900',letterSpacing:.7},chipValue:{fontSize:16,fontWeight:'900',marginTop:2},signal:{fontSize:10,fontWeight:'800'},unlockBox:{borderWidth:1,borderRadius:12,padding:12,gap:5},unlockText:{fontSize:15,fontWeight:'900'},next:{borderWidth:1,borderRadius:12,padding:12},nextText:{fontSize:13,fontWeight:'900',marginTop:4}});
