import React,{useEffect,useRef} from 'react';
import { Animated,StyleSheet,Text,View } from 'react-native';
import { Entrance } from './Interaction';
import { useVitalTheme } from './ThemeProvider';
import { useHeroArchetype } from './useHeroArchetype';
import { materialForArchetype,paletteForArchetype } from './designSystem';
import type { ProgressionRecap } from './progressionRecap';

export default function ProgressionRecapCard({recap}:{recap:ProgressionRecap}){
  const {theme}=useVitalTheme();const t=theme.tokens;const {archetype}=useHeroArchetype();const palette=paletteForArchetype(archetype);const material=materialForArchetype(archetype);const celebration=recap.leveledUp||recap.unlocksEarned.length>0;
  const glow=useRef(new Animated.Value(0)).current;const badgeScale=useRef(new Animated.Value(.9)).current;
  useEffect(()=>{
    if(!celebration){badgeScale.setValue(1);return}
    Animated.parallel([
      Animated.sequence([Animated.timing(glow,{toValue:1,duration:420,useNativeDriver:true}),Animated.timing(glow,{toValue:.34,duration:700,useNativeDriver:true})]),
      Animated.spring(badgeScale,{toValue:1,useNativeDriver:true,speed:14,bounciness:5})
    ]).start();
  },[badgeScale,celebration,glow]);
  const glowOpacity=glow.interpolate({inputRange:[0,1],outputRange:[0,.72]});
  return <Entrance distance={14}><View style={[styles.card,{borderColor:celebration?material.edgeStrong:material.edge,backgroundColor:celebration?material.commandSurface:t.surface}]}>
    {celebration?<Animated.View pointerEvents="none" style={[styles.ceremonyGlow,{backgroundColor:material.glow,opacity:glowOpacity}]}/>:null}
    <View style={styles.head}><View style={{flex:1}}><Text style={[styles.eyebrow,{color:palette.highlight}]}>{recap.leveledUp?'LEVEL UP':recap.unlocksEarned.length?'REWARD EARNED':'PROGRESSION UPDATE'}</Text><Text style={[styles.title,{color:t.text}]}>{recap.leveledUp?`Level ${recap.levelAfter} reached`:`Level ${recap.levelAfter} progress`}</Text>{celebration?<Text style={[styles.celebrationCopy,{color:t.muted}]}>{recap.leveledUp?'Your completed work pushed progression into a new level.':'This session crossed a configured reward threshold.'}</Text>:null}</View><Animated.View style={[styles.levelBadge,{borderColor:celebration?material.edgeStrong:material.edge,backgroundColor:material.elevatedSurface,transform:[{scale:badgeScale}]}]}><Text style={[styles.levelSmall,{color:t.muted}]}>LEVEL</Text><Text style={[styles.levelBig,{color:t.text}]}>{recap.levelAfter}</Text></Animated.View></View>
    {recap.leveledUp?<Entrance delay={70} distance={6}><View style={[styles.levelUpBox,{borderColor:material.edgeStrong,backgroundColor:material.glow}]}><Text style={[styles.levelUp,{color:palette.highlight}]}>LEVEL {recap.levelBefore} → {recap.levelAfter}</Text><Text style={[styles.levelUpSub,{color:t.text}]}>{recap.levelsGained===1?'New level banked':`${recap.levelsGained} levels gained`}</Text><Text style={[styles.ceremonyMeta,{color:material.metal}]}>{material.motif} PROGRESSION</Text></View></Entrance>:null}
    <Entrance delay={95} distance={6}><View><View style={styles.row}><Text style={[styles.meta,{color:t.muted}]}>{recap.levelCurrentXP.toLocaleString()} / {recap.levelNeededXP.toLocaleString()} XP</Text><Text style={[styles.metaStrong,{color:t.text}]}>{recap.xpToNext.toLocaleString()} XP TO NEXT</Text></View><View style={[styles.track,{backgroundColor:t.surfaceElevated}]}><View style={[styles.fill,{width:`${Math.max(0,Math.min(100,recap.levelRatio*100))}%`,backgroundColor:palette.primary}]}/></View></View></Entrance>
    {recap.attributes.length?<Entrance delay={125} distance={6}><View style={styles.section}><Text style={[styles.sectionLabel,{color:t.muted}]}>ATTRIBUTES GAINED</Text><View style={styles.chips}>{recap.attributes.map(item=><View key={item.label} style={[styles.chip,{borderColor:material.edge,backgroundColor:material.railSurface}]}><Text style={[styles.chipLabel,{color:t.text}]}>{item.label.toUpperCase()}</Text><Text style={[styles.chipValue,{color:palette.highlight}]}>+{item.amount}</Text></View>)}</View></View></Entrance>:null}
    <Entrance delay={155} distance={6}><View style={styles.section}><Text style={[styles.sectionLabel,{color:t.muted}]}>GOAL PROGRESS</Text>{recap.progressSignals.map(signal=><Text key={signal} style={[styles.signal,{color:t.text}]}>{signal}</Text>)}</View></Entrance>
    {recap.unlocksEarned.length?<Entrance delay={190} distance={8}><View style={[styles.unlockBox,{borderColor:material.edgeStrong,backgroundColor:material.elevatedSurface}]}><Text style={[styles.unlockKicker,{color:palette.highlight}]}>NEW REWARD UNLOCKED</Text>{recap.unlocksEarned.map(item=><Text key={item} style={[styles.unlockText,{color:t.text}]}>{item}</Text>)}<View style={[styles.revealLine,{backgroundColor:palette.primary}]}/><Text style={[styles.unlockHint,{color:t.muted}]}>Available now in Rewards.</Text></View></Entrance>:null}
    <Entrance delay={220} distance={6}><View style={[styles.next,{borderColor:material.edge,backgroundColor:material.railSurface}]}><Text style={[styles.sectionLabel,{color:palette.highlight}]}>NEXT MILESTONE</Text><Text style={[styles.nextText,{color:t.text}]}>{recap.nextMilestone}</Text></View></Entrance>
  </View></Entrance>
}

const styles=StyleSheet.create({card:{width:'100%',borderWidth:1,borderRadius:22,padding:16,gap:12,overflow:'hidden',position:'relative'},ceremonyGlow:{position:'absolute',width:250,height:250,borderRadius:125,right:-85,top:-120},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12},eyebrow:{fontSize:7,fontWeight:'900',letterSpacing:1.25},title:{fontSize:24,fontWeight:'900',marginTop:4},celebrationCopy:{fontSize:9,lineHeight:14,marginTop:4,maxWidth:520},levelBadge:{width:72,height:72,borderRadius:36,borderWidth:1.5,alignItems:'center',justifyContent:'center'},levelSmall:{fontSize:6,fontWeight:'900',letterSpacing:.8},levelBig:{fontSize:26,fontWeight:'900'},levelUpBox:{borderWidth:1,borderRadius:14,padding:13},levelUp:{fontSize:8,fontWeight:'900',letterSpacing:1},levelUpSub:{fontSize:16,fontWeight:'900',marginTop:3},ceremonyMeta:{fontSize:6,fontWeight:'900',letterSpacing:1.1,marginTop:5},row:{flexDirection:'row',justifyContent:'space-between',gap:12,flexWrap:'wrap'},meta:{fontSize:8,fontWeight:'800'},metaStrong:{fontSize:8,fontWeight:'900'},track:{height:8,borderRadius:99,overflow:'hidden',marginTop:7},fill:{height:'100%',borderRadius:99},section:{gap:7},sectionLabel:{fontSize:6.5,fontWeight:'900',letterSpacing:1},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{borderWidth:1,borderRadius:10,paddingHorizontal:10,paddingVertical:8,minWidth:100},chipLabel:{fontSize:7,fontWeight:'900',letterSpacing:.7},chipValue:{fontSize:16,fontWeight:'900',marginTop:2},signal:{fontSize:10,fontWeight:'800'},unlockBox:{borderWidth:1.5,borderRadius:15,padding:14,gap:5},unlockKicker:{fontSize:7,fontWeight:'900',letterSpacing:1.05},unlockText:{fontSize:19,fontWeight:'900'},revealLine:{height:2,width:56,borderRadius:99,marginTop:4},unlockHint:{fontSize:8.5,fontWeight:'800',marginTop:2},next:{borderWidth:1,borderRadius:12,padding:12},nextText:{fontSize:13,fontWeight:'900',marginTop:4}});
