import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Entrance } from './Interaction';
import { useVitalTheme } from './ThemeProvider';
import type { ProgressionRecap } from './progressionRecap';

export default function ProgressionRecapCard({recap}:{recap:ProgressionRecap}){
  const {theme}=useVitalTheme();const t=theme.tokens;const celebration=recap.leveledUp||recap.unlocksEarned.length>0;
  return <Entrance distance={14}><View style={[styles.card,{borderColor:celebration?t.accentSoft:t.border,backgroundColor:t.surface}]}>
    <View style={styles.head}><View style={{flex:1}}><Text style={[styles.eyebrow,{color:t.accent}]}>{recap.leveledUp?'LEVEL UP':recap.unlocksEarned.length?'REWARD EARNED':'PROGRESSION UPDATE'}</Text><Text style={[styles.title,{color:t.text}]}>{recap.leveledUp?`Level ${recap.levelAfter} reached`:`Level ${recap.levelAfter} progress`}</Text>{celebration?<Text style={[styles.celebrationCopy,{color:t.muted}]}>{recap.leveledUp?'Your completed work pushed progression into a new level.':'This session crossed a configured reward threshold.'}</Text>:null}</View><View style={[styles.levelBadge,{borderColor:recap.leveledUp?t.accent:t.border,backgroundColor:t.heroSurface}]}><Text style={[styles.levelSmall,{color:t.muted}]}>LEVEL</Text><Text style={[styles.levelBig,{color:t.text}]}>{recap.levelAfter}</Text></View></View>
    {recap.leveledUp?<Entrance delay={70} distance={6}><View style={[styles.levelUpBox,{borderColor:t.accentSoft,backgroundColor:t.heroSurface}]}><Text style={[styles.levelUp,{color:t.accent}]}>LEVEL {recap.levelBefore} → {recap.levelAfter}</Text><Text style={[styles.levelUpSub,{color:t.text}]}>{recap.levelsGained===1?'New level banked':`${recap.levelsGained} levels gained`}</Text></View></Entrance>:null}
    <Entrance delay={95} distance={6}><View><View style={styles.row}><Text style={[styles.meta,{color:t.muted}]}>{recap.levelCurrentXP.toLocaleString()} / {recap.levelNeededXP.toLocaleString()} XP</Text><Text style={[styles.metaStrong,{color:t.text}]}>{recap.xpToNext.toLocaleString()} XP TO NEXT</Text></View><View style={[styles.track,{backgroundColor:t.surfaceElevated}]}><View style={[styles.fill,{width:`${Math.max(0,Math.min(100,recap.levelRatio*100))}%`,backgroundColor:t.accent}]}/></View></View></Entrance>
    {recap.attributes.length?<Entrance delay={125} distance={6}><View style={styles.section}><Text style={[styles.sectionLabel,{color:t.muted}]}>ATTRIBUTES GAINED</Text><View style={styles.chips}>{recap.attributes.map(item=><View key={item.label} style={[styles.chip,{borderColor:t.border,backgroundColor:t.heroSurface}]}><Text style={[styles.chipLabel,{color:t.text}]}>{item.label.toUpperCase()}</Text><Text style={[styles.chipValue,{color:t.accent}]}>+{item.amount}</Text></View>)}</View></View></Entrance>:null}
    <Entrance delay={155} distance={6}><View style={styles.section}><Text style={[styles.sectionLabel,{color:t.muted}]}>GOAL PROGRESS</Text>{recap.progressSignals.map(signal=><Text key={signal} style={[styles.signal,{color:t.text}]}>{signal}</Text>)}</View></Entrance>
    {recap.unlocksEarned.length?<Entrance delay={190} distance={8}><View style={[styles.unlockBox,{borderColor:t.accent,backgroundColor:t.heroSurface}]}><Text style={[styles.unlockKicker,{color:t.accent}]}>NEW REWARD UNLOCKED</Text>{recap.unlocksEarned.map(item=><Text key={item} style={[styles.unlockText,{color:t.text}]}>{item}</Text>)}<Text style={[styles.unlockHint,{color:t.muted}]}>Available now in Rewards.</Text></View></Entrance>:null}
    <Entrance delay={220} distance={6}><View style={[styles.next,{borderColor:t.accentSoft,backgroundColor:t.heroSurface}]}><Text style={[styles.sectionLabel,{color:t.accent}]}>NEXT MILESTONE</Text><Text style={[styles.nextText,{color:t.text}]}>{recap.nextMilestone}</Text></View></Entrance>
  </View></Entrance>
}

const styles=StyleSheet.create({card:{width:'100%',borderWidth:1,borderRadius:20,padding:16,gap:12},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12},eyebrow:{fontSize:7,fontWeight:'900',letterSpacing:1.2},title:{fontSize:23,fontWeight:'900',marginTop:4},celebrationCopy:{fontSize:9,lineHeight:14,marginTop:4,maxWidth:520},levelBadge:{width:68,height:68,borderRadius:34,borderWidth:1.5,alignItems:'center',justifyContent:'center'},levelSmall:{fontSize:6,fontWeight:'900',letterSpacing:.8},levelBig:{fontSize:25,fontWeight:'900'},levelUpBox:{borderWidth:1,borderRadius:13,padding:12},levelUp:{fontSize:8,fontWeight:'900',letterSpacing:1},levelUpSub:{fontSize:15,fontWeight:'900',marginTop:3},row:{flexDirection:'row',justifyContent:'space-between',gap:12},meta:{fontSize:8,fontWeight:'800'},metaStrong:{fontSize:8,fontWeight:'900'},track:{height:8,borderRadius:99,overflow:'hidden',marginTop:7},fill:{height:'100%',borderRadius:99},section:{gap:7},sectionLabel:{fontSize:6.5,fontWeight:'900',letterSpacing:1},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{borderWidth:1,borderRadius:10,paddingHorizontal:10,paddingVertical:8,minWidth:100},chipLabel:{fontSize:7,fontWeight:'900',letterSpacing:.7},chipValue:{fontSize:16,fontWeight:'900',marginTop:2},signal:{fontSize:10,fontWeight:'800'},unlockBox:{borderWidth:1.5,borderRadius:14,padding:14,gap:5},unlockKicker:{fontSize:7,fontWeight:'900',letterSpacing:1.05},unlockText:{fontSize:18,fontWeight:'900'},unlockHint:{fontSize:8.5,fontWeight:'800',marginTop:2},next:{borderWidth:1,borderRadius:12,padding:12},nextText:{fontSize:13,fontWeight:'900',marginTop:4}});