import React,{useMemo,useState} from 'react';
import { ImageBackground, Platform, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, useWindowDimensions, View } from 'react-native';
import { IconArt,VQIconName } from './IconArt';
import { useProgressionSnapshot } from './useProgression';
import { useVitalTheme } from './ThemeProvider';

type QuestTab='Active'|'Completed'|'Guild';type WorldId='mythicForge'|'celestialPulse'|'titanCore';
const worldArt:Record<WorldId,string>={mythicForge:'/vitalquest-app/art/premium/mythic-quest.jpg',celestialPulse:'/vitalquest-app/art/today-celestial-premium.webp',titanCore:'/vitalquest-app/art/today-titan-premium.webp'};

export default function QuestBoardV2(){
  const {themeId,theme}=useVitalTheme();const {snapshot}=useProgressionSnapshot();const t=theme.tokens;const {width}=useWindowDimensions();const wide=width>=760;const [tab,setTab]=useState<QuestTab>('Active');const art=worldArt[themeId as WorldId]??worldArt.mythicForge;
  const activeQuests=useMemo(()=>[
    {title:'Iron Week',type:'WEEKLY TRIAL',description:`Complete ${snapshot.quests.ironWeek.target} resistance workouts this week.`,progress:snapshot.quests.ironWeek.progress,target:snapshot.quests.ironWeek.target,reward:'WEEKLY CLEAR',icon:'strength' as VQIconName,complete:snapshot.quests.ironWeek.complete},
    {title:'Five-Ton Trial',type:'VOLUME MILESTONE',description:`Accumulate ${snapshot.quests.fiveTonTrial.target.toLocaleString()} lb of lifting volume this week.`,progress:Math.round(snapshot.quests.fiveTonTrial.progress),target:snapshot.quests.fiveTonTrial.target,reward:'VOLUME CLEAR',icon:'trophy' as VQIconName,complete:snapshot.quests.fiveTonTrial.complete},
    {title:'The Long Road',type:'ENDURANCE MILESTONE',description:`Accumulate ${snapshot.quests.longRoad.target} lifetime running miles.`,progress:Number(snapshot.quests.longRoad.progress.toFixed(1)),target:snapshot.quests.longRoad.target,reward:'ENDURANCE CLEAR',icon:'agility' as VQIconName,complete:snapshot.quests.longRoad.complete},
    {title:'Restoration Ritual',type:'RECOVERY MILESTONE',description:`Complete ${snapshot.quests.restorationRitual.target} recovery protocols.`,progress:snapshot.quests.restorationRitual.progress,target:snapshot.quests.restorationRitual.target,reward:'RECOVERY CLEAR',icon:'streak' as VQIconName,complete:snapshot.quests.restorationRitual.complete},
    {title:'Veteran Path',type:'CAREER MILESTONE',description:`Complete ${snapshot.quests.veteranPath.target} lifetime training sessions.`,progress:snapshot.quests.veteranPath.progress,target:snapshot.quests.veteranPath.target,reward:'FORGED HELM',icon:'quest' as VQIconName,complete:snapshot.quests.veteranPath.complete},
  ],[snapshot]);
  const completedCount=activeQuests.filter(q=>q.complete).length;const campaignRatio=completedCount/activeQuests.length;
  return <SafeAreaView style={[styles.safe,{backgroundColor:t.background}]}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={[styles.page,wide&&styles.pageWide]}><View style={styles.shell}>
    <View><Text style={[styles.eyebrow,{color:t.accent}]}>QUEST BOARD</Text><Text style={[styles.title,{color:t.text}]}>Choose the next objective.</Text><Text style={[styles.lede,{color:t.muted}]}>Every active objective now reads directly from the same progression ledger and rule registry.</Text></View>
    <View style={[styles.tabs,{borderColor:t.border,backgroundColor:t.surface}]}>{(['Active','Completed','Guild'] as QuestTab[]).map(item=>{const active=item===tab;return <Pressable key={item} onPress={()=>setTab(item)} style={[styles.tab,active&&{backgroundColor:t.surfaceElevated,borderColor:t.accentSoft}]}><Text style={[styles.tabText,{color:active?t.accent:t.muted}]}>{item.toUpperCase()}</Text></Pressable>})}</View>
    {tab==='Active'?<><View style={[styles.campaign,{borderColor:t.border,backgroundColor:t.surface}]}><ImageBackground source={{uri:art}} resizeMode="cover" style={[styles.campaignArt,wide&&styles.campaignArtWide]}><View style={styles.shade}/><View style={styles.campaignCopy}><Text style={[styles.eyebrow,{color:t.accent}]}>MAIN QUEST · CHAPTER I</Text><Text style={[styles.campaignTitle,{color:t.text}]}>Forge the Complete Build</Text><Text style={[styles.campaignText,{color:t.text}]}>Clear the opening chain across resistance, endurance, restoration and career consistency.</Text></View></ImageBackground><View style={styles.campaignHud}><View style={styles.campaignMeta}><View><Text style={[styles.metaLabel,{color:t.muted}]}>OBJECTIVES</Text><Text style={[styles.metaValue,{color:t.text}]}>{completedCount} / {activeQuests.length}</Text></View><IconArt name="trophy" size={50}/></View><View style={[styles.track,{backgroundColor:t.surfaceElevated}]}><View style={[styles.fill,{width:`${campaignRatio*100}%`,backgroundColor:t.accent}]}/></View><Text style={[styles.progressCopy,{color:t.muted}]}>{Math.round(campaignRatio*100)}% complete · {activeQuests.length-completedCount} objectives remain</Text></View></View>
      <View style={styles.sectionHead}><View><Text style={[styles.eyebrow,{color:t.accent}]}>ACTIVE OBJECTIVES</Text><Text style={[styles.sectionTitle,{color:t.text}]}>Ledger-driven milestones.</Text></View><Text style={[styles.count,{color:t.muted}]}>{activeQuests.filter(q=>!q.complete).length} ACTIVE</Text></View><View style={[styles.questGrid,wide&&styles.questGridWide]}>{activeQuests.map((quest,index)=>{const ratio=Math.min(1,quest.progress/quest.target);return <View key={quest.title} style={[styles.questCard,{borderColor:quest.complete?t.positive:t.border,backgroundColor:t.surface}]}><View style={styles.questHeader}><IconArt name={quest.icon} size={46}/><View style={{flex:1}}><Text style={[styles.questType,{color:quest.complete?t.positive:t.accent}]}>{quest.complete?'CLEARED':quest.type}</Text><Text style={[styles.questTitle,{color:t.text}]}>{quest.title}</Text></View></View><Text style={[styles.questDescription,{color:t.muted}]}>{quest.description}</Text><View style={styles.questNumbers}><Text style={[styles.questCurrent,{color:t.text}]}>{quest.progress.toLocaleString()}</Text><Text style={[styles.questTarget,{color:t.muted}]}>/ {quest.target.toLocaleString()}</Text><Text style={[styles.reward,{color:t.accent}]}>{quest.reward}</Text></View><View style={[styles.track,{backgroundColor:t.surfaceElevated}]}><View style={[styles.fill,{width:`${ratio*100}%`,backgroundColor:quest.complete?t.positive:index===0?t.positive:t.accent}]}/></View><Text style={[styles.questFooter,{color:quest.complete?t.positive:t.muted}]}>{quest.complete?'OBJECTIVE CLEARED':`${Math.round(ratio*100)}% COMPLETE`}</Text></View>})}</View></>:tab==='Completed'?<View style={[styles.empty,{borderColor:t.border,backgroundColor:t.surface}]}><IconArt name="trophy" size={62}/><Text style={[styles.emptyTitle,{color:t.text}]}>{completedCount} quest{completedCount===1?'':'s'} cleared</Text><Text style={[styles.emptyCopy,{color:t.muted}]}>Current clears are derived from your activity ledger. Permanent quest-completion events are the next persistence upgrade.</Text></View>:<View style={[styles.empty,{borderColor:t.border,backgroundColor:t.surface}]}><IconArt name="quest" size={62}/><Text style={[styles.emptyTitle,{color:t.text}]}>Guild campaigns</Text><Text style={[styles.emptyCopy,{color:t.muted}]}>Co-op boss battles and shared quest chains remain on the social roadmap.</Text></View>}
  </View></ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1},page:{padding:14,paddingBottom:120},pageWide:{padding:24},shell:{width:'100%',maxWidth:1120,alignSelf:'center',gap:16},eyebrow:{fontSize:8,fontWeight:'900',letterSpacing:1.4},title:{fontFamily:Platform.select({ios:'Georgia',default:'serif'}),fontSize:34,fontWeight:'900',marginTop:5},lede:{fontSize:11.5,lineHeight:18,marginTop:6,maxWidth:650},tabs:{flexDirection:'row',borderWidth:1,borderRadius:14,padding:4,gap:4},tab:{flex:1,minHeight:42,borderWidth:1,borderColor:'transparent',borderRadius:10,alignItems:'center',justifyContent:'center'},tabText:{fontSize:8,fontWeight:'900'},campaign:{overflow:'hidden',borderWidth:1,borderRadius:20},campaignArt:{height:290,justifyContent:'flex-end'},campaignArtWide:{height:370},shade:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(0,0,0,.34)'},campaignCopy:{padding:20,maxWidth:620},campaignTitle:{fontFamily:Platform.select({ios:'Georgia',default:'serif'}),fontSize:31,fontWeight:'900',marginTop:5},campaignText:{fontSize:10.5,lineHeight:16,marginTop:6},campaignHud:{padding:16},campaignMeta:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:12},metaLabel:{fontSize:7,fontWeight:'900'},metaValue:{fontSize:16,fontWeight:'900',marginTop:3},track:{height:7,borderRadius:99,overflow:'hidden'},fill:{height:'100%',borderRadius:99},progressCopy:{fontSize:8,marginTop:7},sectionHead:{flexDirection:'row',alignItems:'flex-end',justifyContent:'space-between'},sectionTitle:{fontFamily:Platform.select({ios:'Georgia',default:'serif'}),fontSize:22,fontWeight:'900',marginTop:3},count:{fontSize:7,fontWeight:'900'},questGrid:{gap:10},questGridWide:{flexDirection:'row',flexWrap:'wrap'},questCard:{flex:1,minWidth:210,borderWidth:1,borderRadius:16,padding:15,minHeight:230},questHeader:{flexDirection:'row',alignItems:'center',gap:10},questType:{fontSize:7,fontWeight:'900'},questTitle:{fontSize:17,fontWeight:'900',marginTop:3},questDescription:{fontSize:9.5,lineHeight:15,marginTop:12,minHeight:44},questNumbers:{flexDirection:'row',alignItems:'baseline',marginTop:15,marginBottom:8},questCurrent:{fontSize:20,fontWeight:'900'},questTarget:{fontSize:10,fontWeight:'700',marginLeft:4},reward:{marginLeft:'auto',fontSize:7,fontWeight:'900'},questFooter:{fontSize:7,fontWeight:'900',marginTop:7},empty:{borderWidth:1,borderRadius:18,padding:34,alignItems:'center'},emptyTitle:{fontSize:21,fontWeight:'900',marginTop:10},emptyCopy:{fontSize:10.5,lineHeight:16,textAlign:'center',maxWidth:480,marginTop:6}});
