import React,{useState} from 'react';
import { Platform,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,useWindowDimensions,View } from 'react-native';
import { IconArt,VQIconName } from './IconArt';
import { useProgressionSnapshot } from './useProgression';
import { useVitalTheme } from './ThemeProvider';

type GoalTab='Active'|'Completed';
type GoalItem={title:string;type:string;description:string;progress:number;target:number;reward:string;icon:VQIconName;complete:boolean};
export default function QuestBoardV2(){
  const {theme}=useVitalTheme();const {snapshot}=useProgressionSnapshot();const t=theme.tokens;const {width}=useWindowDimensions();const wide=width>=760;const [tab,setTab]=useState<GoalTab>('Active');
  const goals:GoalItem[]=[
    {title:'Iron Week',type:'WEEKLY',description:`Complete ${snapshot.quests.ironWeek.target} resistance workouts this week.`,progress:snapshot.quests.ironWeek.progress,target:snapshot.quests.ironWeek.target,reward:'Builds weekly training consistency',icon:'strength',complete:snapshot.quests.ironWeek.complete},
    {title:'Five-Ton Week',type:'WEEKLY',description:`Accumulate ${snapshot.quests.fiveTonTrial.target.toLocaleString()} lb of lifting volume this week.`,progress:Math.round(snapshot.quests.fiveTonTrial.progress),target:snapshot.quests.fiveTonTrial.target,reward:'Builds volume progression',icon:'trophy',complete:snapshot.quests.fiveTonTrial.complete},
    {title:'The Long Road',type:'MILESTONE',description:`Accumulate ${snapshot.quests.longRoad.target} lifetime running miles.`,progress:Number(snapshot.quests.longRoad.progress.toFixed(1)),target:snapshot.quests.longRoad.target,reward:'Builds endurance progression',icon:'agility',complete:snapshot.quests.longRoad.complete},
    {title:'Restoration',type:'MILESTONE',description:`Complete ${snapshot.quests.restorationRitual.target} recovery sessions.`,progress:snapshot.quests.restorationRitual.progress,target:snapshot.quests.restorationRitual.target,reward:'Unlocks The Restored',icon:'streak',complete:snapshot.quests.restorationRitual.complete},
    {title:'Veteran',type:'MILESTONE',description:`Complete ${snapshot.quests.veteranPath.target} lifetime training sessions.`,progress:snapshot.quests.veteranPath.progress,target:snapshot.quests.veteranPath.target,reward:'Unlocks Forged Helm',icon:'quest',complete:snapshot.quests.veteranPath.complete},
  ];
  const active=goals.filter(g=>!g.complete);const completed=goals.filter(g=>g.complete);const items=tab==='Active'?active:completed;const ratio=completed.length/goals.length;
  return <SafeAreaView style={[styles.safe,{backgroundColor:t.background}]}><ScrollView contentContainerStyle={[styles.page,wide&&styles.pageWide]} showsVerticalScrollIndicator={false}><View style={styles.shell}>
    <View><Text style={[styles.eyebrow,{color:t.accent}]}>GOALS</Text><Text style={[styles.title,{color:t.text}]}>Know what you’re working toward.</Text><Text style={[styles.lede,{color:t.muted}]}>Goals turn the same training ledger into clear near-term targets and longer-term milestones.</Text></View>

    <View style={[styles.summary,{borderColor:t.border,backgroundColor:t.surface}]}><View><Text style={[styles.eyebrow,{color:t.accent}]}>CURRENT GOAL SET</Text><Text style={[styles.summaryTitle,{color:t.text}]}>{completed.length} of {goals.length} completed</Text><Text style={[styles.summaryCopy,{color:t.muted}]}>{active.length?`${active.length} active objective${active.length===1?'':'s'} still moving.`:'Current goal set complete.'}</Text></View><Text style={[styles.summaryPct,{color:t.accent}]}>{Math.round(ratio*100)}%</Text><View style={[styles.track,{backgroundColor:t.surfaceElevated}]}><View style={[styles.fill,{width:`${ratio*100}%`,backgroundColor:t.accent}]}/></View></View>

    <View style={[styles.tabs,{borderColor:t.border,backgroundColor:t.surface}]}>{(['Active','Completed'] as GoalTab[]).map(item=>{const selected=item===tab;return <Pressable key={item} onPress={()=>setTab(item)} style={[styles.tab,selected&&{backgroundColor:t.surfaceElevated,borderColor:t.accentSoft}]}><Text style={[styles.tabText,{color:selected?t.accent:t.muted}]}>{item.toUpperCase()} · {item==='Active'?active.length:completed.length}</Text></Pressable>})}</View>

    {items.length?<View style={[styles.grid,wide&&styles.gridWide]}>{items.map(goal=>{const goalRatio=Math.min(1,goal.progress/goal.target);return <View key={goal.title} style={[styles.card,{borderColor:goal.complete?t.positive:t.border,backgroundColor:t.surface}]}><View style={styles.cardHead}><IconArt name={goal.icon} size={38}/><View style={{flex:1}}><Text style={[styles.type,{color:goal.complete?t.positive:t.accent}]}>{goal.complete?'COMPLETED':goal.type}</Text><Text style={[styles.cardTitle,{color:t.text}]}>{goal.title}</Text></View></View><Text style={[styles.desc,{color:t.muted}]}>{goal.description}</Text><View style={styles.progressRow}><Text style={[styles.progressValue,{color:t.text}]}>{goal.progress.toLocaleString()}</Text><Text style={[styles.progressTarget,{color:t.muted}]}> / {goal.target.toLocaleString()}</Text></View><View style={[styles.track,{backgroundColor:t.surfaceElevated}]}><View style={[styles.fill,{width:`${goalRatio*100}%`,backgroundColor:goal.complete?t.positive:t.accent}]}/></View><Text style={[styles.reward,{color:goal.complete?t.positive:t.muted}]}>{goal.reward}</Text></View>})}</View>:<View style={[styles.empty,{borderColor:t.border,backgroundColor:t.surface}]}><IconArt name="trophy" size={52}/><Text style={[styles.emptyTitle,{color:t.text}]}>{tab==='Completed'?'No completed goals yet':'Current goals complete'}</Text><Text style={[styles.emptyCopy,{color:t.muted}]}>{tab==='Completed'?'Training and recovery will move these automatically.':'Your next goal set can build from the same progression ledger.'}</Text></View>}
  </View></ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1},page:{padding:16,paddingBottom:124},pageWide:{padding:28},shell:{width:'100%',maxWidth:1080,alignSelf:'center',gap:16},eyebrow:{fontSize:8,fontWeight:'900',letterSpacing:1.3},title:{fontFamily:Platform.select({ios:'Georgia',default:'serif'}),fontSize:36,fontWeight:'900',marginTop:5},lede:{fontSize:11,lineHeight:17,marginTop:6,maxWidth:650},summary:{borderWidth:1,borderRadius:18,padding:16},summaryTitle:{fontSize:22,fontWeight:'900',marginTop:4},summaryCopy:{fontSize:9.5,lineHeight:14,marginTop:4},summaryPct:{position:'absolute',right:16,top:16,fontSize:26,fontWeight:'900'},track:{height:7,borderRadius:99,overflow:'hidden',marginTop:12},fill:{height:'100%',borderRadius:99},tabs:{flexDirection:'row',borderWidth:1,borderRadius:14,padding:4,gap:4},tab:{flex:1,minHeight:42,borderWidth:1,borderColor:'transparent',borderRadius:10,alignItems:'center',justifyContent:'center'},tabText:{fontSize:8,fontWeight:'900',letterSpacing:.8},grid:{gap:10},gridWide:{flexDirection:'row',flexWrap:'wrap'},card:{flex:1,minWidth:230,borderWidth:1,borderRadius:17,padding:15,minHeight:205},cardHead:{flexDirection:'row',alignItems:'center',gap:10},type:{fontSize:7,fontWeight:'900',letterSpacing:.9},cardTitle:{fontSize:18,fontWeight:'900',marginTop:3},desc:{fontSize:9.5,lineHeight:15,marginTop:12,minHeight:44},progressRow:{flexDirection:'row',alignItems:'baseline',marginTop:10},progressValue:{fontSize:19,fontWeight:'900'},progressTarget:{fontSize:9,fontWeight:'700'},reward:{fontSize:7.5,fontWeight:'800',marginTop:8},empty:{borderWidth:1,borderRadius:18,padding:34,alignItems:'center'},emptyTitle:{fontSize:20,fontWeight:'900',marginTop:10},emptyCopy:{fontSize:10,lineHeight:16,textAlign:'center',marginTop:6,maxWidth:420}});