import React,{useState} from 'react';
import { ImageBackground,Platform,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,useWindowDimensions,View } from 'react-native';
import { IconArt,VQIconName } from './IconArt';
import { useProgressionSnapshot } from './useProgression';
import { useVitalTheme } from './ThemeProvider';
import { useHeroArchetype } from './useHeroArchetype';
import { materialForArchetype, paletteForArchetype, fonts } from './designSystem';
import { questArtForArchetype } from './artAssets';
import DataStatePanel from './DataStatePanel';
import { AnimatedBar, Entrance } from './Interaction';

type GoalTab='Active'|'Completed';
type GoalItem={title:string;type:'WEEKLY'|'MILESTONE';description:string;progress:number;target:number;reward:string;icon:VQIconName;complete:boolean};
const ratioFor=(goal:GoalItem)=>Math.min(1,goal.progress/Math.max(1,goal.target));
const remainingFor=(goal:GoalItem)=>Math.max(0,goal.target-goal.progress);
const format=(value:number)=>Number.isInteger(value)?value.toLocaleString():value.toFixed(1);

export default function QuestBoardV3(){
  const {theme}=useVitalTheme();const {snapshot,loading,error,refresh}=useProgressionSnapshot();const t=theme.tokens;const {width}=useWindowDimensions();const wide=width>=760;const compact=width<430;const {archetype}=useHeroArchetype();const palette=paletteForArchetype(archetype);const material=materialForArchetype(archetype);const [tab,setTab]=useState<GoalTab>('Active');
  const goals:GoalItem[]=[
    {title:'Iron Week',type:'WEEKLY',description:`Complete ${snapshot.quests.ironWeek.target} resistance workouts this week.`,progress:snapshot.quests.ironWeek.progress,target:snapshot.quests.ironWeek.target,reward:'Consistency seal',icon:'strength',complete:snapshot.quests.ironWeek.complete},
    {title:'Five-Ton Week',type:'WEEKLY',description:`Accumulate ${snapshot.quests.fiveTonTrial.target.toLocaleString()} lb of lifting volume this week.`,progress:Math.round(snapshot.quests.fiveTonTrial.progress),target:snapshot.quests.fiveTonTrial.target,reward:'Volume crest',icon:'trophy',complete:snapshot.quests.fiveTonTrial.complete},
    {title:'The Long Road',type:'MILESTONE',description:`Accumulate ${snapshot.quests.longRoad.target} lifetime running miles.`,progress:Number(snapshot.quests.longRoad.progress.toFixed(1)),target:snapshot.quests.longRoad.target,reward:'Endurance mark',icon:'agility',complete:snapshot.quests.longRoad.complete},
    {title:'Restoration',type:'MILESTONE',description:`Complete ${snapshot.quests.restorationRitual.target} recovery sessions.`,progress:snapshot.quests.restorationRitual.progress,target:snapshot.quests.restorationRitual.target,reward:'The Restored',icon:'streak',complete:snapshot.quests.restorationRitual.complete},
    {title:'Veteran',type:'MILESTONE',description:`Complete ${snapshot.quests.veteranPath.target} lifetime training sessions.`,progress:snapshot.quests.veteranPath.progress,target:snapshot.quests.veteranPath.target,reward:'Forged Helm',icon:'quest',complete:snapshot.quests.veteranPath.complete},
  ];
  const active=goals.filter(g=>!g.complete);const completed=goals.filter(g=>g.complete);const items=tab==='Active'?active:completed;const featured=[...active].sort((a,b)=>ratioFor(b)-ratioFor(a))[0]??completed[completed.length-1];

  return <SafeAreaView style={[s.safe,{backgroundColor:'transparent'}]}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={[s.page,wide&&s.pageWide]}><View style={s.shell}>
    <Entrance><View><Text style={[s.kicker,{color:palette.highlight}]}>GOALS · QUEST LEDGER</Text><Text style={[s.title,compact&&s.titleCompact,{color:t.text}]}>Your next objective awaits.</Text><Text style={[s.lede,{color:t.muted}]}>Every quest is advanced by the same real training ledger. Progress is earned, not tapped into existence.</Text></View></Entrance>
    {loading?<DataStatePanel kind="loading" title="Loading your goals" copy="Reading your training ledger and current milestones." icon="quest"/>:error?<DataStatePanel kind="error" title="Goals couldn’t load" copy={error} actionLabel="Try again" onAction={()=>void refresh()} icon="quest"/>:<>
      {featured?<Entrance delay={40}><View style={[s.mainQuest,{borderColor:material.edgeStrong}]}><ImageBackground source={{uri:questArtForArchetype(archetype)}} resizeMode="cover" style={s.mainQuestImage} imageStyle={s.mainQuestRadius}><View style={s.mainShade}/><View style={[s.contract,{borderColor:material.edgeStrong,backgroundColor:'rgba(4,8,12,.82)'}]}><View style={s.contractTop}><View style={[s.seal,{borderColor:material.edgeStrong,backgroundColor:material.glow}]}><IconArt name={featured.icon} size={38} tint={palette.highlight}/></View><View style={{flex:1}}><Text style={[s.kicker,{color:palette.highlight}]}>MAIN QUEST · {featured.type}</Text><Text style={s.mainTitle}>{featured.title}</Text><Text style={s.mainCopy}>{featured.description}</Text></View><View style={s.mainPctWrap}><Text style={s.mainPct}>{Math.round(ratioFor(featured)*100)}%</Text><Text style={s.micro}>COMPLETE</Text></View></View><View style={s.progressRow}><AnimatedBar progress={ratioFor(featured)} color={palette.primary} trackStyle={[s.track,{backgroundColor:'rgba(255,255,255,.12)'}]} barStyle={s.fill}/></View><View style={s.contractFoot}><View><Text style={s.micro}>NEXT MOVE</Text><Text style={s.footValue}>{format(remainingFor(featured))} remaining</Text></View><View style={{alignItems:'flex-end'}}><Text style={s.micro}>REWARD</Text><Text style={[s.reward,{color:palette.highlight}]}>{featured.reward}</Text></View></View></View></ImageBackground></View></Entrance>:null}

      <Entrance delay={80}><View style={[s.tabs,{borderColor:material.edge,backgroundColor:material.railSurface}]}>{(['Active','Completed'] as GoalTab[]).map(item=>{const selected=item===tab;return <Pressable key={item} onPress={()=>setTab(item)} style={[s.tab,selected&&{backgroundColor:material.elevatedSurface,borderColor:material.edgeStrong}]}><Text style={[s.tabText,{color:selected?palette.highlight:t.muted}]}>{item.toUpperCase()} · {item==='Active'?active.length:completed.length}</Text></Pressable>})}</View></Entrance>

      {items.length?<View style={[s.grid,wide&&s.gridWide]}>{items.map((goal,index)=>{const pct=Math.round(ratioFor(goal)*100);return <Entrance key={goal.title} delay={110+index*25} style={wide?s.goalEntranceWide:undefined}><View style={[s.goal,{borderColor:goal.complete?t.positive:material.edge,backgroundColor:goal.complete?material.elevatedSurface:material.railSurface}]}><View style={[s.goalRail,{backgroundColor:goal.complete?t.positive:palette.primary}]}/><View style={s.goalTop}><View style={[s.goalSeal,{borderColor:goal.complete?t.positive:material.edgeStrong,backgroundColor:material.glow}]}><IconArt name={goal.icon} size={31} tint={goal.complete?t.positive:palette.highlight}/></View><View style={{flex:1}}><Text style={[s.goalType,{color:goal.complete?t.positive:palette.highlight}]}>{goal.complete?'QUEST COMPLETE':goal.type}</Text><Text style={[s.goalTitle,{color:t.text}]}>{goal.title}</Text></View><Text style={[s.goalPct,{color:goal.complete?t.positive:t.text}]}>{pct}%</Text></View><Text style={[s.goalCopy,{color:t.muted}]}>{goal.description}</Text><AnimatedBar progress={ratioFor(goal)} color={goal.complete?t.positive:palette.primary} trackStyle={[s.track,{backgroundColor:t.surfaceElevated}]} barStyle={s.fill}/><View style={[s.goalFoot,{borderTopColor:material.edge}]}><View><Text style={[s.meta,{color:t.muted}]}>PROGRESS</Text><Text style={[s.metaValue,{color:t.text}]}>{format(goal.progress)} / {format(goal.target)}</Text></View><View style={{alignItems:'flex-end'}}><Text style={[s.meta,{color:t.muted}]}>REWARD</Text><Text style={[s.metaValue,{color:goal.complete?t.positive:palette.highlight}]}>{goal.reward}</Text></View></View></View></Entrance>})}</View>:<DataStatePanel kind="empty" title={tab==='Completed'?'No completed goals yet':'Current goals complete'} copy={tab==='Completed'?'Training and recovery will move these automatically.':'Your next goal set can build from the same progression ledger.'} icon="trophy"/>}
    </>}
  </View></ScrollView></SafeAreaView>;
}

const serif=fonts.display;
const s=StyleSheet.create({safe:{flex:1},page:{padding:16,paddingBottom:124},pageWide:{padding:28},shell:{width:'100%',maxWidth:1080,alignSelf:'center',gap:16},kicker:{fontSize:9,fontWeight:'900',letterSpacing:1.45},title:{fontFamily:serif,fontSize:40,lineHeight:45,fontWeight:'900',marginTop:5},titleCompact:{fontSize:34,lineHeight:39},lede:{fontSize:10.5,lineHeight:17,marginTop:7,maxWidth:650},mainQuest:{borderWidth:1,borderRadius:28,overflow:'hidden',minHeight:390},mainQuestImage:{minHeight:390,justifyContent:'flex-end'},mainQuestRadius:{borderRadius:27},mainShade:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(2,5,9,.28)'},contract:{margin:14,borderWidth:1,borderRadius:20,padding:17},contractTop:{flexDirection:'row',gap:12,alignItems:'flex-start'},seal:{width:62,height:62,borderRadius:31,borderWidth:1,alignItems:'center',justifyContent:'center'},mainTitle:{fontFamily:serif,fontSize:30,fontWeight:'800',color:'#FFF8EB',marginTop:4},mainCopy:{fontSize:10,lineHeight:15,color:'rgba(247,248,250,.72)',marginTop:5},mainPctWrap:{alignItems:'flex-end'},mainPct:{fontSize:30,fontWeight:'900',color:'#F7F8FA'},micro:{fontSize:9,fontWeight:'900',letterSpacing:.8,color:'rgba(247,248,250,.60)'},progressRow:{marginTop:15},track:{height:8,borderRadius:99,overflow:'hidden'},fill:{height:'100%',borderRadius:99},contractFoot:{flexDirection:'row',justifyContent:'space-between',gap:12,marginTop:11},footValue:{fontSize:13,fontWeight:'900',color:'#F7F8FA',marginTop:3},reward:{fontVariant:['tabular-nums'],fontSize:12,fontWeight:'900',marginTop:3},tabs:{flexDirection:'row',borderWidth:1,borderRadius:14,padding:4,gap:4},tab:{flex:1,minHeight:42,borderWidth:1,borderColor:'transparent',borderRadius:10,alignItems:'center',justifyContent:'center'},tabText:{fontSize:9.5,fontWeight:'900',letterSpacing:.9},grid:{gap:10},gridWide:{flexDirection:'row',flexWrap:'wrap'},goalEntranceWide:{flexGrow:1,flexBasis:320},goal:{flex:1,borderWidth:1,borderRadius:20,padding:16,minHeight:228,overflow:'hidden',position:'relative'},goalRail:{position:'absolute',left:0,top:0,bottom:0,width:3},goalTop:{flexDirection:'row',gap:10,alignItems:'flex-start'},goalSeal:{width:48,height:48,borderRadius:24,borderWidth:1,alignItems:'center',justifyContent:'center'},goalType:{fontSize:9,fontWeight:'900',letterSpacing:1},goalTitle:{fontSize:19,fontWeight:'900',marginTop:3},goalPct:{fontSize:20,fontWeight:'900'},goalCopy:{fontSize:9.5,lineHeight:15,marginTop:12,minHeight:42},goalFoot:{borderTopWidth:1,marginTop:13,paddingTop:10,flexDirection:'row',justifyContent:'space-between',gap:12},meta:{fontSize:9,fontWeight:'900',letterSpacing:.8},metaValue:{fontSize:9,fontWeight:'900',marginTop:3}});
