import React,{useState} from 'react';
import { Platform,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,useWindowDimensions,View } from 'react-native';
import { IconArt,VQIconName } from './IconArt';
import { useProgressionSnapshot } from './useProgression';
import { useVitalTheme } from './ThemeProvider';

type GoalTab='Active'|'Completed'|'Community';
type GoalItem={title:string;type:string;description:string;progress:number;target:number;reward:string;icon:VQIconName;complete:boolean};
export default function QuestBoardV2(){
  const {theme}=useVitalTheme();const {snapshot}=useProgressionSnapshot();const t=theme.tokens;const {width}=useWindowDimensions();const wide=width>=760;const [tab,setTab]=useState<GoalTab>('Active');
  const goals:GoalItem[]=[
    {title:'Iron Week',type:'WEEKLY GOAL',description:`Complete ${snapshot.quests.ironWeek.target} resistance workouts this week.`,progress:snapshot.quests.ironWeek.progress,target:snapshot.quests.ironWeek.target,reward:'Builds Arc progress',icon:'strength',complete:snapshot.quests.ironWeek.complete},
    {title:'Five-Ton Target',type:'VOLUME MILESTONE',description:`Accumulate ${snapshot.quests.fiveTonTrial.target.toLocaleString()} lb of lifting volume this week.`,progress:Math.round(snapshot.quests.fiveTonTrial.progress),target:snapshot.quests.fiveTonTrial.target,reward:'Builds Arc progress',icon:'trophy',complete:snapshot.quests.fiveTonTrial.complete},
    {title:'The Long Road',type:'ENDURANCE MILESTONE',description:`Accumulate ${snapshot.quests.longRoad.target} lifetime running miles.`,progress:Number(snapshot.quests.longRoad.progress.toFixed(1)),target:snapshot.quests.longRoad.target,reward:'Builds endurance progression',icon:'agility',complete:snapshot.quests.longRoad.complete},
    {title:'Recovery Consistency',type:'RECOVERY MILESTONE',description:`Complete ${snapshot.quests.restorationRitual.target} recovery sessions.`,progress:snapshot.quests.restorationRitual.progress,target:snapshot.quests.restorationRitual.target,reward:'Unlocks The Restored',icon:'streak',complete:snapshot.quests.restorationRitual.complete},
    {title:'Training Milestone',type:'CAREER MILESTONE',description:`Complete ${snapshot.quests.veteranPath.target} lifetime training sessions.`,progress:snapshot.quests.veteranPath.progress,target:snapshot.quests.veteranPath.target,reward:'Unlocks Forged Helm',icon:'quest',complete:snapshot.quests.veteranPath.complete},
  ];
  const completedGoals=goals.filter(q=>q.complete);const completed=completedGoals.length;const ratio=completed/goals.length;
  const renderCards=(items:GoalItem[])=><View style={[styles.grid,wide&&styles.gridWide]}>{items.map(q=>{const qRatio=Math.min(1,q.progress/q.target);return <View key={q.title} style={[styles.card,{borderColor:q.complete?t.positive:t.border,backgroundColor:t.surface}]}><View style={styles.cardHead}><IconArt name={q.icon} size={40}/><View><Text style={[styles.type,{color:q.complete?t.positive:t.accent}]}>{q.complete?'COMPLETED':q.type}</Text><Text style={[styles.cardTitle,{color:t.text}]}>{q.title}</Text></View></View><Text style={[styles.desc,{color:t.muted}]}>{q.description}</Text><View style={styles.numbers}><Text style={[styles.current,{color:t.text}]}>{q.progress.toLocaleString()}</Text><Text style={[styles.target,{color:t.muted}]}> / {q.target.toLocaleString()}</Text></View><View style={[styles.track,{backgroundColor:t.surfaceElevated}]}><View style={[styles.fill,{width:`${qRatio*100}%`,backgroundColor:q.complete?t.positive:t.accent}]}/></View><Text style={[styles.reward,{color:q.complete?t.positive:t.muted}]}>{q.reward}</Text></View>})}</View>;
  return <SafeAreaView style={[styles.safe,{backgroundColor:t.background}]}><ScrollView contentContainerStyle={[styles.page,wide&&styles.pageWide]} showsVerticalScrollIndicator={false}><View style={styles.shell}>
    <View><Text style={[styles.eyebrow,{color:t.accent}]}>GOALS</Text><Text style={[styles.title,{color:t.text}]}>Progress with a purpose.</Text><Text style={[styles.lede,{color:t.muted}]}>Every goal comes from the same activity ledger that powers XP, attributes and Rewards unlocks.</Text></View>
    <View style={[styles.tabs,{borderColor:t.border,backgroundColor:t.surface}]}>{(['Active','Completed','Community'] as GoalTab[]).map(item=>{const active=item===tab;return <Pressable key={item} onPress={()=>setTab(item)} style={[styles.tab,active&&{backgroundColor:t.surfaceElevated,borderColor:t.accentSoft}]}><Text style={[styles.tabText,{color:active?t.accent:t.muted}]}>{item.toUpperCase()}</Text></Pressable>})}</View>
    {tab==='Active'?<><View style={[styles.campaign,{borderColor:t.border,backgroundColor:t.surface}]}><View style={styles.campaignTop}><IconArt name="quest" size={46}/><View style={{flex:1}}><Text style={[styles.eyebrow,{color:t.accent}]}>FOUNDATION GOALS</Text><Text style={[styles.campaignTitle,{color:t.text}]}>Build the Complete Athlete</Text><Text style={[styles.campaignText,{color:t.muted}]}>Strength. Endurance. Recovery. Consistency. Complete the opening goal set by building a balanced performance base.</Text></View></View><View style={styles.campaignMeta}><View><Text style={[styles.metaLabel,{color:t.muted}]}>GOALS</Text><Text style={[styles.metaValue,{color:t.text}]}>{completed} / {goals.length}</Text></View><View><Text style={[styles.metaLabel,{color:t.muted}]}>STATUS</Text><Text style={[styles.metaValue,{color:t.accent}]}>{completed===goals.length?'COMPLETE':'IN PROGRESS'}</Text></View></View><View style={[styles.track,{backgroundColor:t.surfaceElevated}]}><View style={[styles.fill,{width:`${ratio*100}%`,backgroundColor:t.accent}]}/></View></View>
      <View style={styles.sectionHead}><View><Text style={[styles.eyebrow,{color:t.accent}]}>ACTIVE GOALS</Text><Text style={[styles.sectionTitle,{color:t.text}]}>What moves you forward</Text></View><Text style={[styles.count,{color:t.muted}]}>{goals.filter(q=>!q.complete).length} ACTIVE</Text></View>
      {renderCards(goals)}
    </>:tab==='Completed'?<>{completedGoals.length?<><View style={styles.sectionHead}><View><Text style={[styles.eyebrow,{color:t.positive}]}>COMPLETED GOALS</Text><Text style={[styles.sectionTitle,{color:t.text}]}>Earned through real activity</Text></View><Text style={[styles.count,{color:t.muted}]}>{completedGoals.length} COMPLETE</Text></View>{renderCards(completedGoals)}</>:<View style={[styles.empty,{borderColor:t.border,backgroundColor:t.surface}]}><IconArt name="trophy" size={58}/><Text style={[styles.emptyTitle,{color:t.text}]}>No goals completed yet</Text><Text style={[styles.emptyCopy,{color:t.muted}]}>Complete training and recovery sessions to move the ledger.</Text></View>}</>:<View style={[styles.empty,{borderColor:t.border,backgroundColor:t.surface}]}><IconArt name="quest" size={58}/><Text style={[styles.emptyTitle,{color:t.text}]}>Community goals</Text><Text style={[styles.emptyCopy,{color:t.muted}]}>Reserved for a later social phase.</Text></View>}
  </View></ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1},page:{padding:16,paddingBottom:124},pageWide:{padding:28},shell:{width:'100%',maxWidth:1120,alignSelf:'center',gap:16},eyebrow:{fontSize:8,fontWeight:'900',letterSpacing:1.4},title:{fontFamily:Platform.select({ios:'Georgia',default:'serif'}),fontSize:36,fontWeight:'900',marginTop:5},lede:{fontSize:11,lineHeight:17,marginTop:6},tabs:{flexDirection:'row',borderWidth:1,borderRadius:14,padding:4,gap:4},tab:{flex:1,minHeight:42,borderWidth:1,borderColor:'transparent',borderRadius:10,alignItems:'center',justifyContent:'center'},tabText:{fontSize:8,fontWeight:'900',letterSpacing:.9},campaign:{borderWidth:1,borderRadius:20,padding:18},campaignTop:{flexDirection:'row',gap:14,alignItems:'flex-start'},campaignTitle:{fontSize:27,fontWeight:'900',marginTop:4},campaignText:{fontSize:10,lineHeight:16,marginTop:6,maxWidth:650},campaignMeta:{flexDirection:'row',gap:28,marginTop:18},metaLabel:{fontSize:7,fontWeight:'900',letterSpacing:.8},metaValue:{fontSize:16,fontWeight:'900',marginTop:3},track:{height:7,borderRadius:99,overflow:'hidden',marginTop:12},fill:{height:'100%',borderRadius:99},sectionHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end'},sectionTitle:{fontSize:21,fontWeight:'900',marginTop:4},count:{fontSize:7,fontWeight:'900',letterSpacing:.8},grid:{gap:10},gridWide:{flexDirection:'row',flexWrap:'wrap'},card:{flex:1,minWidth:210,borderWidth:1,borderRadius:17,padding:15,minHeight:220},cardHead:{flexDirection:'row',alignItems:'center',gap:10},type:{fontSize:7,fontWeight:'900',letterSpacing:1},cardTitle:{fontSize:18,fontWeight:'900',marginTop:3},desc:{fontSize:10,lineHeight:16,marginTop:13,minHeight:48},numbers:{flexDirection:'row',alignItems:'baseline',marginTop:12},current:{fontSize:20,fontWeight:'900'},target:{fontSize:10,fontWeight:'700'},reward:{fontSize:8,fontWeight:'800',marginTop:8},empty:{borderWidth:1,borderRadius:18,padding:36,alignItems:'center'},emptyTitle:{fontSize:22,fontWeight:'900',marginTop:12},emptyCopy:{fontSize:11,lineHeight:17,textAlign:'center',marginTop:7}});