import { templates } from './data';
import { ProgressionSnapshot } from './progression';
import { EquipmentId, EXERCISE_CATALOG, equipmentSupports } from './trainingPreferences';
import type { TrainingIntelligence } from './trainingIntelligence';
import type { TrainingBlock } from './trainingBlock';
import { rememberRecommendation } from './recommendationMemory';

export type TrialId='push'|'pull'|'legs'|'run'|'recovery';
type ResistanceTrialId='push'|'pull'|'legs';
export type RecommendationPriority='RECOVERY'|'BALANCE'|'PROGRESSION';
export type ReadinessState='READY'|'MANAGE LOAD'|'RECOVER';
export type RecommendationConfidence='HIGH'|'MODERATE'|'LIMITED';
export type TrainingRecommendation={templateId:TrialId;label:string;title:string;reason:string;attributeFocus:string;priority:RecommendationPriority;signals:string[];readiness:ReadinessState;confidence:RecommendationConfidence;readinessReason:string;alternative:{templateId:TrialId;title:string;reason:string;attributeFocus:string};};

const ROLE:Record<TrialId,string>={push:'STRENGTH · DISCIPLINE',pull:'STRENGTH · DISCIPLINE',legs:'STRENGTH · STAMINA · DISCIPLINE',run:'STAMINA · AGILITY',recovery:'VITALITY · DISCIPLINE'};
function templateSupported(id:TrialId,equipment?:EquipmentId[]){if(!equipment?.length)return true;if(id==='run')return equipment.includes('cardio');if(id==='recovery')return equipment.includes('bodyweight');const template=templates.find(item=>item.id===id);if(!template)return false;return template.exercises.every(exercise=>{const catalog=EXERCISE_CATALOG.find(item=>item.id===exercise.id);return !catalog||equipmentSupports(catalog.equipment,equipment)})}
function hoursSince(value:string|null){if(!value)return Infinity;return Math.max(0,(Date.now()-new Date(value).getTime())/36e5)}
function resistanceCount(snapshot:ProgressionSnapshot,id:ResistanceTrialId){return id==='push'?snapshot.thisWeekPushWorkouts:id==='pull'?snapshot.thisWeekPullWorkouts:snapshot.thisWeekLegWorkouts}
function resistanceTitle(id:ResistanceTrialId){return id==='push'?'Push Day':id==='pull'?'Pull Day':'Leg Day'}
function pickBalancedResistance(snapshot:ProgressionSnapshot,equipment?:EquipmentId[]){const supported=(['push','pull','legs'] as ResistanceTrialId[]).filter(id=>templateSupported(id,equipment));if(!supported.length)return null;return [...supported].sort((a,b)=>{const diff=resistanceCount(snapshot,a)-resistanceCount(snapshot,b);if(diff!==0)return diff;const ar=snapshot.lastTemplateId===a?1:0,br=snapshot.lastTemplateId===b?1:0;if(ar!==br)return ar-br;return ['push','pull','legs'].indexOf(a)-['push','pull','legs'].indexOf(b)})[0]}
function alternativeFor(primary:TrialId,snapshot:ProgressionSnapshot,equipment?:EquipmentId[]){if(primary==='recovery'&&templateSupported('run',equipment))return{templateId:'run' as TrialId,title:'Endurance Run',reason:'Choose this if you feel fresh and want conditioning instead of restoration.',attributeFocus:ROLE.run};if(primary==='run'){const r=pickBalancedResistance(snapshot,equipment);if(r)return{templateId:r as TrialId,title:resistanceTitle(r),reason:'Choose this if you feel recovered and want resistance progression instead.',attributeFocus:ROLE[r]}}if(templateSupported('recovery',equipment))return{templateId:'recovery' as TrialId,title:'Recovery Protocol',reason:'Choose this if soreness or fatigue is higher than the ledger can detect.',attributeFocus:ROLE.recovery};if(templateSupported('run',equipment))return{templateId:'run' as TrialId,title:'Endurance Run',reason:'Choose this for a simple conditioning session.',attributeFocus:ROLE.run};return{templateId:primary,title:templates.find(t=>t.id===primary)?.name??'Recommended session',reason:'Your equipment profile limits alternatives.',attributeFocus:ROLE[primary]}}
function confidenceFor(snapshot:ProgressionSnapshot,intelligence?:TrainingIntelligence):RecommendationConfidence{const sessions=snapshot.workoutCount;const history=intelligence?.recent.length??0;const observed=intelligence?.coaching.observations??0;if(sessions>=8&&history>=6&&observed>=3)return'HIGH';if(sessions>=3&&history>=3)return'MODERATE';return'LIMITED'}
function readinessFor(snapshot:ProgressionSnapshot,intelligence?:TrainingIntelligence,block?:TrainingBlock|null){const recentHours=hoursSince(snapshot.lastWorkoutAt);const hardDays=intelligence?.consecutiveHardDays??0;const fatigue=intelligence?.fatigueScore??0;const regressing=intelligence?.performanceTrend==='REGRESSING';if(block?.phase==='DELOAD'&&snapshot.thisWeekWorkouts>=2)return{state:'RECOVER' as ReadinessState,reason:'You are in the Deload + Assess week. VitalQuest is deliberately reducing hard-session demand so gains can consolidate.'};if((hardDays>=3&&recentHours<30)||fatigue>=60)return{state:'RECOVER' as ReadinessState,reason:'Consecutive hard training and fatigue signals favor restoration before another demanding session.'};if(hardDays>=2||fatigue>=35||regressing||recentHours<18)return{state:'MANAGE LOAD' as ReadinessState,reason:regressing?'Recent output is trending down, so VitalQuest is protecting training quality.':'Recent workload is elevated; train, but avoid unnecessary volume or repeat stress.'};return{state:'READY' as ReadinessState,reason:block?.phase==='OVERLOAD'?'Readiness supports the Overload week. Progress selectively while quality remains high.':'Recent workload and performance signals support a normal training effort.'}}
function exposureSignal(intelligence?:TrainingIntelligence){const top=intelligence?.muscleExposure?.slice(0,2)??[];return top.length?`7d exposure: ${top.map(x=>`${x.muscle} ${x.sets} sets`).join(' · ')}`:null}
function coachingSignal(intelligence?:TrainingIntelligence){const c=intelligence?.coaching;if(!c)return null;if(c.observations===0)return'Coach calibration: LEARNING';return`Coach ${c.label} · ${c.calibrationScore}% calibration · ${c.observations} cycles`}
function blockSignal(block?:TrainingBlock|null){return block?`Arc W${block.week}/${block.totalWeeks} · ${block.phase}`:null}
function remember(rec:TrainingRecommendation){rememberRecommendation({recommendedTemplateId:rec.templateId,priority:rec.priority,readiness:rec.readiness,confidence:rec.confidence,source:'adaptive_engine'});return rec}

export function getTrainingRecommendation(snapshot:ProgressionSnapshot,equipment?:EquipmentId[],intelligence?:TrainingIntelligence,block?:TrainingBlock|null):TrainingRecommendation{
  const recentHours=hoursSince(snapshot.lastWorkoutAt);const resistance={push:snapshot.thisWeekPushWorkouts,pull:snapshot.thisWeekPullWorkouts,legs:snapshot.thisWeekLegWorkouts};const strengthLead=snapshot.strengthXP-Math.max(snapshot.staminaXP,snapshot.agilityXP);const readiness=readinessFor(snapshot,intelligence,block);const confidence=confidenceFor(snapshot,intelligence);const blockRecovery=block?.phase==='DELOAD'?2:0;const recoveryPressure=(snapshot.thisWeekWorkouts>=4?2:0)+(snapshot.streakDays>=4?2:0)+(recentHours<18?2:recentHours<30?1:0)+(snapshot.thisWeekRecoverySessions===0&&snapshot.thisWeekWorkouts>=3?1:0)+(intelligence?.consecutiveHardDays&&intelligence.consecutiveHardDays>=3?2:0)+(intelligence?.performanceTrend==='REGRESSING'?1:0)+blockRecovery;const enduranceGap=snapshot.workoutCount>=3&&strengthLead>=35&&snapshot.thisWeekEnduranceSessions===0&&block?.phase!=='DELOAD';const exposure=exposureSignal(intelligence);const coach=coachingSignal(intelligence);const arc=blockSignal(block);
  if((readiness.state==='RECOVER'||recoveryPressure>=4)&&templateSupported('recovery',equipment)){const primary:TrialId='recovery';const signals=[arc,coach,`${snapshot.thisWeekWorkouts} sessions this week`,`${intelligence?.consecutiveHardDays??0} consecutive hard days`,intelligence?.performanceTrend?`Performance: ${intelligence.performanceTrend}`:null,exposure].filter(Boolean).slice(0,4) as string[];return remember({templateId:primary,label:block?.phase==='DELOAD'?'ARC DELOAD':'RECOVERY RECOMMENDED',title:block?.phase==='DELOAD'?'Consolidate the gains from this Arc.':'Restore capacity before adding more load.',reason:block?.phase==='DELOAD'?'Week 4 is intentionally reducing training demand. Recovery now protects the work already banked and improves the quality of the next Arc.':'Your workload and readiness signals are stacking in the same direction. VitalQuest is prioritizing restoration so the next hard session can produce better output.',attributeFocus:ROLE[primary],priority:'RECOVERY',signals,readiness:readiness.state,confidence,readinessReason:readiness.reason,alternative:alternativeFor(primary,snapshot,equipment)})}
  if(enduranceGap&&templateSupported('run',equipment)){const primary:TrialId='run';return remember({templateId:primary,label:'BALANCE RECOMMENDED',title:'Build the engine behind your strength.',reason:`Strength is leading your conditioning attributes by ${strengthLead} XP and you have not logged endurance this week.`,attributeFocus:ROLE[primary],priority:'BALANCE',signals:[arc,coach,`Strength lead: ${strengthLead} XP`,'0 endurance sessions this week',intelligence?.performanceTrend?`Performance: ${intelligence.performanceTrend}`:`${snapshot.lifetimeMiles.toFixed(1)} lifetime miles`,exposure].filter(Boolean).slice(0,4) as string[],readiness:readiness.state,confidence,readinessReason:readiness.reason,alternative:alternativeFor(primary,snapshot,equipment)})}
  const balanced=pickBalancedResistance(snapshot,equipment);if(balanced){const count=resistanceCount(snapshot,balanced);const most=Math.max(resistance.push,resistance.pull,resistance.legs);const behind=most-count;const trend=intelligence?.performanceTrend;const overload=block?.phase==='OVERLOAD'&&readiness.state==='READY';const reason=behind>0?`${resistanceTitle(balanced)} is the least-trained resistance pattern this week. It restores balance while keeping progression moving.`:trend==='REGRESSING'?'Your split is balanced, but recent performance is softening. Keep the pattern moving with controlled volume rather than pushing for extra work.':overload?'Your split is balanced and readiness is good. The Overload phase supports a measured progression push today.':'Your resistance split is balanced, so VitalQuest is advancing the next supported pattern while avoiding an unnecessary repeat.';const primary:TrialId=balanced;return remember({templateId:primary,label:overload?'ARC OVERLOAD':behind>0?'BALANCE RECOMMENDED':'PROGRESSION RECOMMENDED',title:balanced==='push'?'Build pressing strength.':balanced==='pull'?'Build pulling strength and control.':'Raise lower-body capacity.',reason,attributeFocus:ROLE[primary],priority:behind>0?'BALANCE':'PROGRESSION',signals:[arc,coach,`This week P ${resistance.push} · PULL ${resistance.pull} · L ${resistance.legs}`,trend?`Performance: ${trend}`:'Performance trend: limited data',exposure].filter(Boolean).slice(0,4) as string[],readiness:readiness.state,confidence,readinessReason:readiness.reason,alternative:alternativeFor(primary,snapshot,equipment)})}
  if(templateSupported('recovery',equipment)){const primary:TrialId='recovery';return remember({templateId:primary,label:'EQUIPMENT-SAFE TRIAL',title:'Train what your environment supports.',reason:'Your equipment profile does not support the standard resistance templates, so VitalQuest selected recovery.',attributeFocus:ROLE[primary],priority:'RECOVERY',signals:[arc,coach,'Standard resistance templates unavailable','Bodyweight work is supported'].filter(Boolean).slice(0,4) as string[],readiness:readiness.state,confidence,readinessReason:readiness.reason,alternative:alternativeFor(primary,snapshot,equipment)})}
  const primary:TrialId='run';return remember({templateId:primary,label:'EQUIPMENT-SAFE TRIAL',title:'Build capacity with what is available.',reason:'Your equipment profile does not support the standard resistance templates. Endurance is the strongest supported path.',attributeFocus:ROLE[primary],priority:'BALANCE',signals:[arc,coach,'Resistance templates unavailable','Endurance remains available'].filter(Boolean).slice(0,4) as string[],readiness:readiness.state,confidence,readinessReason:readiness.reason,alternative:alternativeFor(primary,snapshot,equipment)});
}
