import { router } from 'expo-router';
import React from 'react';
import { Platform, SafeAreaView, ScrollView, StyleSheet, Text, useWindowDimensions, View } from 'react-native';
import { templates } from './data';
import { IconArt } from './IconArt';
import { ActionPressable, Entrance } from './Interaction';
import { getTrainingRecommendation } from './recommendation';
import { useProgressionSnapshot } from './useProgression';
import { useTrainingIntelligence } from './useTrainingIntelligence';
import { useTrainingSetup } from './useTrainingSetup';
import { useTrainingBlock } from './useTrainingBlock';
import { buildAdaptiveWeeklyPlan } from './weeklyPlan';
import { useVitalTheme } from './ThemeProvider';
import { useHeroArchetype } from './useHeroArchetype';
import { paletteForArchetype } from './designSystem';
import { deriveHeroEvolution, nextHeroFormMilestone } from './heroEvolution';

export default function TodayV2(){
  const {width}=useWindowDimensions();const wide=width>=760;const {theme}=useVitalTheme();const t=theme.tokens;
  const {snapshot}=useProgressionSnapshot();const intelligence=useTrainingIntelligence();const block=useTrainingBlock(intelligence);const {equipment}=useTrainingSetup();const {archetype}=useHeroArchetype();const palette=paletteForArchetype(archetype);
  const hero=deriveHeroEvolution(snapshot,archetype);const formMilestone=nextHeroFormMilestone(snapshot.level,snapshot.totalXP,archetype);
  const recommendation=getTrainingRecommendation(snapshot,equipment,intelligence,block);const plan=buildAdaptiveWeeklyPlan(block,recommendation,intelligence);const focusTemplate=templates.find(x=>x.id===recommendation.templateId)??templates[0];
  const levelRemaining=Math.max(0,snapshot.levelNeededXP-snapshot.levelCurrentXP);const nextSlots=plan.slots.slice(0,3);
  return <SafeAreaView style={[styles.safe,{backgroundColor:t.background}]}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={[styles.page,wide&&styles.pageWide]}><View style={styles.shell}>
    <Entrance><View style={styles.header}><View><Text style={[styles.wordmark,{color:t.text}]}>VITAL<Text style={{color:palette.primary}}>QUEST</Text></Text><Text style={[styles.kicker,{color:t.muted}]}>TODAY · ONE CLEAR NEXT STEP</Text></View><View style={[styles.levelChip,{backgroundColor:t.surface,borderColor:palette.primary}]}><Text style={[styles.levelLabel,{color:t.muted}]}>LEVEL</Text><Text style={[styles.levelValue,{color:t.text}]}>{snapshot.level}</Text></View></View></Entrance>

    <Entrance delay={35}><View style={[styles.progressCard,{borderColor:`${palette.primary}55`,backgroundColor:t.surface}]}><View style={{flex:1}}><Text style={[styles.eyebrow,{color:palette.highlight}]}>PROGRESS</Text><Text style={[styles.progressTitle,{color:t.text}]}>Level {snapshot.level} → {snapshot.level+1}</Text><Text style={[styles.copy,{color:t.muted}]}>{levelRemaining.toLocaleString()} XP until the next level · {hero.title} · Form {hero.formTier}</Text><View style={[styles.track,{backgroundColor:t.surfaceElevated}]}><View style={[styles.fill,{width:`${Math.min(100,snapshot.levelRatio*100)}%`,backgroundColor:palette.primary}]}/></View><View style={styles.rowBetween}><Text style={[styles.micro,{color:t.muted}]}>{snapshot.levelCurrentXP.toLocaleString()} / {snapshot.levelNeededXP.toLocaleString()} XP</Text><ActionPressable onPress={()=>router.push('/(tabs)/hero')} pressedScale={.97}><Text style={[styles.link,{color:palette.highlight}]}>VIEW PROGRESS ›</Text></ActionPressable></View></View></View></Entrance>

    <Entrance delay={70}><View style={[styles.recommendation,{borderColor:t.border,backgroundColor:t.surface}]}><View style={styles.recTop}><View style={{flex:1}}><Text style={[styles.eyebrow,{color:palette.highlight}]}>RECOMMENDED TODAY</Text><Text style={[styles.recTitle,{color:t.text}]}>{focusTemplate.name}</Text><Text style={[styles.recSub,{color:t.text}]}>{recommendation.title}</Text></View><View style={[styles.readiness,{borderColor:t.border,backgroundColor:t.heroSurface}]}><Text style={[styles.readinessLabel,{color:t.muted}]}>READINESS</Text><Text style={[styles.readinessValue,{color:t.text}]}>{recommendation.readiness}</Text></View></View><Text style={[styles.copy,{color:t.muted}]}>{recommendation.reason}</Text><View style={styles.signalRow}>{recommendation.signals.slice(0,2).map(signal=><View key={signal} style={[styles.signal,{borderColor:t.border,backgroundColor:t.heroSurface}]}><Text style={[styles.signalText,{color:t.muted}]}>{signal}</Text></View>)}</View><ActionPressable onPress={()=>router.push({pathname:'/workout',params:{templateId:focusTemplate.id}})} style={[styles.primary,{backgroundColor:palette.primary}]}><Text style={styles.primaryText}>START {focusTemplate.name.toUpperCase()}</Text></ActionPressable><ActionPressable onPress={()=>router.push('/(tabs)/train')} style={styles.secondaryLink} pressedScale={.98}><Text style={[styles.secondaryText,{color:palette.highlight}]}>SEE WHY + VIEW TRAINING PLAN ›</Text></ActionPressable></View></Entrance>

    {block?<Entrance delay={105}><View style={[styles.arc,{borderColor:t.border,backgroundColor:t.surface}]}><View style={styles.rowBetween}><View><Text style={[styles.eyebrow,{color:palette.highlight}]}>ACTIVE ARC</Text><Text style={[styles.arcTitle,{color:t.text}]}>{block.goalLabel}</Text><Text style={[styles.arcSub,{color:t.muted}]}>Week {block.week}/{block.totalWeeks} · {block.phase}</Text></View><View style={styles.arcScore}><Text style={[styles.arcScoreValue,{color:t.text}]}>{block.scorecard.adherence}%</Text><Text style={[styles.micro,{color:t.muted}]}>ADHERENCE</Text></View></View><View style={[styles.track,{backgroundColor:t.surfaceElevated}]}><View style={[styles.fill,{width:`${block.weeklyProgress*100}%`,backgroundColor:palette.primary}]}/></View><View style={styles.arcStats}><Text style={[styles.micro,{color:t.text}]}>{block.weeklyCompleted}/{block.weeklyTarget} sessions</Text><Text style={[styles.micro,{color:t.muted}]}>{Math.round(block.loadMultiplier*100)}% load guide</Text></View><View style={styles.nextRow}>{nextSlots.map(slot=><View key={slot.day} style={[styles.nextSlot,{borderColor:slot.status==='NEXT'?palette.primary:t.border,backgroundColor:t.heroSurface}]}><Text style={[styles.nextDay,{color:slot.status==='NEXT'?palette.highlight:t.muted}]}>{slot.label}</Text><Text style={[styles.nextName,{color:t.text}]}>{slot.title}</Text></View>)}</View><ActionPressable onPress={()=>router.push('/(tabs)/train')} pressedScale={.97}><Text style={[styles.link,{color:palette.highlight}]}>OPEN FULL ARC PLAN ›</Text></ActionPressable></View></Entrance>:null}

    <Entrance delay={140}><View style={[styles.week,{borderColor:t.border,backgroundColor:t.surface}]}><Mini label="THIS WEEK" value={`${snapshot.thisWeekWorkouts} sessions`} muted={t.muted} text={t.text}/><Mini label="PERFORMANCE" value={intelligence.performanceTrend} muted={t.muted} text={t.text}/><Mini label="STREAK" value={`${snapshot.streakDays} days`} muted={t.muted} text={t.text}/><Mini label="XP EARNED" value={`+${snapshot.thisWeekXP.toLocaleString()}`} muted={t.muted} text={t.text}/></View></Entrance>

    {formMilestone?<Entrance delay={175}><View style={[styles.milestone,{borderColor:t.border,backgroundColor:t.heroSurface}]}><IconArt name="trophy" size={38} tint={palette.highlight}/><View style={{flex:1}}><Text style={[styles.eyebrow,{color:palette.highlight}]}>NEXT MILESTONE</Text><Text style={[styles.milestoneTitle,{color:t.text}]}>{formMilestone.nextTitle} · Level {formMilestone.targetLevel}</Text><Text style={[styles.copy,{color:t.muted}]}>{formMilestone.xpRemaining.toLocaleString()} XP until the next progression form.</Text></View></View></Entrance>:null}
  </View></ScrollView></SafeAreaView>;
}
function Mini({label,value,muted,text}:{label:string;value:string;muted:string;text:string}){return <View style={styles.mini}><Text style={[styles.micro,{color:muted}]}>{label}</Text><Text style={[styles.miniValue,{color:text}]}>{value}</Text></View>}
const styles=StyleSheet.create({safe:{flex:1},page:{padding:16,paddingBottom:124},pageWide:{padding:28},shell:{width:'100%',maxWidth:1080,alignSelf:'center',gap:16},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},wordmark:{fontSize:27,fontWeight:'900',letterSpacing:-1.2},kicker:{fontSize:7,fontWeight:'900',letterSpacing:1.2,marginTop:2},levelChip:{borderWidth:1.5,borderRadius:14,paddingHorizontal:17,paddingVertical:10,alignItems:'center'},levelLabel:{fontSize:7,fontWeight:'900'},levelValue:{fontSize:21,fontWeight:'900'},eyebrow:{fontSize:8,fontWeight:'900',letterSpacing:1.25},copy:{fontSize:10,lineHeight:16,marginTop:6},progressCard:{borderWidth:1,borderRadius:20,padding:18},progressTitle:{fontFamily:Platform.select({ios:'Georgia',default:'serif'}),fontSize:31,fontWeight:'900',marginTop:4},track:{height:8,borderRadius:99,overflow:'hidden',marginTop:14},fill:{height:'100%',borderRadius:99},rowBetween:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:10,flexWrap:'wrap'},micro:{fontSize:7,fontWeight:'900',letterSpacing:.65},link:{fontSize:7,fontWeight:'900',letterSpacing:.75,marginTop:8},recommendation:{borderWidth:1,borderRadius:22,padding:18},recTop:{flexDirection:'row',gap:12,alignItems:'flex-start'},recTitle:{fontSize:29,fontWeight:'900',marginTop:4},recSub:{fontSize:12,fontWeight:'800',marginTop:4},readiness:{borderWidth:1,borderRadius:12,padding:10,minWidth:105,alignItems:'center'},readinessLabel:{fontSize:6.5,fontWeight:'900',letterSpacing:.7},readinessValue:{fontSize:13,fontWeight:'900',marginTop:4},signalRow:{flexDirection:'row',flexWrap:'wrap',gap:6,marginTop:10},signal:{borderWidth:1,borderRadius:999,paddingHorizontal:9,paddingVertical:6},signalText:{fontSize:7.5,fontWeight:'800'},primary:{minHeight:56,borderRadius:12,alignItems:'center',justifyContent:'center',marginTop:15},primaryText:{fontSize:9,fontWeight:'900',letterSpacing:.9,color:'#F4F1EA'},secondaryLink:{minHeight:38,alignItems:'center',justifyContent:'center',marginTop:4},secondaryText:{fontSize:7,fontWeight:'900',letterSpacing:.8},arc:{borderWidth:1,borderRadius:18,padding:16},arcTitle:{fontSize:21,fontWeight:'900',marginTop:4},arcSub:{fontSize:8.5,fontWeight:'800',marginTop:3},arcScore:{alignItems:'flex-end'},arcScoreValue:{fontSize:23,fontWeight:'900'},arcStats:{flexDirection:'row',justifyContent:'space-between',gap:8,marginTop:8},nextRow:{flexDirection:'row',gap:7,marginTop:12},nextSlot:{flex:1,borderWidth:1,borderRadius:11,padding:9,minHeight:62},nextDay:{fontSize:6.5,fontWeight:'900',letterSpacing:.7},nextName:{fontSize:9.5,fontWeight:'900',marginTop:4},week:{borderWidth:1,borderRadius:16,padding:12,flexDirection:'row',flexWrap:'wrap',gap:8},mini:{flex:1,minWidth:120},miniValue:{fontSize:15,fontWeight:'900',marginTop:3},milestone:{borderWidth:1,borderRadius:16,padding:14,flexDirection:'row',alignItems:'center',gap:11},milestoneTitle:{fontSize:16,fontWeight:'900',marginTop:3}});