import { router } from 'expo-router';
import React from 'react';
import { Platform, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, useWindowDimensions, View } from 'react-native';
import { IconArt } from './IconArt';
import { useTrainingIntelligence } from './useTrainingIntelligence';
import { useVitalTheme } from './ThemeProvider';

export default function TrainingInsightsV2(){
  const {theme}=useVitalTheme();const t=theme.tokens;const intel=useTrainingIntelligence();const {width}=useWindowDimensions();const wide=width>=760;
  return <SafeAreaView style={[styles.safe,{backgroundColor:t.background}]}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={[styles.page,wide&&styles.pageWide]}><View style={styles.shell}>
    <View style={styles.header}><View><Text style={[styles.eyebrow,{color:t.accent}]}>TRAINING INTELLIGENCE</Text><Text style={[styles.title,{color:t.text}]}>The ledger is learning you.</Text><Text style={[styles.lede,{color:t.muted}]}>VitalQuest uses this history to shape recommendations and generated workouts. No simulated progress—only saved training data.</Text></View><Pressable onPress={()=>router.back()} style={[styles.back,{borderColor:t.border}]}><Text style={[styles.backText,{color:t.text}]}>CLOSE</Text></Pressable></View>

    <View style={[styles.summary,wide&&styles.summaryWide]}><Metric icon="xp" value={String(intel.averageXP)} label="AVG XP"/><Metric icon="streak" value={`${intel.averageDuration}`} label="AVG MIN"/><Metric icon="strength" value={intel.averageVolume.toLocaleString()} label="AVG VOLUME"/><Metric icon="trophy" value={String(intel.recentPrs)} label="RECENT PRS"/></View>

    <View style={styles.sectionHead}><View><Text style={[styles.eyebrow,{color:t.accent}]}>EXERCISE SIGNALS</Text><Text style={[styles.sectionTitle,{color:t.text}]}>What is moving?</Text></View><Text style={[styles.count,{color:t.muted}]}>{intel.exerciseInsights.length} TRACKED</Text></View>
    {intel.exerciseInsights.length?<View style={[styles.grid,wide&&styles.gridWide]}>{intel.exerciseInsights.slice(0,8).map(item=><View key={item.exerciseId} style={[styles.exercise,{borderColor:t.border,backgroundColor:t.surface}]}><View style={styles.exerciseTop}><IconArt name={item.volumeTrendPct>=0?'strength':'streak'} size={36}/><Text style={[styles.trend,{color:item.volumeTrendPct>=0?t.accent:t.muted}]}>{item.volumeTrendPct>=0?'+':''}{item.volumeTrendPct}%</Text></View><Text style={[styles.exerciseName,{color:t.text}]}>{item.name}</Text><Text style={[styles.exerciseMeta,{color:t.muted}]}>{item.sessions} sessions · top {item.topWeight} lb</Text><View style={[styles.rule,{backgroundColor:t.border}]}/><Text style={[styles.exerciseDetail,{color:t.muted}]}>Recent avg set volume {item.recentVolume.toLocaleString()} lb</Text></View>)}</View>:<Empty title="No exercise history yet" copy="Complete resistance sessions and exercise-level trends will populate here automatically."/>}

    <View style={styles.sectionHead}><View><Text style={[styles.eyebrow,{color:t.accent}]}>RECENT ENCOUNTERS</Text><Text style={[styles.sectionTitle,{color:t.text}]}>Last 12 sessions</Text></View><Text style={[styles.count,{color:t.muted}]}>{intel.generatedSessions} AI-GENERATED</Text></View>
    {intel.recent.length?<View style={[styles.recentCard,{borderColor:t.border,backgroundColor:t.surface}]}>{intel.recent.map((session,index)=><View key={`${session.completedAt}-${index}`} style={[styles.recentRow,index<intel.recent.length-1&&{borderBottomWidth:1,borderBottomColor:t.border}]}><View style={[styles.sessionIcon,{borderColor:t.border}]}><IconArt name={session.templateId==='run'?'agility':session.templateId==='recovery'?'streak':session.templateId.startsWith('ai-')?'quest':'strength'} size={28}/></View><View style={{flex:1}}><Text style={[styles.sessionName,{color:t.text}]}>{session.name}</Text><Text style={[styles.sessionMeta,{color:t.muted}]}>{session.durationMinutes} min · {session.totalVolume.toLocaleString()} lb{session.templateId.startsWith('ai-')?' · GENERATED':''}</Text></View><Text style={[styles.sessionXP,{color:t.accent}]}>+{session.totalXP} XP</Text></View>)}</View>:<Empty title="The ledger is empty" copy="Your saved encounters will appear here and begin informing future training decisions."/>}

    <View style={[styles.insight,{borderColor:t.accentSoft,backgroundColor:t.heroSurface}]}><IconArt name="quest" size={44}/><View style={{flex:1}}><Text style={[styles.eyebrow,{color:t.accent}]}>CURRENT FORGE SIGNAL</Text><Text style={[styles.insightTitle,{color:t.text}]}>{intel.strongestTrend?.name??'Calibration phase'}</Text><Text style={[styles.insightCopy,{color:t.muted}]}>{intel.strongestTrend?`${intel.strongestTrend.name} is currently the strongest exercise-volume trend at ${intel.strongestTrend.volumeTrendPct>=0?'+':''}${intel.strongestTrend.volumeTrendPct}%. Generated plans can use this while balancing movements that are flattening.`:'A few completed sessions will give VitalQuest enough history to identify progression and fatigue signals.'}</Text></View></View>
  </View></ScrollView></SafeAreaView>
}
function Metric({icon,value,label}:{icon:'xp'|'streak'|'strength'|'trophy';value:string;label:string}){const {theme}=useVitalTheme();const t=theme.tokens;return <View style={[styles.metric,{borderColor:t.border,backgroundColor:t.surface}]}><IconArt name={icon} size={32}/><Text style={[styles.metricValue,{color:t.text}]}>{value}</Text><Text style={[styles.metricLabel,{color:t.muted}]}>{label}</Text></View>}
function Empty({title,copy}:{title:string;copy:string}){const {theme}=useVitalTheme();const t=theme.tokens;return <View style={[styles.empty,{borderColor:t.border,backgroundColor:t.surface}]}><Text style={[styles.emptyTitle,{color:t.text}]}>{title}</Text><Text style={[styles.emptyCopy,{color:t.muted}]}>{copy}</Text></View>}
const styles=StyleSheet.create({safe:{flex:1},page:{padding:14,paddingBottom:110},pageWide:{padding:24},shell:{width:'100%',maxWidth:1100,alignSelf:'center',gap:16},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start',gap:16},eyebrow:{fontSize:8,fontWeight:'900',letterSpacing:1.4},title:{fontFamily:Platform.select({ios:'Georgia',default:'serif'}),fontSize:35,lineHeight:40,fontWeight:'900',marginTop:5},lede:{fontSize:11,lineHeight:17,maxWidth:680,marginTop:6},back:{borderWidth:1,borderRadius:8,paddingHorizontal:12,paddingVertical:9},backText:{fontSize:7,fontWeight:'900',letterSpacing:.8},summary:{gap:8},summaryWide:{flexDirection:'row'},metric:{flex:1,borderWidth:1,borderRadius:14,padding:12,alignItems:'center'},metricValue:{fontSize:20,fontWeight:'900',marginTop:2},metricLabel:{fontSize:6.5,fontWeight:'900',letterSpacing:.8,marginTop:2},sectionHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end',gap:10,marginTop:4},sectionTitle:{fontFamily:Platform.select({ios:'Georgia',default:'serif'}),fontSize:23,fontWeight:'800',marginTop:4},count:{fontSize:7,fontWeight:'900',letterSpacing:.8},grid:{gap:8},gridWide:{flexDirection:'row',flexWrap:'wrap'},exercise:{borderWidth:1,borderRadius:15,padding:13,minHeight:150,flexGrow:1,flexBasis:240},exerciseTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},trend:{fontSize:14,fontWeight:'900'},exerciseName:{fontSize:15,fontWeight:'900',marginTop:8},exerciseMeta:{fontSize:8.5,marginTop:4},rule:{height:1,marginVertical:10},exerciseDetail:{fontSize:8.5},recentCard:{borderWidth:1,borderRadius:16,overflow:'hidden'},recentRow:{minHeight:68,padding:11,flexDirection:'row',alignItems:'center',gap:10},sessionIcon:{width:42,height:42,borderRadius:21,borderWidth:1,alignItems:'center',justifyContent:'center'},sessionName:{fontSize:11,fontWeight:'900'},sessionMeta:{fontSize:8,marginTop:3},sessionXP:{fontSize:10,fontWeight:'900'},insight:{borderWidth:1,borderRadius:16,padding:14,flexDirection:'row',alignItems:'center',gap:12},insightTitle:{fontSize:16,fontWeight:'900',marginTop:3},insightCopy:{fontSize:9,lineHeight:14,marginTop:4},empty:{borderWidth:1,borderRadius:15,padding:24,alignItems:'center'},emptyTitle:{fontSize:17,fontWeight:'900'},emptyCopy:{fontSize:9.5,lineHeight:15,textAlign:'center',maxWidth:500,marginTop:5}});
