export type EquipmentId = 'barbell' | 'dumbbells' | 'bench' | 'rack' | 'cables' | 'machines' | 'pullup' | 'cardio' | 'bodyweight';

export const EQUIPMENT_OPTIONS: Array<{id:EquipmentId;label:string;description:string}> = [
  {id:'barbell',label:'Barbell + Plates',description:'Bench, squat, deadlift, rows and overhead work.'},
  {id:'dumbbells',label:'Dumbbells',description:'Presses, rows, curls, split squats and accessory work.'},
  {id:'bench',label:'Adjustable Bench',description:'Flat and incline pressing plus supported movements.'},
  {id:'rack',label:'Squat / Power Rack',description:'Barbell squats, rack pulls and overhead work.'},
  {id:'cables',label:'Cable Station',description:'Pulldowns, rows and cable accessories.'},
  {id:'machines',label:'Machines',description:'Leg press, hamstring curl and selectorized work.'},
  {id:'pullup',label:'Pull-up Bar',description:'Pull-ups, chin-ups and hanging work.'},
  {id:'cardio',label:'Cardio / Outdoor',description:'Running, walking, biking and conditioning.'},
  {id:'bodyweight',label:'Bodyweight Space',description:'Mobility, recovery and no-equipment movements.'},
];

export const DEFAULT_EQUIPMENT: EquipmentId[] = ['barbell','dumbbells','bench','rack','cables','machines','pullup','cardio','bodyweight'];

export type CustomWorkoutExercise = {
  id:string;
  name:string;
  muscle:string;
  prescribedSets:number;
  targetReps:number;
};

export type CustomWorkoutTemplate = {
  id:string;
  name:string;
  createdAt:string;
  exercises:CustomWorkoutExercise[];
};

export type ExerciseCatalogItem = {
  id: string;
  name: string;
  muscle: string;
  equipment: EquipmentId[];
  defaultSets: number;
  defaultReps: number;
  /** Big multi-joint pattern — drives rest length, warm-up ramps, and progression jumps. */
  compound: boolean;
  /** Default rest between working sets, in seconds. */
  restSeconds: number;
  /** Load added (lb) when the top of the rep range is hit. 0 = progress by reps. */
  loadIncrement: number;
  /** 3-5 concise coaching cues shown in the workout. */
  cues: string[];
  /** Exercise ids training the same pattern — used for pain-aware swaps. */
  substitutes: string[];
};

export const EXERCISE_CATALOG:ExerciseCatalogItem[] = [
  {id:'bench',name:'Barbell Bench Press',muscle:'Chest · Strength',equipment:['barbell','bench'],defaultSets:3,defaultReps:8,compound:true,restSeconds:180,loadIncrement:5,substitutes:['db-bench','incline-db','pushup','machine-press'],cues:['Feet planted, upper back arched and tight','Lower the bar to mid-chest with control','Press in a slight J-curve back over the shoulders','Brace hard before you unrack — big breath, ribs down']},
  {id:'row',name:'Barbell Row',muscle:'Back · Strength',equipment:['barbell'],defaultSets:3,defaultReps:8,compound:true,restSeconds:150,loadIncrement:5,substitutes:['db-row','seated-row','chest-row'],cues:['Hinge to ~45 degrees, back flat as a table','Pull the bar to the lower ribs','Squeeze the shoulder blades for a beat','No bouncing — torso stays still']},
  {id:'ohp',name:'Overhead Press',muscle:'Shoulders · Power',equipment:['barbell'],defaultSets:3,defaultReps:8,compound:true,restSeconds:180,loadIncrement:5,substitutes:['db-ohp','machine-ohp','pushup'],cues:['Glutes squeezed, ribs down — no layback','Bar starts at the collarbone','Press up and slightly back, head through at the top','Lower with control to the chin, then the chest']},
  {id:'incline-db',name:'Incline Dumbbell Press',muscle:'Chest · Volume',equipment:['dumbbells','bench'],defaultSets:3,defaultReps:10,compound:true,restSeconds:120,loadIncrement:5,substitutes:['bench','db-bench','pushup'],cues:['Bench at ~30 degrees — higher becomes shoulders','Dumbbells touch the outer chest','Press up and slightly together','Keep the wrists stacked over the elbows']},
  {id:'pulldown',name:'Lat Pulldown',muscle:'Back · Control',equipment:['cables'],defaultSets:3,defaultReps:10,compound:false,restSeconds:90,loadIncrement:5,substitutes:['pullup','seated-row'],cues:['Chest tall, slight lean back','Drive the elbows down to the ribs','Pause one second at the bottom','Control the weight all the way up — no shrugging']},
  {id:'curl',name:'Dumbbell Curl',muscle:'Biceps · Accessory',equipment:['dumbbells'],defaultSets:3,defaultReps:10,compound:false,restSeconds:60,loadIncrement:2.5,substitutes:['hammer-curl','cable-curl'],cues:['Elbows pinned at your sides','Curl without swinging the torso','Squeeze hard at the top','Lower over a full 2-3 seconds']},
  {id:'squat',name:'Back Squat',muscle:'Quads · Strength',equipment:['barbell','rack'],defaultSets:3,defaultReps:6,compound:true,restSeconds:210,loadIncrement:10,substitutes:['leg-press','split-squat','goblet-squat'],cues:['Big breath, brace like a punch is coming','Knees track over the toes — push the floor apart','Hit depth: hip crease below the knee','Drive up fast, keep the chest proud']},
  {id:'rdl',name:'Romanian Deadlift',muscle:'Hamstrings · Strength',equipment:['barbell'],defaultSets:3,defaultReps:8,compound:true,restSeconds:150,loadIncrement:10,substitutes:['deadlift','good-morning','ham-curl'],cues:['Soft knees, push the hips straight back','Bar slides down the thighs, stays close','Feel the deep hamstring stretch, then snap the hips through','Back stays flat — the hinge is in the hips, not the spine']},
  {id:'split-squat',name:'Bulgarian Split Squat',muscle:'Legs · Stability',equipment:['dumbbells','bench'],defaultSets:3,defaultReps:10,compound:false,restSeconds:120,loadIncrement:5,substitutes:['lunge','step-up','leg-press'],cues:['Torso tall, most weight on the front leg','Lower straight down until the back knee hovers','Drive through the front heel','Keep the front knee over the ankle']},
  {id:'leg-press',name:'Leg Press',muscle:'Quads · Volume',equipment:['machines'],defaultSets:3,defaultReps:10,compound:true,restSeconds:150,loadIncrement:10,substitutes:['squat','split-squat'],cues:['Low back stays glued to the pad','Lower until knees are at ~90 degrees','Press through the full foot — not the toes','Never lock the knees hard at the top']},
  {id:'ham-curl',name:'Hamstring Curl',muscle:'Hamstrings · Accessory',equipment:['machines'],defaultSets:3,defaultReps:10,compound:false,restSeconds:90,loadIncrement:5,substitutes:['rdl','nordic-curl'],cues:['Hips stay down on the pad','Curl all the way — full range','Pause and squeeze at the top','Lower slowly, resist the weight']},
  {id:'calf',name:'Standing Calf Raise',muscle:'Calves · Capacity',equipment:['machines'],defaultSets:3,defaultReps:12,compound:false,restSeconds:60,loadIncrement:5,substitutes:['seated-calf'],cues:['Full stretch at the bottom — pause there','Rise as high as possible','Pause 1 second at the top','No bouncing — slow and deliberate']},
  {id:'pullup',name:'Pull-up',muscle:'Back · Bodyweight',equipment:['pullup'],defaultSets:3,defaultReps:8,compound:true,restSeconds:150,loadIncrement:0,substitutes:['pulldown','chinup'],cues:['Start from a dead hang','Chest to the bar, elbows driven down','No kipping — strict reps only','Lower all the way to straight arms']},
  {id:'pushup',name:'Push-up',muscle:'Chest · Bodyweight',equipment:['bodyweight'],defaultSets:3,defaultReps:12,compound:false,restSeconds:90,loadIncrement:0,substitutes:['bench','incline-db','dip'],cues:['Body in one straight line — glutes tight','Chest to the floor, elbows ~45 degrees','Push the floor away explosively','Hands under the shoulders']},
  {id:'lunge',name:'Walking Lunge',muscle:'Legs · Bodyweight',equipment:['bodyweight'],defaultSets:3,defaultReps:10,compound:false,restSeconds:90,loadIncrement:5,substitutes:['split-squat','step-up'],cues:['Long stride, torso tall','Back knee kisses the floor','Drive up through the front heel','Keep the front knee behind the toes']},
  {id:'carry',name:'Farmer Carry',muscle:'Grip · Conditioning',equipment:['dumbbells'],defaultSets:3,defaultReps:10,compound:false,restSeconds:120,loadIncrement:5,substitutes:['trap-carry'],cues:['Crush the handles','Tall posture — ribs down','Short, quick steps','Brace the core like a moving plank']},
  {id:'db-bench',name:'Flat Dumbbell Bench Press',muscle:'Chest · Strength',equipment:['dumbbells','bench'],defaultSets:3,defaultReps:8,compound:true,restSeconds:150,loadIncrement:5,substitutes:['bench','machine-press','incline-db','pushup'],cues:['Start with the dumbbells at the outer chest, wrists stacked over elbows','Press up and slightly together — control them, don\'t clank them','Feet planted, shoulder blades pinched hard into the bench','Lower for 2-3 seconds and touch the chest every rep']},
  {id:'machine-press',name:'Machine Chest Press',muscle:'Chest · Volume',equipment:['machines'],defaultSets:3,defaultReps:10,compound:true,restSeconds:120,loadIncrement:5,substitutes:['bench','db-bench','dip','pushup'],cues:['Set the seat so the handles align with mid-chest','Press without locking the elbows hard at the top','Keep your back flat against the pad — no bridging','Control the negative all the way back to the stretch']},
  {id:'dip',name:'Dip',muscle:'Chest · Bodyweight',equipment:['bodyweight'],defaultSets:3,defaultReps:8,compound:true,restSeconds:150,loadIncrement:0,substitutes:['pushup','bench','db-bench','close-grip-bench'],cues:['Use parallel bars or sturdy chair backs — lean the torso slightly forward to bias the chest','Lower until the shoulders are below the elbows','Keep the elbows tracking back, not flaring wide','Add weight with a belt once 3x12 is clean']},
  {id:'incline-bench',name:'Incline Barbell Bench Press',muscle:'Chest · Strength',equipment:['barbell','bench'],defaultSets:3,defaultReps:8,compound:true,restSeconds:180,loadIncrement:5,substitutes:['incline-db','bench','db-bench','machine-press'],cues:['Set the bench to about 30 degrees — steeper turns it into a shoulder press','Touch the bar to the upper chest, just below the collarbone','Use the same leg drive and upper-back arch as flat bench','Press straight up so the bar finishes over the shoulders']},
  {id:'db-fly',name:'Dumbbell Fly',muscle:'Chest · Accessory',equipment:['dumbbells','bench'],defaultSets:3,defaultReps:12,compound:false,restSeconds:90,loadIncrement:2.5,substitutes:['machine-press','dip','pushup','db-bench'],cues:['Keep a slight bend in the elbows — it must not change mid-rep','Open the arms wide until you feel a deep chest stretch','Hug an imaginary tree on the way back up','Never let the dumbbells drop below bench level']},
  {id:'deadlift',name:'Conventional Deadlift',muscle:'Back · Strength',equipment:['barbell'],defaultSets:3,defaultReps:6,compound:true,restSeconds:210,loadIncrement:10,substitutes:['sumo-deadlift','rdl','good-morning','trap-carry'],cues:['Bar over mid-foot, shins touching the bar before you pull','Hips high, chest up — wedge yourself between the bar and the floor','Drag the bar up your shins and thighs with the lats engaged','Stand tall with glutes squeezed; lower by pushing the hips straight back','Never round the lower back — reset every rep if you need to']},
  {id:'db-row',name:'Single-Arm Dumbbell Row',muscle:'Back · Strength',equipment:['dumbbells','bench'],defaultSets:3,defaultReps:10,compound:true,restSeconds:120,loadIncrement:5,substitutes:['row','seated-row','chest-row','single-arm-cable-row'],cues:['One knee and hand on the bench, back flat as a table','Let the dumbbell hang and the lat fully stretch at the bottom','Row the elbow toward the hip, not the shoulder','No torso rotation — keep the bench-side shoulder level']},
  {id:'chinup',name:'Chin-Up',muscle:'Back · Bodyweight',equipment:['pullup'],defaultSets:3,defaultReps:8,compound:true,restSeconds:150,loadIncrement:0,substitutes:['pullup','pulldown','db-row'],cues:['Underhand grip at shoulder width','Pull the chest to the bar — think elbows driving to the ribs','Start every rep from a dead hang','Lower under full control; no dropping into the bottom']},
  {id:'seated-row',name:'Seated Cable Row',muscle:'Back · Volume',equipment:['cables'],defaultSets:3,defaultReps:10,compound:true,restSeconds:120,loadIncrement:5,substitutes:['row','db-row','chest-row','pulldown'],cues:['Chest tall with a slight forward reach for the stretch','Pull the handle to the navel, elbows tight to the body','Squeeze the shoulder blades together at the back','Torso stays still — no swinging for momentum']},
  {id:'chest-row',name:'Chest-Supported Dumbbell Row',muscle:'Back · Control',equipment:['dumbbells','bench'],defaultSets:3,defaultReps:10,compound:true,restSeconds:120,loadIncrement:5,substitutes:['row','db-row','seated-row','t-bar-row'],cues:['Chest firmly on the incline bench — cheating is impossible here, which is the point','Let the arms hang long for a full lat stretch at the bottom','Row the dumbbells to the ribs and squeeze at the top','Keep the neck neutral — don\'t crane up to watch yourself']},
  {id:'t-bar-row',name:'T-Bar Row',muscle:'Back · Strength',equipment:['barbell'],defaultSets:3,defaultReps:8,compound:true,restSeconds:150,loadIncrement:5,substitutes:['row','chest-row','seated-row','db-row'],cues:['Hinge to about 45 degrees and brace the core hard','Pull the handle to the lower chest','Drive the elbows back and squeeze the mid-back','Strict torso — the bar moves, you don\'t']},
  {id:'bb-shrug',name:'Barbell Shrug',muscle:'Traps · Accessory',equipment:['barbell'],defaultSets:3,defaultReps:12,compound:false,restSeconds:60,loadIncrement:5,substitutes:['carry','trap-carry','db-row'],cues:['Stand tall with the bar resting at the thighs','Shrug straight up — ears toward shoulders','Pause one full second at the top of every rep','No rolling the shoulders, no bouncing the knees']},
  {id:'single-arm-cable-row',name:'Single-Arm Cable Row',muscle:'Back · Control',equipment:['cables'],defaultSets:3,defaultReps:12,compound:false,restSeconds:90,loadIncrement:2.5,substitutes:['seated-row','db-row','pulldown','chest-row'],cues:['Staggered stance, chest tall, handle at mid-torso height','Reach forward for a deep lat stretch at the start','Pull the elbow past the torso and squeeze','A slight torso rotation following the elbow is fine — don\'t stay rigid']},
  {id:'db-ohp',name:'Seated Dumbbell Overhead Press',muscle:'Shoulders · Strength',equipment:['dumbbells','bench'],defaultSets:3,defaultReps:8,compound:true,restSeconds:150,loadIncrement:5,substitutes:['ohp','machine-ohp','arnold-press','lateral-raise'],cues:['Bench upright, back supported, feet planted wide','Dumbbells start at shoulder height with palms facing in','Press straight up — don\'t let them drift forward','Lower to ear level with control on every rep']},
  {id:'machine-ohp',name:'Machine Shoulder Press',muscle:'Shoulders · Volume',equipment:['machines'],defaultSets:3,defaultReps:10,compound:true,restSeconds:120,loadIncrement:5,substitutes:['db-ohp','ohp','lateral-raise','arnold-press'],cues:['Set the seat so the handles start at shoulder height','Press up without shrugging the traps toward your ears','Keep the lower back pressed into the pad','Full lockout at the top, slow negative down']},
  {id:'lateral-raise',name:'Dumbbell Lateral Raise',muscle:'Shoulders · Accessory',equipment:['dumbbells'],defaultSets:3,defaultReps:12,compound:false,restSeconds:60,loadIncrement:2.5,substitutes:['machine-ohp','db-ohp','rear-delt-fly'],cues:['Keep a slight bend in the elbows — locked for the whole set','Lead with the elbows, not the hands','Raise to shoulder height and no higher','Pour the pitchers at the top: pinkies slightly up']},
  {id:'rear-delt-fly',name:'Reverse Dumbbell Fly',muscle:'Rear Delts · Accessory',equipment:['dumbbells','bench'],defaultSets:3,defaultReps:12,compound:false,restSeconds:60,loadIncrement:2.5,substitutes:['face-pull','lateral-raise','db-row'],cues:['Chest on the incline bench, arms hanging straight down','Open the arms wide in a reverse fly motion','Squeeze the rear delts — think elbows driving to the ceiling','Go light with perfect form — momentum ruins this exercise']},
  {id:'face-pull',name:'Face Pull',muscle:'Shoulders · Control',equipment:['cables'],defaultSets:3,defaultReps:15,compound:false,restSeconds:60,loadIncrement:2.5,substitutes:['rear-delt-fly','pulldown','lateral-raise'],cues:['Set the rope at eye level with thumbs toward you','Pull the rope to the forehead with elbows high and wide','Externally rotate at the end — knuckles to the ceiling','Don\'t lean back — the torso is a statue']},
  {id:'arnold-press',name:'Arnold Press',muscle:'Shoulders · Volume',equipment:['dumbbells'],defaultSets:3,defaultReps:10,compound:true,restSeconds:120,loadIncrement:5,substitutes:['db-ohp','machine-ohp','lateral-raise'],cues:['Start with palms facing you at chin height','Rotate the palms outward as you press overhead','Reverse the rotation on the way down','Keep the ribs down — no arching the back for extra reps']},
  {id:'hammer-curl',name:'Hammer Curl',muscle:'Biceps · Accessory',equipment:['dumbbells'],defaultSets:3,defaultReps:10,compound:false,restSeconds:60,loadIncrement:2.5,substitutes:['curl','cable-curl','preacher-curl'],cues:['Neutral grip — palms facing each other the whole time','Curl slightly across the body toward the opposite shoulder','Elbows pinned at your sides, torso perfectly still','Squeeze at the top, then lower over 2-3 seconds']},
  {id:'cable-curl',name:'Cable Curl',muscle:'Biceps · Accessory',equipment:['cables'],defaultSets:3,defaultReps:12,compound:false,restSeconds:60,loadIncrement:2.5,substitutes:['curl','hammer-curl','preacher-curl'],cues:['Stand close to the stack — constant tension is the point','Elbows locked at your sides for the entire set','Curl to full contraction without letting the stack touch down','Resist the cable all the way back down']},
  {id:'incline-db-curl',name:'Incline Dumbbell Curl',muscle:'Biceps · Accessory',equipment:['dumbbells','bench'],defaultSets:3,defaultReps:10,compound:false,restSeconds:60,loadIncrement:2.5,substitutes:['curl','hammer-curl','cable-curl'],cues:['Bench at about 45 degrees, arms hanging behind the torso','Let the biceps fully stretch at the bottom of every rep','Curl without letting the elbows drift forward','Go lighter than you think — the stretch position does the work']},
  {id:'preacher-curl',name:'Dumbbell Preacher Curl',muscle:'Biceps · Accessory',equipment:['dumbbells','bench'],defaultSets:3,defaultReps:10,compound:false,restSeconds:60,loadIncrement:2.5,substitutes:['curl','cable-curl','hammer-curl'],cues:['Armpits snug over the pad, arms fully extended at the start','Curl until the forearms are vertical','Never lift the elbows off the pad','Lower to a full stretch — that\'s where the growth stimulus lives']},
  {id:'tricep-pushdown',name:'Tricep Pushdown',muscle:'Triceps · Accessory',equipment:['cables'],defaultSets:3,defaultReps:12,compound:false,restSeconds:60,loadIncrement:2.5,substitutes:['overhead-tricep','skullcrusher','dip'],cues:['Elbows pinned at your sides — they never move','Push to a full lockout on every rep','Squeeze the triceps hard for one second at the bottom','Let the bar rise only until the elbows hit 90 degrees']},
  {id:'overhead-tricep',name:'Overhead Dumbbell Extension',muscle:'Triceps · Accessory',equipment:['dumbbells'],defaultSets:3,defaultReps:12,compound:false,restSeconds:60,loadIncrement:2.5,substitutes:['tricep-pushdown','skullcrusher','dip'],cues:['Hold one dumbbell overhead with both hands','Lower it behind the head — feel the deep triceps stretch','Elbows point forward and stay close to the head','Extend to full lockout without flaring the elbows out']},
  {id:'skullcrusher',name:'EZ-Bar Skullcrusher',muscle:'Triceps · Accessory',equipment:['barbell','bench'],defaultSets:3,defaultReps:10,compound:false,restSeconds:90,loadIncrement:2.5,substitutes:['tricep-pushdown','overhead-tricep','close-grip-bench'],cues:['Lower the bar to the forehead — or just behind the head for a deeper stretch','Upper arms stay vertical and motionless; only the forearms move','Extend to full lockout and squeeze','Stop a rep before the elbows complain — this one is spicy on the joints']},
  {id:'close-grip-bench',name:'Close-Grip Bench Press',muscle:'Triceps · Strength',equipment:['barbell','bench'],defaultSets:3,defaultReps:8,compound:true,restSeconds:150,loadIncrement:5,substitutes:['bench','tricep-pushdown','dip','skullcrusher'],cues:['Grip just inside shoulder width — narrower is not better','Tuck the elbows about 45 degrees on the way down','Touch the lower chest, then press straight up','Think about pushing the bar away with the triceps']},
  {id:'front-squat',name:'Front Squat',muscle:'Quads · Strength',equipment:['barbell','rack'],defaultSets:3,defaultReps:6,compound:true,restSeconds:210,loadIncrement:10,substitutes:['squat','goblet-squat','leg-press','hack-squat'],cues:['Bar rests on the front delts with the elbows held high','Torso stays vertical — fight the forward tip on every rep','Let the knees travel forward freely over the toes','Brace brutally hard; the rack position punishes a soft core']},
  {id:'goblet-squat',name:'Goblet Squat',muscle:'Quads · Volume',equipment:['dumbbells'],defaultSets:3,defaultReps:12,compound:false,restSeconds:90,loadIncrement:5,substitutes:['squat','front-squat','leg-press','step-up'],cues:['Hold the dumbbell at your chest like a goblet','Elbows track between the knees at the bottom','Sit deep — hips below the knees','Keep the chest proud and the heels planted']},
  {id:'leg-extension',name:'Leg Extension',muscle:'Quads · Accessory',equipment:['machines'],defaultSets:3,defaultReps:12,compound:false,restSeconds:60,loadIncrement:2.5,substitutes:['leg-press','hack-squat','goblet-squat'],cues:['Pad positioned just above the ankles','Extend to full lockout and squeeze the quads hard','Pause one second at the top of every rep','Lower over 2-3 seconds — no kicking or swinging']},
  {id:'hack-squat',name:'Hack Squat',muscle:'Quads · Strength',equipment:['machines'],defaultSets:3,defaultReps:8,compound:true,restSeconds:180,loadIncrement:10,substitutes:['squat','leg-press','front-squat'],cues:['Shoulders and back flat against the pads','Place the feet low on the platform to bias the quads','Drive through the full foot on every rep','Don\'t let the knees cave — actively push them out']},
  {id:'step-up',name:'Dumbbell Step-Up',muscle:'Legs · Stability',equipment:['dumbbells','bench'],defaultSets:3,defaultReps:10,compound:false,restSeconds:90,loadIncrement:5,substitutes:['split-squat','lunge','goblet-squat'],cues:['Bench at about knee height — higher is not better','Drive through the heel of the working leg','Don\'t push off the trailing foot — it just goes along for the ride','Control the step down — no dropping off the bench']},
  {id:'box-squat',name:'Box Squat',muscle:'Quads · Strength',equipment:['barbell','rack','bench'],defaultSets:3,defaultReps:6,compound:true,restSeconds:180,loadIncrement:10,substitutes:['squat','front-squat','leg-press'],cues:['Box set at parallel — touch it, don\'t crash onto it','Sit back first with shins near vertical','Pause on the box, then explode up','Keep the chest up and the brace locked the whole time']},
  {id:'good-morning',name:'Barbell Good Morning',muscle:'Hamstrings · Strength',equipment:['barbell'],defaultSets:3,defaultReps:8,compound:true,restSeconds:150,loadIncrement:5,substitutes:['rdl','deadlift','cable-pull-through'],cues:['Bar low on the traps, exactly like a squat','Soft knees — push the hips straight back','Lower until the torso is near parallel with hamstrings fully loaded','Start light — this movement humbles everyone']},
  {id:'nordic-curl',name:'Nordic Curl',muscle:'Hamstrings · Bodyweight',equipment:['bodyweight'],defaultSets:3,defaultReps:6,compound:false,restSeconds:120,loadIncrement:0,substitutes:['ham-curl','seated-leg-curl','rdl'],cues:['Anchor the feet securely, knees on a pad','Lower as slowly as possible — fight gravity the whole way','Keep the hips extended — don\'t break at the waist','Push off the floor to return until you\'re strong enough to curl back up']},
  {id:'hip-thrust',name:'Barbell Hip Thrust',muscle:'Glutes · Strength',equipment:['barbell','bench'],defaultSets:3,defaultReps:8,compound:true,restSeconds:150,loadIncrement:10,substitutes:['glute-bridge','deadlift','cable-pull-through'],cues:['Upper back on the bench, barbell over the hips','Chin tucked, ribs down — don\'t overextend the lower back','Drive through the heels to full hip extension','Squeeze the glutes hard for 2 seconds at the top']},
  {id:'glute-bridge',name:'Glute Bridge',muscle:'Glutes · Bodyweight',equipment:['bodyweight'],defaultSets:3,defaultReps:15,compound:false,restSeconds:60,loadIncrement:0,substitutes:['hip-thrust','cable-pull-through','deadlift'],cues:['Feet flat, knees bent, arms resting at your sides','Push through the heels and lift the hips as high as possible','Squeeze the glutes at the top while keeping the ribs down','Lower slowly — don\'t just drop']},
  {id:'seated-leg-curl',name:'Seated Leg Curl',muscle:'Hamstrings · Accessory',equipment:['machines'],defaultSets:3,defaultReps:12,compound:false,restSeconds:90,loadIncrement:2.5,substitutes:['ham-curl','nordic-curl','rdl'],cues:['Pad just above the ankles, hips pushed back in the seat','Curl to a full contraction','The seated position loads the stretched hamstring — respect the weight','Control the negative over 2-3 seconds']},
  {id:'cable-pull-through',name:'Cable Pull-Through',muscle:'Glutes · Accessory',equipment:['cables'],defaultSets:3,defaultReps:12,compound:false,restSeconds:90,loadIncrement:5,substitutes:['hip-thrust','good-morning','rdl'],cues:['Rope between the legs, then walk forward for tension','Hinge deep — let the weight pull you back','Snap the hips forward and squeeze the glutes at lockout','Arms stay straight — they\'re just hooks']},
  {id:'sumo-deadlift',name:'Sumo Deadlift',muscle:'Glutes · Strength',equipment:['barbell'],defaultSets:3,defaultReps:6,compound:true,restSeconds:210,loadIncrement:10,substitutes:['deadlift','hip-thrust','squat'],cues:['Wide stance, toes pointed out, shins vertical','Grip inside the knees with the chest proud','Push the floor away — wedge the hips toward the bar','Lock out with the glutes; don\'t lean back at the top']},
  {id:'seated-calf',name:'Seated Calf Raise',muscle:'Calves · Capacity',equipment:['machines'],defaultSets:3,defaultReps:15,compound:false,restSeconds:60,loadIncrement:2.5,substitutes:['calf','bw-calf-raise'],cues:['Knees bent to 90 degrees — this targets the soleus under the calf','Full stretch at the bottom with a brief pause','Rise as high as possible and hold one second','Higher reps work best here — embrace the burn']},
  {id:'plank',name:'Plank',muscle:'Core · Stability',equipment:['bodyweight'],defaultSets:3,defaultReps:60,compound:false,restSeconds:60,loadIncrement:0,substitutes:['dead-bug','ab-wheel','side-plank'],cues:['Elbows under the shoulders, body in one straight line (reps are seconds)','Squeeze the glutes and brace the abs as hard as possible','Don\'t let the hips sag down or pike up','Breathe behind the brace — never hold your breath']},
  {id:'side-plank',name:'Side Plank',muscle:'Core · Stability',equipment:['bodyweight'],defaultSets:3,defaultReps:45,compound:false,restSeconds:60,loadIncrement:0,substitutes:['plank','pallof-press','dead-bug'],cues:['Elbow directly under the shoulder, feet stacked (reps are seconds per side)','Hips high — body in one straight line','Don\'t let the hips drop toward the floor','Brace like someone is about to poke your side']},
  {id:'hanging-knee-raise',name:'Hanging Knee Raise',muscle:'Core · Bodyweight',equipment:['pullup'],defaultSets:3,defaultReps:12,compound:false,restSeconds:90,loadIncrement:0,substitutes:['cable-crunch','ab-wheel','dead-bug'],cues:['Start from a dead hang — no swinging','Curl the pelvis upward, driving the knees toward the chest','Lower slowly — the negative is half the exercise','If you start swinging, stop and reset']},
  {id:'cable-crunch',name:'Cable Crunch',muscle:'Core · Accessory',equipment:['cables'],defaultSets:3,defaultReps:15,compound:false,restSeconds:60,loadIncrement:2.5,substitutes:['ab-wheel','hanging-knee-raise','russian-twist'],cues:['Kneel facing the cable with the rope behind your head','Crunch the ribs toward the hips — round the spine deliberately','Hips stay still — this is spinal flexion, not a hip hinge','Squeeze the abs hard at the bottom of every rep']},
  {id:'ab-wheel',name:'Ab Wheel Rollout',muscle:'Core · Stability',equipment:['bodyweight'],defaultSets:3,defaultReps:10,compound:false,restSeconds:90,loadIncrement:0,substitutes:['plank','dead-bug','hanging-knee-raise'],cues:['Knees on a pad with the wheel under your shoulders','Roll out only as far as you can control','Keep the hips tucked — never let the lower back sag','Pull yourself back with the abs, not the arms']},
  {id:'pallof-press',name:'Pallof Press',muscle:'Core · Control',equipment:['cables'],defaultSets:3,defaultReps:10,compound:false,restSeconds:60,loadIncrement:2.5,substitutes:['dead-bug','side-plank','cable-crunch'],cues:['Cable at chest height, standing sideways to the stack','Press the handle straight out from the center of the chest','Resist the rotation — the torso does not move','Hold 2 seconds at full extension on every rep']},
  {id:'dead-bug',name:'Dead Bug',muscle:'Core · Control',equipment:['bodyweight'],defaultSets:3,defaultReps:10,compound:false,restSeconds:60,loadIncrement:0,substitutes:['plank','pallof-press','ab-wheel'],cues:['Lie on your back and press the lower back flat into the floor','Extend the opposite arm and leg slowly','If the lower back arches, you reached too far','Exhale as you extend and keep the core braced the whole time']},
  {id:'russian-twist',name:'Russian Twist',muscle:'Core · Accessory',equipment:['bodyweight'],defaultSets:3,defaultReps:20,compound:false,restSeconds:60,loadIncrement:0,substitutes:['cable-crunch','pallof-press','hanging-knee-raise'],cues:['Lean back slightly with the chest proud','Rotate the torso — the arms just follow along','Touch the floor on each side under control','Move slowly enough that momentum can\'t help you']},
  {id:'trap-carry',name:'Heavy Dumbbell Carry',muscle:'Grip · Conditioning',equipment:['dumbbells'],defaultSets:3,defaultReps:10,compound:false,restSeconds:120,loadIncrement:5,substitutes:['carry','deadlift','bb-shrug'],cues:['Go heavier than the standard farmer carry','Tall posture with the shoulders packed down','Short, choppy steps while bracing the core','Don\'t shrug — let the traps work statically']},
  {id:'db-swing',name:'Dumbbell Swing',muscle:'Glutes · Conditioning',equipment:['dumbbells'],defaultSets:3,defaultReps:15,compound:true,restSeconds:120,loadIncrement:5,substitutes:['deadlift','hip-thrust','burpee'],cues:['Hinge, don\'t squat — all the power comes from the hips','Snap the hips forward and let the dumbbell float to chest height','Arms are ropes — they don\'t lift anything','Brace at the top: glutes and abs locked']},
  {id:'box-jump',name:'Box Jump',muscle:'Legs · Power',equipment:['bodyweight','bench'],defaultSets:3,defaultReps:6,compound:false,restSeconds:120,loadIncrement:0,substitutes:['jump-squat','lunge','squat'],cues:['Use a sturdy box or bench at knee height or below','Swing the arms and explode upward','Land soft — knees bent, quiet feet','Step down, don\'t jump down — save the joints']},
  {id:'burpee',name:'Burpee',muscle:'Full Body · Conditioning',equipment:['bodyweight'],defaultSets:3,defaultReps:10,compound:false,restSeconds:90,loadIncrement:0,substitutes:['mountain-climber','jump-squat','db-swing'],cues:['Chest touches the floor on every rep — no half burpees','Jump the feet back into a strong plank position','Explode up with a full jump','Pace it — smooth is fast']},
  {id:'mountain-climber',name:'Mountain Climber',muscle:'Core · Conditioning',equipment:['bodyweight'],defaultSets:3,defaultReps:30,compound:false,restSeconds:60,loadIncrement:0,substitutes:['burpee','dead-bug','plank'],cues:['Hold a strong plank — hips level with the shoulders','Drive the knees toward the chest alternately','Keep the core braced; don\'t bounce the hips','Speed is earned — master control first']},
  {id:'jump-squat',name:'Jump Squat',muscle:'Legs · Power',equipment:['bodyweight'],defaultSets:3,defaultReps:10,compound:false,restSeconds:90,loadIncrement:0,substitutes:['box-jump','squat','lunge'],cues:['Dip to a quarter squat, then explode upward','Land soft with bent knees — absorb the impact','Reset briefly between reps for maximum power','Keep the chest up on every landing']},
  {id:'bw-calf-raise',name:'Bodyweight Calf Raise',muscle:'Calves · Capacity',equipment:['bodyweight'],defaultSets:3,defaultReps:20,compound:false,restSeconds:45,loadIncrement:0,substitutes:['calf','seated-calf'],cues:['Stand on a step edge so the heels can drop below the toes','Full stretch at the bottom with a brief pause','Rise as high as possible and hold one second at the top','Progress to single-leg once 3x20 is easy']},
];

export function equipmentSupports(required:EquipmentId[], available:EquipmentId[]) {
  return required.every(id=>available.includes(id));
}

/** Smart rest: catalog default, lengthened for heavy compound work. */
export function restSecondsFor(exerciseId: string, targetReps?: number): number {
  const item = EXERCISE_CATALOG.find((e) => e.id === exerciseId);
  if (!item) return 90;
  let rest = item.restSeconds;
  if (item.compound && targetReps != null && targetReps <= 6) rest = Math.max(rest, 180);
  if (!item.compound && targetReps != null && targetReps >= 12) rest = Math.min(rest, 75);
  return rest;
}

export function restLabel(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return m > 0 ? `${m}:${String(s).padStart(2, '0')}` : `${s}s`;
}

/** Pain-aware swaps: same-pattern alternatives that exist in the catalog and fit the equipment. */
export function findSubstitutes(exerciseId: string, equipment?: EquipmentId[]): ExerciseCatalogItem[] {
  const item = EXERCISE_CATALOG.find((e) => e.id === exerciseId);
  if (!item?.substitutes.length) return [];
  return item.substitutes
    .map((id) => EXERCISE_CATALOG.find((e) => e.id === id))
    .filter((e): e is ExerciseCatalogItem => !!e && e.id !== exerciseId)
    .filter((e) => !equipment?.length || equipmentSupports(e.equipment, equipment));
}
