import { fonts } from './designSystem';
import { router } from 'expo-router';
import React,{useMemo,useState} from 'react';
import { Platform,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View } from 'react-native';
import { IconArt } from './IconArt';
import { getVerificationCapabilities,requestGpsVerificationAccess,requestHealthVerificationAccess } from './sensorVerification';
import { useVitalTheme } from './ThemeProvider';

export default function VerificationSetupV2(){
  const {theme}=useVitalTheme();const t=theme.tokens;const styles=useMemo(()=>makeStyles(t),[t]);const caps=getVerificationCapabilities();
  const [health,setHealth]=useState<'idle'|'connected'|'unavailable'|'error'>(caps.healthAvailable?'idle':'unavailable');
  const [gps,setGps]=useState<'idle'|'connected'|'denied'|'error'>('idle');
  const [busy,setBusy]=useState<string|null>(null);
  async function connectHealth(){setBusy('health');try{const r=await requestHealthVerificationAccess();setHealth(r.available&&r.granted?'connected':'unavailable')}catch{setHealth('error')}finally{setBusy(null)}}
  async function connectGps(){setBusy('gps');try{const r=await requestGpsVerificationAccess();setGps(r.granted?'connected':'denied')}catch{setGps('error')}finally{setBusy(null)}}
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.page}><View style={styles.shell}>
    <View style={styles.top}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ BACK</Text></Pressable><Text style={styles.topMeta}>WEB BETA 1</Text></View>
    <View style={styles.hero}><IconArt name="xp" size={68}/><Text style={styles.eyebrow}>XP TRUST · BETA 1</Text><Text style={styles.title}>Prove the core loop first.</Text><Text style={styles.copy}>Beta 1 stays in the web app. VitalQuest is validating live session timing, set cadence, progression plausibility, overlap protection and optional browser GPS before native Health and wearable verification enter Beta 2.</Text></View>
    <Source title="LIVE APP EVIDENCE" subtitle="Resistance + recovery timing" status="active" detail="This is the primary Beta 1 verification path. VitalQuest uses encounter timing, set cadence, completed work, progression history and session integrity to determine how much XP is trusted." action="ACTIVE IN BETA 1" disabled={true} onPress={()=>{}} styles={styles}/>
    <Source title="BROWSER GPS" subtitle="Optional endurance verification" status={gps} detail="Available where the browser and device allow location access. VitalQuest derives endurance distance and elapsed time while the encounter is active." action="ENABLE GPS" disabled={busy!==null} onPress={connectGps} styles={styles}/>
    <Source title="HEALTH + WEARABLES" subtitle={Platform.OS==='ios'?'Apple Health / Apple Watch':'Health Connect / wearable workouts'} status={health} detail="Reserved for Beta 2. The plumbing already exists, but Beta 1 does not require TestFlight, Apple Watch, HealthKit or Health Connect." action={caps.healthAvailable?'BETA 2 SOURCE':'BETA 2 · NATIVE'} disabled={true} onPress={connectHealth} styles={styles}/>
    <View style={styles.ruleCard}><Text style={styles.eyebrow}>BETA 1 GOAL</Text><Text style={styles.ruleTitle}>Fair XP before stronger sensors.</Text><Text style={styles.copy}>A legitimate web-tracked workout should usually earn full-value corroborated XP. The beta is designed to expose false downgrades, bad XP pacing and logging friction before native sensors add more variables.</Text></View>
    <View style={styles.ruleCard}><Text style={styles.eyebrow}>FAIRNESS RULE</Text><Text style={styles.ruleTitle}>Sensors prove work. They do not buy power.</Text><Text style={styles.copy}>Native sources in Beta 2 will strengthen provenance, not inflate the raw value of a workout. A legitimate corroborated workout can still bank 100% XP without a wearable.</Text></View>
    <Pressable style={styles.primary} onPress={()=>router.push('/insights')}><Text style={styles.primaryText}>OPEN XP TRUST LEDGER</Text></Pressable>
  </View></ScrollView></SafeAreaView>
}
function Source({title,subtitle,status,detail,action,disabled,onPress,styles}:{title:string;subtitle:string;status:string;detail:string;action:string;disabled:boolean;onPress:()=>void;styles:any}){const connected=status==='connected'||status==='active';return <View style={styles.source}><View style={styles.sourceTop}><View style={styles.sourceIcon}><IconArt name={connected?'trophy':'quest'} size={42}/></View><View style={{flex:1}}><Text style={styles.sourceTitle}>{title}</Text><Text style={styles.sourceSub}>{subtitle}</Text></View><Text style={[styles.status,connected&&styles.statusOn]}>{status.toUpperCase()}</Text></View><Text style={styles.sourceDetail}>{detail}</Text><Pressable disabled={disabled||connected} onPress={onPress} style={[styles.sourceButton,(disabled||connected)&&styles.disabled]}><Text style={styles.sourceButtonText}>{connected&&status!=='active'?'CONNECTED':action}</Text></Pressable></View>}
function makeStyles(t:any){return StyleSheet.create({safe:{flex:1,backgroundColor:t.background},page:{padding:16,paddingBottom:100},shell:{width:'100%',maxWidth:820,alignSelf:'center',gap:14},top:{minHeight:44,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},back:{color:t.muted,fontSize:9,fontWeight:'900',letterSpacing:.8},topMeta:{color:t.accent,fontSize:8,fontWeight:'900',letterSpacing:1.2},hero:{borderWidth:1,borderColor:t.accentSoft,borderRadius:20,backgroundColor:t.heroSurface,padding:22,alignItems:'center'},eyebrow:{color:t.accent,fontSize:8,fontWeight:'900',letterSpacing:1.3,marginTop:5},title:{color:t.text,fontFamily:fonts.display,fontSize:31,lineHeight:36,fontWeight:'900',textAlign:'center',marginTop:6},copy:{color:t.muted,fontSize:10.5,lineHeight:17,textAlign:'center',marginTop:8},source:{borderWidth:1,borderColor:t.border,borderRadius:16,backgroundColor:t.surface,padding:15},sourceTop:{flexDirection:'row',alignItems:'center',gap:10},sourceIcon:{width:48,height:48,borderRadius:24,borderWidth:1,borderColor:t.border,alignItems:'center',justifyContent:'center'},sourceTitle:{color:t.text,fontSize:14,fontWeight:'900'},sourceSub:{color:t.muted,fontSize:8.5,marginTop:2},status:{color:t.muted,fontSize:9,fontWeight:'900',letterSpacing:.8},statusOn:{color:t.positive},sourceDetail:{color:t.muted,fontSize:9.5,lineHeight:15,marginTop:12},sourceButton:{minHeight:48,borderRadius:10,backgroundColor:t.accent,alignItems:'center',justifyContent:'center',marginTop:13},disabled:{opacity:.45},sourceButtonText:{color:t.background,fontSize:8.5,fontWeight:'900',letterSpacing:.9},ruleCard:{borderWidth:1,borderColor:t.border,borderRadius:16,backgroundColor:t.heroSurface,padding:16},ruleTitle:{color:t.text,fontSize:16,fontWeight:'900',marginTop:5},primary:{minHeight:54,borderRadius:10,borderWidth:1,borderColor:t.accent,alignItems:'center',justifyContent:'center'},primaryText:{color:t.accent,fontSize:9,fontWeight:'900',letterSpacing:.9}})}
